Repository data-team-uhn/cards, pull requests merged in 2020-12, with the labels that each got.

#372 LFS-751: Computed fields with value 0 handled incorrectly
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
Labels: tested

#364 LFS-734: Add time question support for minute and second format
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: tested

#345 LFS-671: Script for importing cardiac rehab questionnaires
  Utilities/JSON-to-XML/json_to_xml.py
  cardiac-rehab-resources/clinical-data/pom.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/ActiGraph data.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Baseline Health Information - Cardiovascular parameters.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Baseline Health Information - Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Cardiac Rehab Exercise Diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Daily diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Events.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Historical Lab Results.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Historical tests.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Study Visit.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Surveys.xml
  cardiac-rehab-resources/clinical-data/util/import.py
  cardiac-rehab-resources/pom.xml
  distribution/src/main/provisioning/01-boot.txt
  distribution/src/main/provisioning/62-cardiac-rehab-resources.txt
  pom.xml
Labels: tested

#374 LFS-749: Non-functioning parent links on the chart page
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested

#375 LFS-656: Upon successful creation of a new Subject, the Subjects page does not refresh
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#373 LFS-576: As a user, I can filter forms by questionnaire
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/QuestionnaireFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java
Labels: tested

#383 [misc] Reimport cardiac_rehab Participant Status form to add device id
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested

#381 LFS-618: React warning: scrollWidth prop
  modules/aggregated-frontend/src/main/frontend/webpack.config-template.js
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/principals/src/main/frontend/package.json
Labels: dependencies, tested

#388 [misc] Remove patient view from non-lfs runmodes
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions.json
  modules/data-entry/src/main/resources/SLING-INF/content/Extensions.json
Labels: tested

#380 LFS-763: Ensure that when querying subject types on LFS, the order of the results is Patient, Tumor, Tumor region
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/SubjectTypes.json
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/resources/SLING-INF/content/SubjectTypes.json
Labels: tested

#389 LFS-775: Delete buttons should not have a different color
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectType.jsx
Labels: tested

#386 LFS-159: As a user I can access a dashboard
  modules/commons/src/main/frontend/src/assetManager.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/frontend/webpack.config.js
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java
  modules/data-entry/src/main/resources/SLING-INF/content/Extensions.json
  modules/homepage/src/main/resources/SLING-INF/content/apps/lfs/ExtensionPoints/DashboardMenuItems.json
  modules/homepage/src/main/resources/SLING-INF/content/apps/lfs/ExtensionPoints/DashboardViews.json
Labels: tested, urgent

#354 LFS-698: Restructure the patient chart
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent

#379 Subject filter UI improvements: LFS-756, LFS-764
  modules/commons/src/main/frontend/src/SearchBar.jsx
  modules/commons/src/main/frontend/src/headerStyle.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/SubjectFilter.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/HeaderSearchBar.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/QuickSearchIdentifier.jsx
Labels: tested

#366 LFS-655: Handle re-login globally
  modules/commons/src/main/frontend/src/SearchBar.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/login/src/main/frontend/src/login/loginDialogue.js
Labels: urgent

#394 LFS-784: Questionnaires should be sorted alphabetically in the new form dialog
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
Labels: tested, urgent

#395 [cardiac_rehab] Hints on the visit number fields should match the visit numbers indicated in the questionnaire description
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information - Cardiovascular parameters.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information - Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
Labels: urgent

#398 LFS-722: Fields at the bottom of the form are inaccessible
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent

#396 [cardiac-rehab] Improve language in questionnaires
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, urgent

#384 LFS-757: As an API consumer, I can access the data recorded for a subject
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/BareFormProcessor.java
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/BareSubjectProcessor.java
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/DataSubjectProcessor.java
  modules/utils/src/main/java/ca/sickkids/ccm/lfs/serialize/ResourceToJsonAdapterFactory.java
Labels: urgent

#400 LFS-781: Set the appropriate rights to all Admin resources to prevent non-admin users from accessing them in the UI
  modules/homepage/src/main/provisioning/model.txt
  modules/homepage/src/main/resources/SLING-INF/content/Extensions.json
Labels: tested

#402 LFS-787: After a form is saved with an unanswered MM/yyyy date question, it can no longer be re-rendered
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
Labels: tested, urgent

#399 LFS-789: Browser-native login prompts appear when attempting to save forms with an invalid session
  compose-cluster/proxy/000-default.conf
  compose-cluster/proxy/Dockerfile
Labels: tested, urgent

#393 LFS-667: Questionnaire for uploading external data files
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/External file.xml
Labels: urgent

#407 LFS-573: Values displayed in patient charts are the raw stored values, not the user-friendly ones
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent

#403 LFS-758: Create a JSON processor for obfuscating dates
  cardiac-rehab-resources/backend/pom.xml
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/serialize/DateObfuscationProcessor.java
  cardiac-rehab-resources/pom.xml
  distribution/src/main/provisioning/62-cardiac-rehab-resources.txt
Labels: tested, urgent

#411 [cardiac-rehab] Switched participant date of birth format from MM/yyyy to yyyy
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: urgent

#408 [misc] Properly save dates across all valid dateFormats
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent

#413 [cardiac_rehab] Changed variable name to match the format of other var names in the form
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, urgent

#412 LFS-774: Some fields in Cardiac rehab should be switched to single entry numeric fields
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Cardiac Rehab Exercise Diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, urgent

#409 LFS-792: The app name, platform name, and platform version should be displayed to the user on every page
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/conf.json
  cardiac-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/conf.json
  modules/commons/src/main/resources/SLING-INF/content/libs/lfs/Resource/header.html
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebar.jsx
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebarStyle.jsx
  modules/homepage/src/main/resources/SLING-INF/nodetypes/homepage.cnd
  modules/login/src/main/resources/SLING-INF/nodetypes/login.cnd
  modules/utils/src/main/resources/SLING-INF/libs/lfs/conf.json
  pom.xml
Labels: tested, urgent

#414 [misc] Reimport cardiac rehab questionnaires
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information - Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Cardiac Rehab Exercise Diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Daily diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
  cardiac-rehab-resources/clinical-data/util/import.py
Labels: tested, urgent

#417 LFS-761: Cardiac Rehab Medication 1 and 2 conditionals are incorrect
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information - Medications.xml
Labels: tested

#416 LFS-747 / LFS-802: Multiple choice questions should support the "None of the above" option
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information - Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Events.xml
  cardiac-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/0-5NDVariables.xml
  cardiac-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6-21NDVariables.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Demographics.xml
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: tested, urgent

#415 LFS-796: Allow for an external MongoDB instance (and its credentials) to be defined when generating a docker-compose environment
  compose-cluster/.gitignore
  compose-cluster/cleanup.sh
  compose-cluster/generate_compose_yaml.py
  distribution/Dockerfile
  distribution/docker_entry.sh
  pom.xml
Labels: urgent

#418 LFS-780: Forms and Subjects views should be consistent with the corresponding Dashboard boxes
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
Labels: tested, urgent

#419 [misc] Use stdout/stderr for logging in Docker
  distribution/Dockerfile
  distribution/logback.xml
  distribution/src/main/provisioning/10-sling-base.txt
Labels: urgent

#421 LFS-730: Set up sending data via the S3 ingest API
  cardiac-rehab-resources/backend/pom.xml
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/NightlyExport.java
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/NightlyExportTask.java
  cardiac-rehab-resources/backend/src/main/provisioning/model.txt
Labels: urgent
