Repository data-team-uhn/cards, pull requests merged in 2020-11, with the labels that each got.

#331 LFS-469: Upgrade versions of sling, jackrabbit, oak and dependencies
  distribution/src/main/provisioning/02-oak.txt
  distribution/src/main/provisioning/10-sling-base.txt
  modules/custom-jcr-oak-server/README.md
  modules/custom-jcr-oak-server/pom.xml
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/DefaultThreadPoolRegistrar.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/OakSlingRepository.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/OakSlingRepositoryManager.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/OakSlingRepositoryManagerConfiguration.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/TcclWrappingJackrabbitRepository.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/TcclWrappingJackrabbitSession.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/WhiteboardCommitHook.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/WhiteboardRepositoryInitializer.java
  modules/custom-jcr-oak-server/src/main/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/internal/package-info.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/DynamicOakServerIT.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/LoginAdminBlacklistedIT.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/LoginAdminWhitelistedIT.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/OakServerIT.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/OakServerTestSupport.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/ResourceEventListener.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/ResourceTypeResolutionIT.java
  modules/custom-jcr-oak-server/src/test/java/ca/sickkids/ccm/lfs/sling/jcr/oak/server/it/Retry.java
  modules/custom-jcr-oak-server/src/test/resources/i18n.cnd
  modules/custom-jcr-oak-server/src/test/resources/repoinit.txt
  modules/pom.xml
Labels: dependencies, tested

#317 LFS-630: Add an extension point allowing the insertion of visual element at the top of each page
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectType.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/homepage/src/main/frontend/src/themePage/PageStart/PageStart.jsx
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebar.jsx
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebarStyle.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/homepage/src/main/resources/SLING-INF/content/apps/lfs/ExtensionPoints/PageStart.json
Labels: tested

#316 LFS-613: Fix questionnaire deletion and remove duplicate Actions column
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/EditButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectTypes.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/DeleteQuestionnaireDialog.jsx
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DeleteServlet.java
Labels: tested

#312 LFS-619: Improve query performance
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/ResourceIterator.java
Labels: tested

#340 [misc] Upgrade Node and Yarn
  pom.xml
Labels: dependencies, tested

#310 LFS-602: Pagination for Forms
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: bug

#337 [misc] Update the docker maven plugin
  distribution/pom.xml
Labels: dependencies

#332 LFS-317: Computed Question
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: tested

#346 LFS-317: Computed Fields Adjustments
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: tested

#343 LFS-701: In the Questionnaire wizard, display all question properties that have a set value in view mode
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
Labels: tested

#342 LFS-638: Data tables improvements. Includes subtasks LFS-607, LFS-555, LFS-606, LFS-609
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectTypes.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectDirectory.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectType.jsx
  modules/homepage/src/main/frontend/src/themePage/EntityIdentifier.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/HeaderSearchBar.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchResults.jsx
Labels: tested

#347 LFS-713 Do not display #1 after the section title if the section is non-recurrent
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested

#352 LFS-651: Form contents are visible above the form's sticky header when scrolling
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested

#348 LFS-709: Subject selector improvements; LFS-721:Unable to create Tumor form in a specific situation; LFS-688: UI anomaly when having multiple tumors with the same name
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#349 LFS-707: Improve the look of the quick search results; LFS-264: As a user, I can open the resources provided as suggestions to my quick search in a new browser tab or window
  modules/commons/src/main/frontend/src/SearchBar.jsx
  modules/commons/src/main/frontend/src/headerStyle.jsx
  modules/homepage/src/main/frontend/src/themePage/EntityIdentifier.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/HeaderSearchBar.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/QuickSearchIdentifier.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchResults.jsx
Labels: tested

#353 LFS-697: Forms with conditional sections are not properly marked as COMPLETE or INCOMPLETE
  modules/form-completion-status/src/main/java/ca/sickkids/ccm/lfs/formcompletionstatus/AnswerCompletionStatusEditor.java
  modules/form-completion-status/src/main/java/ca/sickkids/ccm/lfs/formcompletionstatus/AnswerCompletionStatusEditorProvider.java
  modules/form-completion-status/src/main/java/ca/sickkids/ccm/lfs/formcompletionstatus/ConditionalSectionUtils.java
Labels: tested

#357 LFS-573: Check for label in displayQuestion method
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: bug

#370 LFS-714: Remove Data from all LFS Questionnaire titles
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Chemotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Demographics.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Radiotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Tumors.xml
  lfs-resources/tissue-metrix/src/main/resources/SLING-INF/content/TissueMetrix.xml
  modules/variants/src/main/resources/SLING-INF/content/Questionnaires/SomaticVariants.xml
Labels: tested

#368 LFS-745: Backend verification marks fields as INVALID,INCOMPLETE if question is missing minAnswers and maxAnswers fields
  modules/form-completion-status/src/main/java/ca/sickkids/ccm/lfs/formcompletionstatus/AnswerCompletionStatusEditor.java
Labels: tested

#371 LFS-748: Subject selection dialog unexpectedly switches page size
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#361 LFS-731: Support more than 10 forms
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
Labels: tested
