Repository data-team-uhn/cards, pull requests merged in 2021-10, with the labels that each got.

#780 CARDS-1403: Inform the user if there are min/max value requirements for the answers of numeric questions
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, easy to review

#781 CARDS-1404: As a questionnaire designer I can specify numeric questions of type "range"
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/RangeTest.xml
Labels: tested

#783 CARDS-1347: Evaluate computed fields serverside
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/FormUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/QuestionnaireUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/AbstractNodeUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ComputedAnswersEditor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ComputedAnswersEditorProvider.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ExpressionUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/FormUtilsImpl.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/QuestionnaireUtilsImpl.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ServersideComputedTest.xml
Labels: tested, Merge me!, current sprint

#799 CARDS-510: Clicking on a bar in a chart displayed in Statistics should open the Subjects page with subjects filtered appropriately to display those matching the clicked bar
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
  modules/statistics/src/main/frontend/src/Statistics/UserStatistics.jsx
Labels: tested, Merge me!, easy to review, current sprint
