Repository data-team-uhn/cards, pull requests merged in 2021-08, with the labels that each got.

#714 [misc] Fixed build on pristine instances: wrong parent for the moved aggregated-frontend module
  aggregated-frontend/pom.xml
  pom.xml
Labels: Merge me!, easy to review, tested

#717 CARDS-1285: Update app name and logo for cards4kids
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/background.jpg
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/logo.png
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/logo_light_bg.png
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/AppName.json
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
Labels: tested, easy to review

#715 CARDS-1264: Add a Pagination Test questionnaire to the test runmode
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/PaginationTest.xml
Labels: tested

#718 CARDS-699 and CARDS-1302: Add support for hidden and formatted computed questions
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
Labels: tested, Merge me!, easy to review

#720 CARDS-1304: Switch from using install runModes to normal runModes
  distribution/src/main/provisioning/01-boot.txt
Labels: question, easy to review

#719 CARDS-1303 - Add the ability to display informative text in questionnaires
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/CreationMenu.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Information.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: tested, urgent, Merge me!

#723 CARDS-1164: Smaller form headers on smaller screens
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: question, tested, urgent

#726 CARDS-1307: As a user, I can export the contents of a form in text format
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, urgent, Merge me!, easy to review

#730 CARDS-1320: Each form should keep track of its related subjects
  modules/data-entry/pom.xml
  modules/data-entry/src/main/java/io/uhndata/cards/internal/FormRelatedSubjectsEditor.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/FormRelatedSubjectsEditorProvider.java
  modules/data-entry/src/main/resources/SLING-INF/content/oak%3Aindex/formRelatedSubjects.json
  modules/data-entry/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: tested, Merge me!

#727 CARDS-1164 (Smaller form headers on smaller screens) amendment: Moved the breadcrumb action to the RIGHT of the sticky header
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
Labels: tested, Merge me!

#734 CARDS-1278: The start_cards script should display the port where the app started (or failed to start)
  start_cards.sh
Labels: tested, Merge me!, easy to review

#733 CARDS-1187: Modify tooltip "Save and close" to "Save and view" as the button does not close the form
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, Merge me!, easy to review

#732 CARDS-1302: Add support for computed fields displayed as formatted text - BUGFIX
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
Labels: tested, easy to review

#731 CARDS-1319: The generate_compose_yaml.py script should configure a bind-mount from the cardsinitial container to the local SLING directory
  compose-cluster/.gitignore
  compose-cluster/cleanup.sh
  compose-cluster/generate_compose_yaml.py
Labels: easy to review

#722 CARDS-1263: As an admin, I can access a preview of what a questionnaire looks and functions like without creating a new form ("view mode" for questionnaires)
  modules/commons/src/main/frontend/src/components/dragAndDrop.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NewQuestionnaireDialog.jsx
Labels: tested

#738 CARDS-1325: Selecting/dragging file(s) to a question inside the section sometimes does not work
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
Labels: tested, Merge me!, easy to review

#736 CARDS-1330: Error displayed when deleting a pedigree if the pedigree question is inside a section
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
Labels: tested, Merge me!, easy to review

#737 CARDS-1332: jcr:lastModified for Questionnaires does not get updated sometimes
  modules/versioning/src/main/java/io/uhndata/cards/versioning/LastModifiedEditor.java
Labels: tested, Merge me!, easy to review

#739 CARDS-1306/CARDS-1353: Add support for sections that stick to the bottom (footer section) of the page when scrolling
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/StickySectionTest.xml
Labels: tested

#725 CARDS-1225: Write a script for upgrading the base Ubuntu image used by the Nginx proxy Docker Compose container
  Utilities/ContainerManagement/upgrade_nginx_ubuntu_proxy.sh
Labels: tested, Merge me!

#740 CARDS-1306 / CARDS-1352 Add support for sections that stick to the top (header section) when scrolling
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/homepage/src/main/frontend/src/themePage/indexStyle.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/StickySectionTest.xml
Labels: tested

#744 CARDS-1263 amendment : Added "Close" button for questionnaire preview, which directs the user to the Questionnaires page
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
Labels: tested, easy to review

#749 CARDS-1164: Smaller form headers on smaller screens - action position
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
Labels: easy to review

#748 CARDS-1355: Review PROMs questionnaires: footer section layout issue
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PHQ9.xml
Labels: easy to review

#758 CARDS-1230: For Number Questions with predefined options, the selectedvalue is displayed instead of the label in view mode and in the subject chart
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/AnswerOptionsLabelProcessor.java
Labels: Test me!, easy to review
