Repository data-team-uhn/cards, pull requests merged in 2021-07, with the labels that each got.

#632 LFS-328: As a user answering a vocabulary question, I can select an option from the Vocabulary browser
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBranch.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyTree.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/util.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDetails.jsx
Labels: tested

#671 LFS-1210: Filters for vocabulary questions are cleared too often
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: tested

#683 LFS-1231: Computed field display may truncate longer values
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
Labels: easy to review, tested

#679 LFS-961: Cannot specify custom ethnicities
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
Labels: tested, urgent

#687 [misc] Fixed random React version mismatch
  modules/vocabularies/src/main/frontend/package.json
Labels: Merge me!, tested

#685 LFS-1234: Inform the user when some of the suggestions for vocabulary question cannot be loaded because one of the vocabularies linked to that questions is not yet installed
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: Merge me!, tested

#686 LFS-1237: After selecting the maximum number of vocabulary answers, the search input seems still active
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: easy to review, tested, urgent

#688 LFS-1239: start_cards.sh should detect failure to start the java process and terminate
  start_cards.sh
Labels: tested

#684 LFS-1232: As a questionnaire designer, I can use text formatting in question and section descriptions
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownTextField.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Properties.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBranch.jsx
  modules/principals/src/main/frontend/src/Userboard/Users/changeuserpassworddialogue.jsx
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyAction.jsx
Labels: tested

#696 CARDS-1249: Show question descriptions to forms in view mode
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
Labels: easy to review, tested

#695 CARDS-1246: Show questionnaire description in each form
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: easy to review, tested

#694 CARDS-1250: Remove questionnaire description from the patient chart
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: easy to review, tested

#693 CARDS-1248: Remove the Description column from the Administration/Questionnaires table
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
Labels: easy to review, tested

#697 CARDS-1251: When many Patient information forms are stored, UI allows for multiple Patient Information forms to be created for a single patient
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Test me!, urgent

#689 LFS-1243 & LFS-1244 - Errors when deleting subjects on the subject chart
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent

#691 CARDS-1247: Move the codebase to data-team-uhn
  modules/commons/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/package.json
  modules/demo-banner/src/main/frontend/package.json
  modules/homepage/src/main/frontend/package.json
  modules/login/src/main/frontend/package.json
  modules/pedigree/src/main/frontend/package.json
  modules/principals/src/main/frontend/package.json
  modules/ui-extension/src/main/frontend/package.json
  modules/variants/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/package.json
  pom.xml
Labels: tested, urgent

#677 LFS-360: Clarify the source of filter variables
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested, urgent

#673 [Misc] Re-enable NCR Notes for vocab questions
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: easy to review, tested, urgent

#699 LFS-1253: After clicking close and save, Forms are sometimes incorrectly marked as being edited by another user
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: easy to review, tested

#698 CARDS-1255: Warning when opening Patient Information: Unknown event handler property `onAddSuggestion`.
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
Labels: easy to review, tested

#690 LFS-1238: Buggy behavior for vocabulary questions with list+input display and maxAnswers=1
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: Merge me!, easy to review, tested

#700 CARDS-1258: Searching for "caucasian" or "white" in Race/Ethnicities should suggest "European"
  modules/vocabularies/src/main/resources/SLING-INF/content/oak%3Aindex/vocabularyTerms.json
Labels: Merge me!, easy to review, tested

#692 LFS-1233: As a questionnaire designer, I can specify descriptions for predefined answer options
  modules/commons/pom.xml
  modules/commons/src/main/frontend/src/components/ComposedIcon.jsx
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownText.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownTextField.jsx
Labels: Merge me!, tested

#702 CARDS-1272: Wrong question listed in filters for the Radio form
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
Labels: Test me!, easy to review

#706 CARDS-1257: Add description of the "Caucasian" predefined option of the "Race/Ethnicity reported" question in the Patient Information questionnaire
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
Labels: Merge me!, tested

#704 CARDS-1276: Switching filters causes the input box to be treated as empty.
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
Labels: easy to review, tested

#708 CARDS-1281: Improve the look of the Patient Information's Co-morbidities field
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
Labels: Merge me!, easy to review, tested

#709 CARDS-1279: In questions with maxAnswers != 1, user-added answers are no longer displayed on the same line with their delete (x) button
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Merge me!, easy to review, tested

#678 LFS-1223: Create a utility program for backing up and restoring the tag of a running Docker image
  Utilities/ContainerManagement/backup_image_tag.sh
  Utilities/ContainerManagement/restore_image_tag.sh
Labels: Merge me!, easy to review

#710 CARDS-1295: As an admin I can design paginated questionnaires in the questionnaire wizard
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Properties.json
Labels: Merge me!, easy to review, tested

#705 CARDS-1236: Test runMode should provide a mock NCR service which will allow the NCRNote component to be tested with hard-coded text annotations
  test-resources/pom.xml
  test-resources/src/main/java/io/uhndata/cards/test/MockNCREndpoint.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ConceptRecognitionTest.xml
Labels: Merge me!, tested

#703 CARDS-1262: The suggestions dropdown for Vocabulary Questions should display additional fields as needed when the suggestion label doesn't match the user input
  modules/data-entry/src/main/frontend/src/vocabQuery/QueryMatchingUtils.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: Merge me!, tested

#711 CARDS-1297: Disable pagination when in view mode of a paginated questionnaire
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: Merge me!, easy to review, tested

#713 CARDS-1283: Export forms as text
  modules/data-entry/pom.xml
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/FormToTextAdapterFactory.java
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/Form/txt.GET.html
  modules/utils/src/main/java/io/uhndata/cards/scripting/ContentTypeSetter.java
Labels: question, tested, urgent
