Repository data-team-uhn/cards, pull requests merged in 2021-11, with the labels that each got.

#806 CARDS-1430: Regression: Vocabulary term displayed value is its id instead of the label
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/AnswerOptionsLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/SimpleAnswerLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/VocabularyLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/VocabularyOptionsLabelProcessor.java
Labels: tested, Merge me!

#818 [misc] Move dependency versions in a single place, the root pom
  aggregated-frontend/pom.xml
  cardiac-rehab-resources/backend/pom.xml
  modules/commons/pom.xml
  modules/data-entry/pom.xml
  modules/examples/pom.xml
  modules/form-completion-status/pom.xml
  modules/homepage/pom.xml
  modules/pedigree/pom.xml
  modules/permissions-ownership/pom.xml
  modules/permissions/pom.xml
  modules/principals/pom.xml
  modules/statistics/pom.xml
  modules/subjects/pom.xml
  modules/utils/pom.xml
  modules/versioning/pom.xml
  modules/vocabularies/pom.xml
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/VocabularyTermInfoServlet.java
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/VocabularyTermSearchServlet.java
  pom.xml
  test-resources/pom.xml
Labels: Merge me!

#819 CARDS-1520: Update Visit Numbers for Cardiac Rehab Questionnaires
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
Labels: tested, Merge me!, easy to review
