Repository data-team-uhn/cards, pull requests merged in 2021-09, with the labels that each got.

#761 CARDS-1373: Questions with datatype `long`, display mode `list`, and max answers != 1 duplicate their answers on re-edit; CARDS-1229 Number questions with predefined options lose their value on reedit
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, urgent, Merge me!

#766 CARDS-1372: Double questions are not supported in the questionnaire editor
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: tested, Merge me!, easy to review

#765 CARDS-1377: Remove comparison filters for vocabulary questions
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/VocabularyFilter.jsx
Labels: tested, Merge me!, easy to review

#760 CARDS-1110: Unsaved data lost when using the browser's back feature
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, Merge me!, easy to review

#769 CARDS-1384: Remove `is empty` and `is not empty` filters for subject and questionnaire
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/QuestionnaireFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/SubjectFilter.jsx
Labels: tested, Merge me!

#768 Improvement: only list the highest affected node, not all the descendants, when forms/sections/answers will be affected by a deletion
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
Labels: tested, Merge me!

#767 CARDS-1385: Too many questionnaires reported when deleting Patient subject type
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
Labels: tested, Merge me!

#754 CARDS-1324: Unable to delete questions from questionnaire designer in some situations
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/DeleteDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/ConditionalSectionUtils.java
Labels: tested, Merge me!

#770 CARDS-1373 & CARDS-1229 regression fix: BooleanQuestion options no longer appear selected.
  modules/data-entry/src/main/frontend/src/questionnaire/BooleanQuestion.jsx
Labels: tested, easy to review

#771 CARDS-1350: Adjust the PHQ and GAD forms to use Number questions instead of Text
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PHQ9.xml
Labels: tested, Merge me!

#764 CARDS-658: Create tools for creating and using UI extension points
  Utilities/Development/ExtensionPointResources/ExtensionPointUserTemplate.jsx
  Utilities/Development/ExtensionPointResources/extension_boilerplate.jsx
  Utilities/Development/ExtensionPointResources/package.json
  Utilities/Development/ExtensionPointResources/pom.xml.head
  Utilities/Development/ExtensionPointResources/pom.xml.tail
  Utilities/Development/ExtensionPointResources/webpack.config.js.head
  Utilities/Development/ExtensionPointResources/webpack.config.js.tail
  Utilities/Development/build_on_extension_point.py
  Utilities/Development/create_extension_point.py
  Utilities/Development/extension_points.md
  Utilities/Development/list_extension_points.py
  pom.xml
Labels: tested

#741 CARDS-247: As a user, I can perform advanced searches across all data
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/FilterComparators.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/TextFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/FormRelatedSubjectsEditor.java
Labels: question, tested, urgent

#772 CARDS-1110: Unsaved data lost when using the browser's back feature
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, Merge me!

#773 CARDS-1382: Option None does not work properly in list+input questions
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, Merge me!, easy to review

#774 CARDS-1390: Cannot remove user-entered answers from Number questions of type long with list+input display
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, Merge me!, easy to review

#775 CARDS-1383: As a clinician, I can record multiple numerical answers for a question
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, easy to review

#776 CARDS-1394: The questionnaire wizard suggests invalid default values for the na/noneOfTheAbove options in long/double/decimal questions with list or list+input display
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: question, tested, easy to review

#756 CARDS-1321: As a questionnaire designer, I can specify default values for questions with list or list+input display mode
  modules/commons/src/main/frontend/src/components/ComposedIcon.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
Labels: tested

#778 CARDS-1383: As a clinician, I can record multiple numerical answers for a question - Answer instructions bug fix
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, easy to review

#777 CARDS-1389: The backend code for handling filtering by DateAnswers should use the timezone offset for the given date and not the current date
  modules/data-entry/src/main/java/io/uhndata/cards/DateUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested, easy to review
