Repository data-team-uhn/cards, pull requests merged in 2021-03, with the labels that each got.

#505 LFS-959: Attempting to edit a pedigree question in the questionnaire wizard results in a white screen and console errors
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ObjectInput.jsx
Labels: Merge me!, tested

#501 LFS-939: Add the ability to specify "compact" display for questions with predefined options - all options on one line
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: Merge me!, tested

#506 LFS-960: Pedigree questions cannot be specified as mandatory
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: Merge me!, tested

#507 LFS-965: Cardiac rehab forms - presentation improvements
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/ActiGraph data.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Cardiovascular Parameters.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Daily Actigraph Diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Medication Change.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical Lab Results.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical tests.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
  cardiac-rehab-resources/clinical-data/util/import.py
Labels: tested

#491 LFS-918: An API endpoint should be available that when called as admin will cause saved data to be pushed to S3
  cardiac-rehab-resources/backend/pom.xml
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportEndpoint.java
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportTask.java
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/NightlyExport.java
Labels: urgent

#341 LFS-693: Boolean fields are not supported when filtering forms
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/BooleanFilter.jsx
Labels: bug, on hold

#514 LFS-978: Date fields appear as editable when form is in the view mode
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
Labels: tested

#517 LFS-985: Only the last instance of a repeatable section is present in the .bare JSON serialization
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/BareFormProcessor.java
Labels: tested

#523 LFS-993: Make 6MWD questions a conditional section
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Cardiovascular Parameters.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Daily Actigraph Diary.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
  cardiac-rehab-resources/clinical-data/util/import.py
Labels: tested

#525 LFS-981: Enforce 6-20 values on 6MWT form's BORG RPE pre and post test fields
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: tested

#527 Cards4CaRe questionnaire fixes
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/External file.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Surveys.xml
Labels: tested, urgent

#535 LFS-911: Refactor lfs:Subject and lfs:SubjectType nodes to use a tree structure instead of parent references
  cardiac-rehab-resources/clinical-data/pom.xml
Labels: tested

#531 LFS-512: Special characters break the vocabulary search
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
Labels: tested

#536 LFS-933: Create a utility program for setting the Sling admin password
  Utilities/Administration/set_admin_password.py
Labels: tested

#530 LFS-1015: Cardiac Rehab / Graded Walk Test / Time performed has wrong unit of measurement
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
Labels: tested

#534 LFS-1017: In .bare.json, only sections with the repeatable flag ON should be wrapped in an array
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/BareFormProcessor.java
Labels: tested

#524 LFS-983: Vocabularies administration page crashes when the user is logged out
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/owlInstaller.jsx
  modules/vocabularies/src/main/frontend/src/search.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyAction.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyEntry.jsx
Labels: Merge me!, tested

#516 LFS-975: The control for changing the number of rows in the subject selector dialog makes most of the dialog unfunctional
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Merge me!, tested

#519 LFS-664: After editing a question or section, the page should not be scrolled back to the top
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NewQuestionnaireDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
Labels: Merge me!, tested

#520 LFS-963: Editing Demographics/Ethnicity discards the vocabulary
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
Labels: tested

#545 LFS-938: Move the BioPortalApiKey serverside code into a separate API component
  modules/vocabularies/src/main/frontend/src/vocabularyEntry.jsx
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/BioPortalApiKeyManager.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/VocabularyBioPortalApiKeyServlet.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/BioOntologyIndexer.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/BioOntologyRepositoryHandler.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/DefaultBioPortalApiKeyManager.java
Labels: bug

#539 LFS-608: Release Date field is incorrect for newly installed vocabularies
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyEntry.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyTable.jsx
Labels: Merge me!, tested

#538 [misc] Fixed show locally installed vocabularies if no bioportal key
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
Labels: Merge me!, tested

#533 LFS-932: Create a utility program for installing vocabularies into a running CARDS instance
  Utilities/Administration/install_vocabulary.py
Labels: tested

#548 LFS-1029: The vocabularies administration page lists invalid BioPortal vocabularies
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyLinks.json
Labels: tested

#549 LFS-838: LDAP users should not have a "Change password" user menu option
  modules/homepage/src/main/frontend/src/themePage/Navbars/AdminNavbarLinks.jsx
Labels: Merge me!, tested

#559 LFS-1040: The .bare JSON doesn't simplify the subject if it does not have a fullIdentifier set
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/BareFormProcessor.java
Labels: urgent

#557 LFS-1038: Pushed files have wrong date in the filename
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportTask.java
Labels: tested, urgent

#561 LFS-1043: MultipleChoice questions single valued answers exported as string or array of one string
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/select.jsx
Labels: urgent

#560 LFS-1041, LFS-1042: As a user entering answers to a multi-valued question, I am warned that using "," or ";" to separate values in the input does not automatically generate separate answer entries
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical.xml
  modules/commons/src/main/frontend/src/components/UserInputAssistant.jsx
  modules/commons/src/main/frontend/src/components/style.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: urgent

#459 LFS-680 + LFS-681: When clicking (+) on a subject child chart to add a form, do not offer irrelevant subjects and questionnaires
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectAncestryEditor.java
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectProgenyEditor.java
  modules/variants/src/main/resources/SLING-INF/content/Questionnaires/SomaticVariants.xml
Labels: Merge me!, tested

#566 LFS-911 bugfix: Refactor lfs:Subject and lfs:SubjectType nodes to use a tree structure instead of parent references.
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DeleteServlet.java
Labels: Merge me!, tested

#555 LFS-1035: Wrong labels displayed in view mode for vocabulary question with custom labels
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/labels/AnswerOptionsLabelProcessor.java
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/labels/VocabularyLabelProcessor.java
Labels: Merge me!, tested

#563 LFS-1048: Issues creating a functional question of type vocabulary with only one source vocabulary using the questionnaire wizard
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
Labels: Merge me!, tested

#556 LFS-663/LFS-973: The dialog for editing questions should only display question properties and options that are relevant for the selected data type
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditorInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NumberInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ObjectInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: Merge me!, tested

#508 LFS-921: As an admin designing a questionnaire, I can specify both value and label for answer options
  modules/commons/src/main/frontend/src/escape.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
Labels: Merge me!, tested

#551 LFS-663/LFS-1033: The question edit dialog should only scroll the list of properties, leaving the dialog title and actions always visible
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
Labels: Merge me!, tested

#550 LFS-998: Refactor Variant upload and Somatic Variants form to use a FileResourceQuestion
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SomaticVariantsQuestion.jsx
  modules/data-entry/src/main/frontend/webpack.config.js
  modules/variants/pom.xml
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
  modules/variants/src/main/resources/SLING-INF/content/Questionnaires/SomaticVariants.xml
  modules/variants/src/main/resources/SLING-INF/nodetypes/variants.cnd
Labels: tested

#571 LFS-877: When clicking (+) on a subject chart, don't allow the creation of new subjects that are not descendants of the current subject
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: bug

#572 LFS-1051: Download links for file resources are broken in the subject chart for File Resource questions with maxAnswers = 1
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: Merge me!, tested

#547 LFS-935 & LFS-936: Publish a manifest file of available NeuralCR / BasicCR text analysis models and provide a downloader utility
  Utilities/NCR-Downloader/download_model.py
  Utilities/NCR-Downloader/model_repo.json
Labels: tested

#573 LFS-877: When clicking (+) on a subject chart, don't allow the creation of new subjects that are not descendants of the current subject
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#562 LFS-995: maxPerSubject, maxAnswers sometimes stored and retrieved as string instead of long
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NumberInput.jsx
Labels: tested

#580 [misc] Removed unused import
  modules/homepage/src/main/frontend/src/themePage/EntityIdentifier.jsx
Labels: Merge me!

#495 LFS-924: As an admin, I can manage subject types
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectType.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectTypes.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectDirectory.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectType.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTypeDialog.jsx
  modules/data-entry/src/main/frontend/webpack.config.js
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/SubjectTypeInstanceCountProcessor.java
  modules/homepage/src/main/frontend/src/themePage/EntityIdentifier.jsx
Labels: Merge me!, tested

#581 LFS-1063: Weird characters briefly displayed when opening the questionnaire editor for questionnaires with spaces in their name
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: Merge me!, tested

#577 LFS-1057: Avoid scrolling when going to edit mode form search result
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: Merge me!, easy to review, tested

#582 [misc] Fixed incorrect condition
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
Labels: easy to review, question
