Repository data-team-uhn/cards, pull requests merged in 2021-06, with the labels that each got.

#627 LFS-1085: Refactor query.jsx as a functional component; LFS-1151: Show no results when typing space in the vocabulary field
  modules/commons/src/main/frontend/src/components/ResponsiveDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/VocabularyFilter.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/InfoBox.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBranch.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyTree.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
Labels: tested

#654 LFS-1150: Unable to uninstall vocabularies; LFS-1180: Add vocabulary name to the uninstall warning dialog
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DeleteServlet.java
  modules/vocabularies/src/main/frontend/src/vocabularyAction.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyActions.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDetails.jsx
Labels: easy to review, tested

#658 LFS-1183: Ignore term GEO:000000374 from HANCESTRO vocabulary
  modules/vocabularies-ignore/src/main/resources/SLING-INF/content/HANCESTRO/GEO000000374.json
Labels: easy to review, tested

#626 LFS-1115: As an admin, I can look inside installed vocabularies
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBranch.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyTree.jsx
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DeleteServlet.java
  modules/vocabularies/src/main/frontend/src/vocabularyActions.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDetails.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/BioOntologyIndexer.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/FileUploadIndexer.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/OntologyIndexerUtils.java
  modules/vocabularies/src/main/resources/SLING-INF/nodetypes/vocabularies.cnd
Labels: tested

#659 LFS-143: Releases should have production-transpiled resources
  modules/aggregated-frontend/src/main/frontend/webpack.config-template.js
  pom.xml
Labels: bug

#661 LFS-1160: Deleting the variants file after using the variants uploader triggers an error
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, easy to review, tested

#660 LFS-1192: When starting CARDS on a non-default port with the test runMode enabled, the non-default port setting is not passed to the vocabulary installation script
  start_cards.sh
Labels: Merge me!, easy to review, tested

#657 LFS-1170: Create a GitHub Action Workflow that will, upon each release of CARDS, check if the release is the latest version and if so, mark a given CARDS deployment as ready for upgrade
  .github/workflows/mark_demo_upgrade.yml
  Utilities/Administration/mark_for_upgrade.py
  Utilities/RepositoryManagement/get_latest_tagged_version.py
Labels: Merge me!, tested

#662 LFS-1174: Vocabulary question filters cannot be cleared by emptying the input
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/VocabularyFilter.jsx
Labels: Merge me!, easy to review, tested

#664 LFS-1198: "is empty" and "is not empty" comparators do not work when multiple Questionnaires have identically named answer nodes
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java
Labels: Merge me!, tested

#669 LFS-1197: Empty "Is a type of" displayed for terms from certain vocabularies
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
Labels: easy to review

#666 Misc lfs fixes
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Chemotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Radiotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Tumors.xml
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DataImportServlet.java
Labels: Merge me!, tested, urgent

#665 LFS-1208: Pressing the down arrow key while in a vocabulary input when the suggestion list is not visible results in JS console error
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: Test me!, easy to review

#670 LFS-1200: Cards4Care Enrollment Status Update - Add resumed and paused
  cardiac-rehab-resources/clinical-data/pom.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/Questionnaire/fixstatus.html.esp
Labels: tested

#663 LFS-1194: As a user, I can filter forms by "Created date" in the dashboard and on the Forms page
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java
Labels: tested

#672 LFS-1216: Add support for selecting vocabulary suggestions using the up arrow key
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
Labels: easy to review, tested

#667 LFS-1206: Questionnaire/Subject selector does not reset internal state when closed before completion
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: bug, easy to review

#675 LFS-1206 Regression Fix
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
Labels: tested
