Repository data-team-uhn/cards, pull requests merged in 2021-05, with the labels that each got.

#630 LFS-535: Solve concurrency issues when uploading somatic variant files as CSVs in bulk
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested

#629 LFS-1136: Improve the layout of the vocabulary browser
  modules/data-entry/src/main/frontend/src/vocabQuery/browse.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseListChild.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
Labels: Merge me!, tested

#636 LFS-1149: New question: cards4care / Graded Walk Test / Was Polar data captured
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
Labels: Merge me!, easy to review, tested, urgent

#637 LFS-1146: The test runmode should provide a sample patient
  test-resources/pom.xml
  test-resources/src/main/resources/SLING-INF/content/Subjects/SamplePatient.xml
Labels: Merge me!, easy to review, tested

#628 LFS-1074: CARDS should not start if it cannot bind to a port
  README.md
  Utilities/HostConfig/argparse_bash.py
  Utilities/HostConfig/check_tcp_available.py
  Utilities/HostConfig/check_tcp_listen.py
  start_cards.sh
Labels: tested

#639 LFS-1156: Importing Patient information forms with a "Surveilled since" answer will break the form
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
Labels: Merge me!, easy to review, tested

#638 LFS-1155: Wrong resource type recorded for date, time, and pedigree answers
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: Merge me!, easy to review, tested

#574 LFS-1055: Somatic Variants uploader mangles non-UTF characters
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested

#642 LFS-1136: Improve the layout of the vocabulary browser - Bugfixes
  modules/data-entry/src/main/frontend/src/vocabQuery/browseListChild.jsx
Labels: Merge me!, easy to review, tested

#641 LFS-1158: The test runmode should provide a non-admin user
  distribution/src/main/provisioning/63-test-forms.txt
Labels: Merge me!, easy to review, tested

#631 LFS-1091: Make sure only relevant details are shown in the timeline
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
Labels: Merge me!, tested

#643 LFS-1161: Show 10 questionnaires/subjects in the questionnaire/subject selection dialogs by default
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: easy to review, tested

#640 LFS-1147: The test runmode should have HANCESTRO already installed
  Utilities/HostConfig/java_property_parser.py
  start_cards.sh
Labels: Merge me!, tested

#644 [misc] Polish the look of the dialog for changing the BioPortal API key introduced as part of LFS-1113
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
Labels: easy to review, tested

#646 LFS-1167: The dialogs for selecting a questionnaire or subject when creating a new form should be responsive
  modules/commons/src/main/frontend/src/components/ResponsiveDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Merge me!, tested

#648 LFS-1165: Display questionnaire description under the name in the selection dialog
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: easy to review, tested

#649 LFS-1168: Clean up the look of questionnaire and subject selection dialogs
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Merge me!, easy to review, tested

#645 LFS-1074: CARDS should not start if it cannot bind to a port
  Utilities/HostConfig/check_tcp_available.py
Labels: tested

#653 Update README.md
  README.md
Labels: Merge me!, easy to review, urgent

#651 Pedigree editor fixes: LFS-605, LFS-1172, LFS-1173
  modules/pedigree/src/main/frontend/src/pedigree/pedigree.js
  modules/pedigree/src/main/frontend/src/pedigree/shims/suggestShim.js
  modules/pedigree/src/main/frontend/src/pedigree/view/exportSelector.js
  modules/pedigree/src/main/frontend/src/pedigree/view/importSelector.js
  modules/pedigree/src/main/frontend/src/pedigree/view/nodeMenu.js
  modules/pedigree/src/main/frontend/src/pedigree/view/okCancelDialogue.js
Labels: easy to review, tested, urgent

#656 LFS-1176: Pedigree editor: Relationship handles don't work
  modules/pedigree/src/main/frontend/src/pedigree/view/partnershipHoverbox.js
Labels: Merge me!, easy to review, tested
