Repository data-team-uhn/cards, pull requests merged in 2021-12, with the labels that each got.

#821 CARDS-1524: Question text consisting of only whitespace gets discarded in the questionnaire editor
  modules/data-entry/src/main/frontend/src/questionnaireEditor/TextInput.jsx
Labels: tested, Merge me!, easy to review

#784 CARDS-1006: When in a view mode of an invalid/incomplete form, show all the offending fields marked with proper message in red fonts
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested, Merge me!

#823 CARDS-1527: Subsections are not rendered in a view mode if their parent Section does not have direct Question descendants with existing answers
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested, Merge me!, easy to review

#824 CARDS-1518: Import Cardiac Rehab phase 2 questionnaire changes
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Changes in Health Survey.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/End of Study Physical Assessment.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Recent Activities Survey.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/WHODAS.xml
  cardiac-rehab-resources/clinical-data/util/import.py
Labels: tested, urgent, Merge me!

#826 CARDS-1530: Modify Participant Status Form
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  cardiac-rehab-resources/clinical-data/util/import.py
Labels: tested, urgent, Merge me!

#829 [misc] Fixed building distribution for windows
  distribution/pom.xml
Labels: tested, Merge me!, easy to review

#830 CARDS-1529: A --dev_docker_image flag should be available for generate_compose_yaml.py
  compose-cluster/generate_compose_yaml.py
Labels: urgent, Merge me!, easy to review, current sprint

#834 CARDS-1518: Cardiac Rehab phase 2 import fixes
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Changes in Health Survey.xml
Labels: tested, urgent

#836 CARDS-1530 fixes: Modify participant status form
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested

#817 CARDS-1463: Computed questions should have a data type
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/ExpressionUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/QuestionnaireUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ComputedAnswersEditor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ExpressionUtilsImpl.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/QuestionnaireUtilsImpl.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/EQ5D.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PHQ9.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/SC.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ServersideComputedTest.xml
Labels: tested, current sprint

#838 CARDS-1530 fixes 2: Modify Participant status form for phase 2 cardiac rehab
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested

#837 CARDS-692: Better handling of sections/questions with the same variable name
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
Labels: incomplete
