Repository data-team-uhn/cards, pull requests merged in 2021-02, with the labels that each got.

#465 LFS-867: When opening a patient chart, there are 2 request for for each sub-subject
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: Merge me!, tested

#456 LFS-581: Livetable pagination should go back to page 1 when changing the search criteria
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
Labels: Merge me!, tested

#472 LFS-885: Baseline Medication / Beta blockers / Patient-reported not taking should not be mandatory
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
Labels: tested

#444 LFS-816: Handle re-login globally (continued)
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/login/src/main/frontend/src/login/loginDialogue.js
Labels: Merge me!, tested

#474 LFS-889: bl_med_types_other section in Baseline Medications has incorrect conditional
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
Labels: tested

#473 LFS-886: Polish the UI of the Pedigree question
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested

#468 LFS-876: Installed vocabularies are not shown when the Vocabulary page gets refreshed
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyLinks.json
Labels: Merge me!, tested

#478 LFS-894: Customize the theme colors
  modules/commons/src/main/frontend/src/themePalette.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/login/src/main/frontend/src/login/loginMainComponent.js
  modules/login/src/main/frontend/src/styling/styles.js
Labels: tested

#475 LFS-888: Display "<Appname> by DATA" at the bottom of the login form
  modules/login/src/main/frontend/src/login/loginMainComponent.js
  modules/login/src/main/frontend/src/styling/styles.js
Labels: tested

#471 LFS-854: Transfer active tab from Dashboard to Forms or Subjects page when clicking expand
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
Labels: tested

#467 LFS-872: Variant upload fails silently with hyphen in filename when patient ID exists
  modules/commons/src/main/frontend/src/escape.jsx
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: tested

#476 LFS-890: Blank screen when trying to create a patient with the identifier O'Malley
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#481 LFS-900: Incorrect year of birth in Cardiac Rehab's Participant status form
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/labels/DateLabelProcessor.java
Labels: tested

#461 LFS-712: Source vocabulary fields in the questionnaire editor should be arrays, not strings
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Properties.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: Merge me!, tested

#486 LFS-878: Make nolfs the default runmode, to be active unless lfs runmode is specified
  distribution/src/main/provisioning/01-boot.txt
Labels: Merge me!, tested

#484 LFS-916: Hide the global search bar in all admin screens
  modules/homepage/src/main/frontend/src/themePage/Navbars/AdminNavbarLinks.jsx
Labels: Merge me!, tested

#479 LFS-899: Cardiac Rehab nightly exports contain unobfuscated dates in displayedValue
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/NightlyExportTask.java
Labels: Merge me!, tested

#488 [misc] Polished the demo banner style
  modules/demo-banner/src/main/frontend/src/demoBanner.jsx
Labels: tested

#490 LFS-896: Remove List from Admin's options Users List and Groups List
  modules/principals/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/Grouplist.json
  modules/principals/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/Userlist.json
  modules/principals/src/main/resources/SLING-INF/content/Extensions/Views/Grouplist.json
  modules/principals/src/main/resources/SLING-INF/content/Extensions/Views/Userlist.json
Labels: Merge me!, tested

#483 Cardiac rehab fixes
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical Lab Results.xml
Labels: bug, urgent

#485 LFS-895: Move + button to the bottom of the Admin's Users List and Group List pages
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NewQuestionnaireDialog.jsx
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebarStyle.jsx
  modules/principals/src/main/frontend/src/Userboard/Groups/groupsmanager.jsx
  modules/principals/src/main/frontend/src/Userboard/Users/usersmanager.jsx
  modules/principals/src/main/frontend/src/Userboard/newPrincipalButton.jsx
Labels: Merge me!, tested

#429 LFS-632: As an admin, I can update the Bioportal API key from the Admin screen
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/owlInstaller.jsx
  modules/vocabularies/src/main/frontend/src/phaseCodes.json
  modules/vocabularies/src/main/frontend/src/search.jsx
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyEntry.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyTable.jsx
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/VocabularyBioPortalApiKeyServlet.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/BioOntologyRepositoryHandler.java
  package-lock.json
Labels: Merge me!, tested

#493 [misc] Fixed UI regression introduced by PR #485
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent

#453 LFS-856: Simplify CARDS runmodes
  distribution/src/main/provisioning/01-boot.txt
  distribution/src/main/provisioning/61-kids-resources.txt
  kids-resources/clinical-data/pom.xml
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/lfs/resources/background.jpg
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/lfs/resources/logo.png
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/lfs/resources/logo_light_bg.png
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/0-5NDVariables.xml
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6-21NDVariables.xml
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/QIVariables.xml
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/conf/AppName.json
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/conf/ThemeColor.json
  kids-resources/clinical-data/util/heartCentreData.py
  kids-resources/pom.xml
  pom.xml
Labels: Merge me!, tested

#497 LFS-943: Installing ORDO fails
  README.md
  distribution/docker_entry.sh
Labels: Merge me!, tested

#496 LFS-559: Incorrect tumor region name and in same case creation of single tumor region when uploading somatic variant files as CSVs that have more then two _ in the file name
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested

#498 [Misc] Freeze the versions of our dependencies, to prevent possible improper-backwards-compatibility breakages.
  modules/commons/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/package.json
  modules/demo-banner/src/main/frontend/package.json
  modules/homepage/src/main/frontend/package.json
  modules/login/src/main/frontend/package.json
  modules/pedigree/src/main/frontend/package.json
  modules/principals/src/main/frontend/package.json
  modules/ui-extension/src/main/frontend/package.json
  modules/variants/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/package.json
Labels: Merge me!, tested

#502 LFS-724 / LFS-950: Creating data with non-admin users fails
  distribution/src/main/provisioning/50-lfs.txt
  modules/permissions/src/main/java/ca/sickkids/ccm/lfs/permissions/internal/RootRestrictionFactory.java
  modules/permissions/src/main/java/ca/sickkids/ccm/lfs/permissions/internal/RootRestrictionPattern.java
Labels: tested

#428 LFS-795, LFS-366: Refactor Date questions and fix DateTime
  cardiac-rehab-resources/clinical-data/util/import.py
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionYear.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/webpack.config.js
Labels: tested

#499 LFS-928: Use the (+) button component (NewItemButton) for creating a new question or section in the Questionnaire Wizard
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/CreationMenu.jsx
Labels: tested

#503 LFS-952: Actigraph Diary Date and Entry Number
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/ActiGraph data.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Daily Actigraph Diary.xml
Labels: tested
