Repository data-team-uhn/cards, pull requests merged in 2021-04, with the labels that each got.

#576 LFS-1061 & LFS-1062: Files with URL special characters in their name can be uploaded but not downloaded or deleted
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: Merge me!, easy to review, tested

#584 LFS-1068: Quotation marks in question or section identifiers break the questionnaire serialization
  distribution/src/main/provisioning/50-sling-webconsole.txt
Labels: Merge me!, easy to review, tested

#544 LFS-1022 / LFS-1060: Remove Progeny/Ancestors and wrong parent selected when creating new tumor
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/QueryBuilder.java
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectAncestryEditor.java
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectParentEditor.java
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectParentEditorProvider.java
  modules/subjects/src/main/java/ca/sickkids/ccm/lfs/subjects/internal/SubjectProgenyEditorProvider.java
Labels: Merge me!, tested

#586 LFS-1075: Improve how file resources files are displayed on the patient chart
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: easy to review, tested

#579 LFS-1000: Radio questions don't respond well to tab / LFS-771: Unable to tab on specific fields in sections
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/select.jsx
Labels: tested

#578 LFS-1058: Single select file questions may leave stale files in the answer / LFS-1069: Single select upload function should not allow multiple files selection
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
Labels: easy to review, tested

#569 LFS-974: Add the ability so specify if an answer option has a None or None of the above behavior in the question editor
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
Labels: Merge me!, tested

#590 Various cleanup changes from #429
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/VocabularyBioPortalApiKeyServlet.java
  package-lock.json
Labels: Merge me!, tested

#592 LFS-1026: The vocabulary browser should use theme colors
  modules/data-entry/src/main/frontend/src/vocabQuery/browseListChild.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
Labels: Merge me!, easy to review, tested

#482 LFS-193: As a user, I can visualize the events recorded for a patient in a timeline
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
Labels: Merge me!, tested

#575 LFS-1044: Newly added questions are not highlighted in the questionnaire editor
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/CreationMenu.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/DeleteDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
Labels: Merge me!, tested

#588 LFS-1077: Keep input radio button and label together in compact mode
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Merge me!, tested

#593 LFS-1086: New question: cardiac_rehab/GWT/Number of laps completed
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
Labels: Merge me!, easy to review, tested

#594 LFS-1089: Remove text indentation inside text fields associated with multiselect questions
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Merge me!, easy to review, tested

#591 LFS-1053: Form actions menu & LFS-1080: As a developer, I can render a Delete button with a text label
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Merge me!, tested

#595 LFS-1037: Add the ability to reorder answer options via drag and drop
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
Labels: Merge me!, tested

#596 LFS-1093: generate_compose_yaml.py should be able to run non-interactively
  compose-cluster/generate_compose_yaml.py
Labels: Merge me!, easy to review

#597 LFS-1097: generate_compose_yaml.py should allow for the user to define the subnet of IP addresses used in the docker-compose environment
  compose-cluster/generate_compose_yaml.py
Labels: Merge me!, easy to review

#601 LFS-1099: Description of HANCESTRO terms is not shown
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
Labels: Merge me!, tested

#599 LFS-1077: Keep input radio button and label together in compact mode
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: Merge me!, easy to review, tested

#603 LFS-1079: Better theme color for cards4kids
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/lfs/resources/logo.png
  kids-resources/clinical-data/src/main/media/SLING-INF/content/libs/lfs/resources/logo_light_bg.png
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/conf/ThemeColor.json
Labels: Merge me!, easy to review, tested

#604 LFS-1107: Synonyms not displayed in the info box for HANCESTRO terms
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
Labels: Merge me!, easy to review, tested

#600 LFS-1094: The dialogs to create a new form should not close on clicking outside them
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Merge me!, easy to review, tested

#587 LFS-1069: Single select upload function should not allow multiple files selection: fixed regression in FileResourceQuestion with maxAnswers > 1
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
Labels: Merge me!, tested

#598 LFS-1072: Move the focus at the beginning of the newly created recurring section
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: Merge me!, easy to review, tested

#606 LFS-1101: Displaying information for CHEBI terms fails
  modules/vocabularies/pom.xml
Labels: tested

#589 LFS-1073: Refactor the vocabulary question to use MultipleChoice component
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/VocabularyFilter.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/select.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/selectEntry.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/selectionResults.jsx
  modules/data-entry/src/main/frontend/src/vocabSelector/selectorStyle.jsx
Labels: Test me!

#602 LFS-1067: Themed 404 not found page
  modules/commons/pom.xml
  modules/commons/src/main/frontend/src/components/404.js
  modules/commons/src/main/frontend/src/components/PageNotFound.js
  modules/commons/src/main/frontend/webpack.config.js
  modules/commons/src/main/resources/SLING-INF/content/libs/sling/servlet/errorhandler/404.html
  modules/utils/pom.xml
  modules/utils/src/main/java/ca/sickkids/ccm/lfs/scripting/ContentTypeSetter.java
  modules/utils/src/main/java/ca/sickkids/ccm/lfs/scripting/StatusCodeSetter.java
Labels: Merge me!

#610 LFS-941: "No vocabularies installed yet" displayed while the list of installed vocabularies is fetched
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
Labels: Merge me!, easy to review, tested

#605 LFS-996: Fine tune vocabulary search
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/config.json
  modules/vocabularies/src/main/frontend/src/owlInstaller.jsx
  modules/vocabularies/src/main/frontend/src/search.jsx
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyActions.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDetails.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyTable.jsx
Labels: Merge me!, tested

#607 LFS-836: LFS forms clean up
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Chemotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Demographics.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Radiotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Tumors.xml
  lfs-resources/tissue-metrix/src/main/resources/SLING-INF/content/Questionnaires/TissueMetrix.xml
Labels: tested, urgent

#609 LFS-1098: After a vocabulary is installed, all its nodes should be checked in
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/BioOntologyIndexer.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/FileUploadIndexer.java
  modules/vocabularies/src/main/java/ca/sickkids/ccm/lfs/vocabularies/internal/OntologyIndexerUtils.java
Labels: tested

#612 LFS-1123: Non-latin characters are garbled
  distribution/src/main/provisioning/10-sling-base.txt
Labels: Merge me!, tested

#616 LFS-1119: Vocabulary question with maxAnswers=1 has broken indentation
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
Labels: Merge me!, tested, urgent

#611 LFS-1087: Implement test run mode
  distribution/src/main/provisioning/63-test-forms.txt
  pom.xml
  test-resources/pom.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateFormatsTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DecimalConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DoubleConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/LongConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/RadioButtonCheckboxCompactTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/StringConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/VocabularyMultipleChoiceTest.xml
Labels: Merge me!, tested

#619 LFS-1130: Files in the compose-cluster/SSL_CONFIG directory should be ignored by both git and org.apache.rat
  compose-cluster/.gitignore
  pom.xml
Labels: easy to review, tested

#614 LFS-1114: Create a utility program for listing all required vocabularies for a CARDS deployment
  Utilities/Administration/install_required_vocabularies.sh
  Utilities/Administration/list_required_vocabularies.py
Labels: tested

#608 LFS-842: Improve UX in the Variants Upload form
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested

#621 LFS-1133: Boolean questions lose their value on reddit
  modules/data-entry/src/main/frontend/src/questionnaire/BooleanQuestion.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/VocabularyMultipleChoiceTest.xml
Labels: easy to review, tested, urgent

#620 LFS-1100: Ugly UI when dragging files over a File question
  modules/commons/src/main/frontend/src/components/dragAndDrop.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested, urgent

#623 [misc] Use subject type labels instead of hardcoded strings in Variant Upload
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: easy to review

#618 LFS-1125: Split LFS forms into semantic sections
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Chemotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Demographics.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Radiotherapy.xml
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Tumors.xml
  lfs-resources/tissue-metrix/src/main/resources/SLING-INF/content/Questionnaires/TissueMetrix.xml
Labels: tested, urgent

#622 LFS-1128: When generate_compose_yaml.py is called with the --ssl_proxy flag, add the secure flag to cookies
  compose-cluster/proxy/https_000-default.conf
Labels: easy to review

#625 LFS-1135: Patient events are no longer grayed out in the tumor timeline
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
Labels: Merge me!, tested, urgent

#624 LFS-1131: Adding or removing the tumor region identifier in the Variants uploader is buggy
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
Labels: Merge me!, tested, urgent
