Repository data-team-uhn/cards, pull requests merged in 2022-06, with the labels that each got.

#1051 [misc] PROMS-specific resources fail to load on windows
  distribution/src/main/features/core/cards.json
  proms-resources/feature/src/main/features/feature.json
Labels: tested, Merge me!

#1028 Misc: Mock Torch server - random patient generation
  Utilities/Development/com.github.dominictarr.random-name.names.json
  Utilities/Development/mock_torch.js
Labels: on hold

#1053 CARDS-1790: Concept Recognition Test Form is not highlighting potential terms
  test-resources/src/main/java/io/uhndata/cards/test/MockNCREndpoint.java
Labels: tested, Merge me!, easy to review

#1049 CARDS-1726: Create a simple placeholder html page template to be displayed when CARDS is down
  compose-cluster/cleanup.sh
  compose-cluster/generate_compose_yaml.py
  compose-cluster/proxy/Dockerfile
  compose-cluster/proxy/http_000-default.conf
  compose-cluster/proxy/http_saml_000-default.conf
  compose-cluster/proxy/https_000-default.conf
  compose-cluster/proxy/https_saml_000-default.conf
  compose-cluster/proxy/proxyerror/503.html.template
  compose-cluster/proxy/render_503_page.js
  compose-cluster/proxy/startup.sh
Labels: tested, Merge me!

#1018 CARDS-558: Replace moment.js with luxon
  Utilities/Development/ExtensionPointResources/package.json
  lfs-resources/variants/src/main/frontend/package.json
  lfs-resources/variants/src/main/frontend/src/variantFilesContainer.jsx
  modules/commons/src/main/frontend/package.json
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionYear.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/demo-banner/src/main/frontend/package.json
  modules/homepage/src/main/frontend/package.json
  modules/statistics/src/main/frontend/package.json
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
  proms-resources/frontend/src/main/frontend/package.json
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateFormatsTest.xml
Labels: dependencies, urgent, Test me!

#1043 CARDS-1784: New question type: ResourceQuestion
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/ResourceFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/resourceQuery/QueryMatchingUtils.jsx
  modules/data-entry/src/main/frontend/src/resourceQuery/ResourceQuery.jsx
  modules/data-entry/src/main/frontend/src/resourceQuery/queryStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/InfoBox.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyTree.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/browseStyle.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/queryStyle.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/AbstractResourceLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/ResourceLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/ResourceOptionsLabelProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/VocabularyOptionsLabelProcessor.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  test-resources/src/main/features/feature.json
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ResourceTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/VocabularyMultipleChoiceTest.xml
Labels: tested, urgent, large PR

#1047 CARDS-1623-1724: Add support for DICOM images through the cards:DicomAnswer question type
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dicom/dicomDataDictionary.js
  modules/data-entry/src/main/frontend/src/questionnaire/DicomQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/DicomLabelProcessor.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DicomTest.xml
Labels: tested, Merge me!

#1034 CARDS-1737: When computing the surveys that need to be filled out for a visit based on the configured frequency, look at previous visit from the same clinic rather than with the same questionnaire set
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
  proms-resources/frontend/src/main/frontend/src/proms/PromsDashboard.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
Labels: tested, urgent, Merge me!

#1062 CARDS-1797: provider.names parameter in OSGi configuration for PROMs Import is broken
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: easy to review

#1058 CARDS-1801: The dashboard widgets don't take out the full screen width on narrow screens
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsDashboard.jsx
Labels: tested, Merge me!, easy to review

#1061 CARDS-1798: Sending SMTPS emails from CARDS is broken
  modules/email-notifications/src/main/features/feature.json
Labels: easy to review

#1059 [IDEA] CARDS-1802: Dashboard colors improvements
  modules/commons/src/main/frontend/src/headerStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/QuickSearchIdentifier.jsx
Labels: tested, Merge me!, easy to review

#1057 CARDS-1791: The terms are not visible enough when using text recognition
  modules/data-entry/src/main/frontend/src/questionnaire/NCRNote.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, Merge me!, easy to review

#1056 CARDS-1708: The Patient chart shows only 10 out of 10+ child subjects
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent, Merge me!, easy to review

#1065 CARDS-1804: Number question: do not display value instructions "Please enter a value more than 0" when we have minValue=0 and no other range constraints
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, Merge me!, easy to review

#1063 [misc] Speedup the build (and reduce build size) by not building fat feature archives
  README.md
  distribution/pom.xml
  pom.xml
  start_cards.sh
Labels: tested, Merge me!

#1036 CARDS-1767 - Questionnaire wizard refactoring and polishing; CARDS-1770 - Questionnaire designer: Make questionnaire title editable
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/BooleanInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditorInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/LabeledField.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NumberInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/TextInput.jsx
  modules/statistics/src/main/frontend/src/Statistics/AdminStatistics.jsx
  proms-resources/frontend/src/main/frontend/src/proms/Clinics.jsx
Labels: tested, urgent, Merge me!, large PR

#1064 CARDS-1799: LFS mode: Timeline unresponsive
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
Labels: tested, Merge me!, easy to review

#1046 CARDS-1786: Import HERACLES questionnaires
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Cardiovascular Parameters.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Demographics.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Medication Change.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Non-Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical CPET Tests.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical Lab Results.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Physical Assessments.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Study Stream.xml
  heracles-resources/clinical-data/util/import.py
Labels: tested, Merge me!

#1070 CARDS-1809: Add Legacy Data form to Heracles import
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Legacy Data.xml
  heracles-resources/clinical-data/util/import.py
Labels: tested, urgent, easy to review

#1072 CARDS-1567: Show subject ID on parent subject selector screen
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, Merge me!, easy to review

#1071 CARDS-1808: Add the ability to search questionnaire descriptions in the new form dialog
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
Labels: tested, Merge me!, easy to review

#1052 CARDS-814: Add a `flatten` json processor for forms
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/FlattenFormProcessor.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DoubleNestedSectionTest.xml
Labels: tested, Merge me!, easy to review

#1068 CARDS-1774: Make the patient landing page text configurable
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/WelcomeMessage.xml
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
Labels: tested, Merge me!, easy to review

#1083 CARDS-1376: Froms/Subjects pages: Livetable pagination controls become inaccessible under the fixed + button
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent, Merge me!, easy to review

#1073 CARDS-1541: Move the `Incomplete` chip next to the questionnaire title
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
Labels: tested, Merge me!, easy to review

#1079 CARDS-1821: Deprecate the cards4care project
  cardiac-rehab-resources/feature/pom.xml
  cardiac-rehab-resources/feature/src/main/features/feature.json
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
  heracles-resources/backend/pom.xml
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/ExportEndpoint.java
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/ExportTask.java
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/NightlyExport.java
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/serialize/DateObfuscationProcessor.java
  heracles-resources/feature/src/main/features/feature.json
  heracles-resources/pom.xml
  pom.xml
Labels: urgent, Merge me!, Test me!

#1074 CARDS-1815: Create a script to quickly start up a Docker Compose environment for testing SMTPS email sending from CARDS
  compose-cluster/quick-environments/smtps-ci.sh
Labels: tested, Merge me!, easy to review

#1085 CARDS-1376: Froms/Subjects pages: Livetable pagination controls become inaccessible under the fixed + button - Fixed JS Console warning
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
Labels: tested, urgent, Merge me!, easy to review

#1087 CARDS-1376: Froms/Subjects pages: Livetable pagination controls become inaccessible under the fixed + button
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
Labels: tested, urgent, Merge me!, easy to review

#1076 CARDS-1817: All frontend code should check specifically for INCOMPLETE and INVALID status flags to determine form entry completion
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested, Merge me!

#1086 CARDS-1829: On subject pages, the new form dialog proposes questionnaires that match current, child, and parent subject types, instead of only current and child
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
Labels: tested, Merge me!, easy to review

#1084 CARDS-1593: As a clinician, I can't see the entries of clinics I don't belong to in the sidebar
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/PermissionsManagerService.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/PermissionsManagerServlet.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/spi/PermissionsManager.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ClinicsServlet.java
Labels: tested, urgent, Merge me!

#1075 CARDS-1814: Create a script to automatically verify the MBOX file generated by the cards/postfix-docker development email server container
  Utilities/Development/verify_mbox_file.py
Labels: tested, Merge me!, easy to review

#1078 CARDS-1774: Make the patient landing page text configurable
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownText.jsx
  proms-resources/frontend/pom.xml
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/WelcomeMessageConfiguration.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/WelcomeMessageConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/WelcomeMessageConfiguration.json
Labels: tested, Merge me!

#1088 CARDS-1401: Creating forms via API ignores the maxPerSubject setting
  modules/data-entry/src/main/features/feature.json
  modules/data-entry/src/main/java/io/uhndata/cards/internal/MaxFormsOfTypePerSubjectValidator.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/MaxFormsOfTypePerSubjectValidatorProvider.java
Labels: tested, easy to review

#1093 CARDS-1834: AnswerInstructions crashes while editing PROMs Physical Health Assessment forms
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
Labels: tested, urgent, easy to review

#1096 [misc] Update frontend-maven-plugin
  pom.xml
Labels: tested, Merge me!, easy to review

#1092 CARDS-1831 / CARDS-1832: Update Participant Status XML with new questions and options
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, Merge me!

#1029 Misc: auto_answer_surveys.py development/testing tool
  Utilities/Development/Backup_Size_Estimation.md
  Utilities/Development/Cards4Proms-SampleAnswers/AUDITC.csv
  Utilities/Development/Cards4Proms-SampleAnswers/EQ5D.csv
  Utilities/Development/Cards4Proms-SampleAnswers/GAD7.csv
  Utilities/Development/Cards4Proms-SampleAnswers/PHQ9.csv
  Utilities/Development/Cards4Proms-SampleAnswers/SC.csv
  Utilities/Development/auto_answer_surveys.py
  pom.xml
Labels: tested, Merge me!

#1040 CARDS-1759: Create a nightly data export task that will serialize all subjects that were modified that day and POST that data to a backup service webhook
  Utilities/Administration/Backup-To-JSON/README.md
  Utilities/Administration/Backup-To-JSON/backup_recorder.js
  Utilities/Administration/Backup-To-JSON/restore_json_backup.py
  distribution/src/main/features/core/webhook-backup.json
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/ComputedAnswersEditorProvider.java
  modules/pom.xml
  modules/webhook-backup/pom.xml
  modules/webhook-backup/src/main/features/feature.json
  modules/webhook-backup/src/main/java/io/uhndata/cards/webhookbackup/NightlyWebhookBackup.java
  modules/webhook-backup/src/main/java/io/uhndata/cards/webhookbackup/WebhookBackupEndpoint.java
  modules/webhook-backup/src/main/java/io/uhndata/cards/webhookbackup/WebhookBackupTask.java
Labels: tested, urgent, Merge me!, large PR

#1098 CARDS-1826: The heading size and style should be consistent across all admin screens
  modules/homepage/src/main/frontend/src/adminDashboard/AdminScreen.jsx
Labels: tested, easy to review
