Repository data-team-uhn/cards, pull requests merged in 2022-01, with the labels that each got.

#840 CARDS-1369: Form pagination should be at the bottom of the screen regardless of the page size
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: bug

#832 CARDS-1478: Investigate Percona as db backend with encryption
  compose-cluster/percona_encryption_at_rest.md
Labels: question, current sprint

#822 CARDS-1457: Enable emailing functionality in Sling
  modules/email-notifications/pom.xml
  modules/email-notifications/src/main/features/feature.json
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTestEndpoint.java
  modules/pom.xml
Labels: tested, current sprint

#845 Update readme with list of currently supported projects
  README.md
Labels: easy to review

#844 CARDS-1559: Support building and running different instances in parallel
  .gitignore
  pom.xml
  start_cards.sh
Labels: tested

#843 CARDS-1487: Update the PROMs patient UI to only display pre-created surveys
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: current sprint

#847 CARDS-1562: Forms created by the mock Proms authentication are broken in the regular user UI
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/SimpleAnswerLabelProcessor.java
Labels: tested, Merge me!, easy to review

#846 CARDS-1510: As a patient, I can see a meaningful description of the app I'm about to use on the landing page/identification screen
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: tested, Merge me!

#849 CARDS-1569: Proms patient login screen: Remove scroller from MRN field
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: tested, Merge me!, easy to review

#848 CARDS-1561: On the patient identification screen, replace the date field with dropdowns for day,month,year
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: tested, Merge me!, current sprint

#850 CARDS-1507: As a patient, I have access to a high-level interpretation of my survey responses
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TextQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PHQ9.xml
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: tested, Merge me!, current sprint

#854 CARDS-1584: Make certain answers easily available in the form's JSON
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AnswerCopyProcessor.java
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/AUDITC.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/EQ5D.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/GAD7.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/PHQ9.json
Labels: tested, urgent, Merge me!, current sprint

#853 CARDS-1506: As a patient, I can review my survey answers before finalizing my submission
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: tested, Merge me!, current sprint

#839 CARDS-1474: Associate an optional frequency with PROMs questionnaires
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/FormUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/QuestionnaireUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/SubjectTypeUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/api/SubjectUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/AbstractNodeUtils.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/FormUtilsImpl.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/QuestionnaireUtilsImpl.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/SubjectTypeUtilsImpl.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/SubjectUtilsImpl.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  pom.xml
  proms-resources/backend/pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
  proms-resources/feature/src/main/features/feature.json
  proms-resources/pom.xml
Labels: tested, Merge me!, current sprint

#856 CARDS-1456: Forms are not checked back in when they are filled out using the PROMs UI
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: Test me!, easy to review, current sprint

#855 CARDS-1576: If the terms of use change, patient users should be prompted to review and re-accept
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/TermsOfUse.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/ToUDialog.jsx
Labels: tested, Merge me!, easy to review, current sprint

#842 CARDS-1497: Terms of Use on patient's first login
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Footer/ToU.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/TermsOfUse.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/Footer.json
  proms-resources/frontend/src/main/frontend/src/Footer.jsx
  proms-resources/frontend/src/main/frontend/src/Header.jsx
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/ToUDialog.jsx
  proms-resources/frontend/src/main/frontend/src/ToULink.jsx
  proms-resources/frontend/src/main/frontend/src/index.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/libs/cards/PromsHomepage/html.GET.html
Labels: tested, Merge me!, current sprint

#858 CARDS-1563: App name is not consistent across the UI
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/AppName.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: Test me!, easy to review, current sprint

#859 CARDS-1581: Proms mode: Clinicians should not be able to create subjects
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  proms-resources/feature/src/main/features/feature.json
Labels: tested

#865 CARDS-1570: Remove text 'You have selected "none"...' for non-smokers in Smoking Cessation survey form
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/SC.xml
Labels: tested, urgent, Merge me!, easy to review, current sprint

#863 CARDS-1574: Patient UI overhaul - Identification screen
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: tested, urgent, Merge me!, easy to review, current sprint

#869 CARDS-1355: Review PROMs questionnaires
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Cardio.xml
Labels: Merge me!, easy to review, current sprint

#871 [typo] Fixed "dayly" typo in AUDIT-C
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
Labels: tested, Merge me!

#872 CARDS-1574: Patient UI overhaul - Disclaimer
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: tested, easy to review, current sprint

#870 CARDS-1601: Remove cancer wording from smoking cessation survey
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/SC.xml
Labels: tested, Merge me!

#867 CARDS-1511: Patients can see information about upcoming appointments
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
Labels: tested, Merge me!, easy to review, current sprint

#861 CARDS-1595: Compact property is not displayed for compact questions in the questionnaire wizard for the Radio Button / Checkbox Compact Test questionnaire
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/RadioButtonCheckboxCompactTest.xml
Labels: tested, easy to review

#874 CARDS-1600: Proms: As a patient user, I can access help for finding my MRN
  proms-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/mrn_helper_1.png
  proms-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/mrn_helper_2.png
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
Labels: tested, easy to review, current sprint

#879 CARDS-1550: Rework proms UI to get the data from the server
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/DataSubjectProcessor.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/SessionSubjectRestrictionPattern.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToJsonAdapterFactory.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/TermsOfUseServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
  proms-resources/feature/src/main/features/feature.json
  proms-resources/frontend/src/main/frontend/src/MockPatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/ToUDialog.jsx
  proms-resources/frontend/src/main/frontend/src/index.jsx
  proms-resources/frontend/src/main/frontend/src/testPatients.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/libs/cards/PromsHomepage/html.GET.html
  proms-resources/frontend/src/main/resources/SLING-INF/content/libs/cards/PromsHomepage/sessionAttributes.js
Labels: tested, urgent, Merge me!

#878 CARDS-1339: Patient users should only be able to access the PROMs ui
  modules/commons/src/main/features/feature-repoinit.txt
  modules/commons/src/main/frontend/src/components/PageNotFound.js
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  proms-resources/feature/src/main/features/feature.json
Labels: question, urgent, needs refactoring, easy to review, current sprint

#877 CARDS-1599: Subject resources can be serialized in Text (.txt) and Markdown (.md) formats
  modules/data-entry/pom.xml
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AbstractFormToStringSerializer.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AbstractSubjectToStringSerializer.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/FormToMarkdownProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/FormToTextAdapterFactory.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/SubjectToMarkdownAdapterFactory.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/SubjectToTextAdapterFactory.java
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/Subject/md.GET.html
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/Subject/txt.GET.html
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToMarkdownAdapterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToTextAdapterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/ResourceMarkdownProcessor.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/ResourceTextProcessor.java
Labels: tested, urgent, Merge me!, current sprint

#880 CARDS-1589: Only consider same clinic visits for form frequency
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/FormUtilsImpl.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
Labels: tested, urgent, current sprint

#885 [misc] Disable statistics in PROMS mode
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/UserStatistics.json
Labels: Merge me!

#888 CARDS-1613: Don't quick-search in Questionnaires by default
  modules/data-entry/src/main/resources/SLING-INF/content/apps/cards/config/QuickSearch.json
Labels: tested, easy to review, current sprint

#887 CARDS-1475: PROMs Dashboard - More accurate title and label
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/PMCC-ACHD.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/DashboardViewsPMCC-ACHD.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/DashboardViewsPMCC.json
Labels: tested, urgent, easy to review, current sprint

#886 CARDS-1608: More helpful page displayed to non-patient users trying to access /Proms.html
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
  modules/commons/src/main/frontend/src/components/PageNotFound.js
  proms-resources/frontend/src/main/frontend/src/proms/index.jsx
Labels: tested, easy to review

#875 CARDS-1417: Print-friendly styling of forms - refactoring with a reusable, self-contained Print button
  modules/commons/src/main/resources/SLING-INF/content/libs/cards/Resource/header.html
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
Labels: tested, urgent, Merge me!, current sprint

#876 CARDS-1489: As a clinician, I can print all forms directly associated with a patient or related subject
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent, Merge me!, easy to review, current sprint
