Repository data-team-uhn/cards, pull requests merged in 2022-03, with the labels that each got.

#948 CARDS-1671: Escape key in the questionnaire editor's edit dialog causes console error and white screen
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
Labels: tested, easy to review

#951 CARDS-1674: As and admin, I can enable the entry of Notes associated with answers to any type of question using the questionnaire wizard
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: tested, Merge me!, easy to review

#942 CARDS-1459: Rework form pagination to prevent rendering non-active pages
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
Labels: tested

#950 CARDS-1673: PROMs: Only send notification emails for visits that are "planned"
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
Labels: tested, Merge me!

#949 CARDS-1672: PROMs: Wrong answer for the "patient submitted" question in imported visits
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: tested, Merge me!

#955 CARDS-1658 / CARDS-1666: Review WHODAS change
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/WHODAS.xml
Labels: easy to review

#957 CARDS-1680: PROMs: Multiple notifications are sent when a visit time changes
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: tested, Merge me!, easy to review

#956 CARDS-1658 / CARDS-1679: Add Proctor Device ID to 6MWT and GWT
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Graded Walk Test.xml
Labels: tested, urgent, Merge me!, easy to review

#954 CARDS-1677: Update DATA-PRO TOU
  modules/commons/src/main/frontend/src/components/ResponsiveDialog.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/TermsOfUse.xml
  proms-resources/frontend/src/main/frontend/src/proms/ToUDialog.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToULink.jsx
Labels: tested, urgent, Merge me!

#960 CARDS-1683: Conditionals do not support <= or >=
  modules/data-entry/src/main/frontend/src/questionnaire/ConditionalSingle.jsx
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/ConditionalSectionUtils.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/LongConditionalTest.xml
Labels: tested, needs refactoring, easy to review

#962 CARDS-1687: AppointmentUtils occasionally fails to compile with a Multiple String Literals error.
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
Labels: tested, Merge me!, easy to review

#963 Misc: Install bash in the build stage image of the Docker image build pipeline
  distribution/make_filled_m2.sh
Labels: easy to review

#961 CARDS-1686: Wrong version of CARDS used in released docker images
  distribution/Dockerfile
  distribution/docker_entry.sh
Labels: tested, urgent, Merge me!, easy to review

#965 CARDS-1688: When building self-contained Docker images, Webpack resources should be built in production mode
  distribution/make_filled_m2.sh
Labels: easy to review

#967 CARDS-1689: Proms mode: White screen of death upon accepting Terms of Use
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
Labels: tested, Merge me!, easy to review

#972 CARDS-1692: AUDIT-C form marked as complete when automatically created
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
Labels: tested, urgent, Merge me!, easy to review

#973 CARDS-1694: Logs are filled with Access Denied errors when using the PROMS UI
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AnswerCopyProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/FormRelatedSubjectsEditor.java
Labels: tested

#970 CARDS-1492: Slack notifications: # of upcoming appts, # of initial emails sent, # of reminder emails sent, # of surveys completed
  Utilities/Development/mock_slack.js
  distribution/src/main/features/base-repoinit.txt
  modules/http-requests/pom.xml
  modules/http-requests/src/main/features/feature.json
  modules/http-requests/src/main/java/io/uhndata/cards/httprequests/HttpRequests.java
  modules/metrics/pom.xml
  modules/metrics/src/main/features/feature.json
  modules/metrics/src/main/java/io/uhndata/cards/metrics/Metrics.java
  modules/pom.xml
  proms-resources/backend/pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AbstractPromsNotification.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/InitialNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/ReminderNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/slacknotifications/NightlySlackNotifications.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/slacknotifications/SlackNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/submissioncounter/SubmissionCounter.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/submissioncounter/SubmissionEventListener.java
  proms-resources/feature/src/main/features/feature.json
Labels: large PR, current sprint

#966 CARDS-1631: Mark visits with no surveys as "No surveys assigned"
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Visit information.json
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
Labels: tested

#974 CARDS-1696: Remove End of Study Physical Assessment
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/End of Study Physical Assessment.xml
Labels: tested

#978 CARDS-1606: As a patient, I receive rich text notification emails to fill out my pre-appointment surveys in DATA-PRO - HTML email template styling
  proms-resources/backend/src/main/resources/SLING-INF/content/apps/cards/proms/clinics/Cardio/mailTemplates/24h.html
  proms-resources/backend/src/main/resources/SLING-INF/content/apps/cards/proms/clinics/Cardio/mailTemplates/72h.html
Labels: tested, Merge me!, easy to review

#977 CARDS-1606: As a patient, I receive rich text notification emails to fill out my pre-appointment surveys in DATA-PRO
  distribution/Dockerfile
  distribution/mailcap
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTestEndpoint.java
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailUtils.java
  pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AbstractPromsNotification.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/InitialNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/ReminderNotificationsTask.java
  start_cards.sh
Labels: urgent

#981 CARDS-1700: Add the ability for developers and testers to view the emails that are sent by CARDS
  Utilities/Development/EmailServer/Dockerfile
  Utilities/Development/EmailServer/README.md
  Utilities/Development/EmailServer/docker_entry.sh
  Utilities/Development/EmailServer/main.cf
  Utilities/Development/EmailServer/master.cf
  Utilities/Development/EmailServer/screenshots/001.png
  Utilities/Development/EmailServer/screenshots/002.png
  Utilities/Development/EmailServer/screenshots/003.png
  Utilities/Development/EmailServer/screenshots/004.png
  Utilities/Development/EmailServer/screenshots/005.png
  Utilities/Development/EmailServer/screenshots/006.png
  Utilities/Development/EmailServer/screenshots/007.png
  Utilities/Development/EmailServer/screenshots/008.png
  Utilities/Development/EmailServer/screenshots/009.png
  Utilities/Development/EmailServer/start_container.sh
  compose-cluster/SSL_CONFIG/cards_certs/README.md
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
Labels: urgent

#975 Update the provider filter
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: on hold, easy to review

#979 [misc] Torch Mock Server Updates
  Utilities/Development/mock_torch.js
Labels: on hold, urgent

#985 CARDS-1675: Exclude cancelled appointments form all data listings on the PROMs dashboard
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
Labels: tested, urgent, easy to review
