Repository data-team-uhn/cards, pull requests merged in 2022-08, with the labels that each got.

#1144 [MISC] Import Heracles Form Changes
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Non-Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical Lab Results.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
  heracles-resources/clinical-data/util/import.py
Labels: urgent, Merge me!

#1116 CARDS-1103: As a user, I can see answers from other forms in the form I am filling in
  modules/data-entry/src/main/features/feature.json
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ReferenceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/QuestionnaireUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/AnswersEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ComputedAnswersEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/QuestionnaireUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersEditorProvider.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractAnswerCopyProcessor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/FormAnswerCopyProcessor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/SubjectAnswerCopyProcessor.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ReferenceTestCopied.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ReferenceTestUser.xml
Labels: incomplete, urgent, Merge me!, Test me!

#1143 CARDS-1813: Heracles: Populate study stream questions based on study stream form answer
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
Labels: urgent, Merge me!, Test me!

#1146 CARDS-1812: Computing form completion status flags overwrites any oth…
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/AnswerCompletionStatusEditor.java
Labels: easy to review

#1151 CARDS-1890: Update 6MWT to add conditional severity question in CARDS4Care
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: tested

#1153 [Misc] Update wording and minAnswers of 6MWT
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: question, tested, Merge me!, easy to review

#1067 CARDS-1783: Make email scheduling more flexible
  distribution/src/main/features/base-repoinit.txt
  modules/metrics/src/main/java/io/uhndata/cards/metrics/Metrics.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AbstractEmailNotification.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentEmailNotificationsFactory.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/GeneralNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/InitialNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/NightlyNotifications.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/ReminderNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/slacknotifications/SlackNotificationsTask.java
  proms-resources/feature/src/main/features/feature.json
Labels: tested, urgent, large PR

#971 CARDS-1693: Sometimes starting CARDS fails with "setting ACL" errors
  modules/data-entry/src/main/features/feature.json
  modules/data-entry/src/main/features/permissions_ownership.json
  modules/data-entry/src/main/features/permissions_trusted.json
  proms-resources/backend/pom.xml
  proms-resources/feature/src/main/features/feature.json
  proms-resources/permissions/pom.xml
  proms-resources/permissions/src/main/java/io/uhndata/cards/proms/permissions/UnsubmittedFormsRestrictionFactory.java
  proms-resources/permissions/src/main/java/io/uhndata/cards/proms/permissions/UnsubmittedFormsRestrictionPattern.java
  proms-resources/pom.xml
Labels: tested

#1155 CARDS-1900: Optimize VisitChangeListener when no frequencies are specified
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
Labels: easy to review

#1159 CARDS-1909: Heracles: Saving a 6MWT form with an answer to the Reason question fails
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: tested, Merge me!, easy to review

#1160 CARDS-1908: Updates to Heracles questionnaires
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Medications.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Non-Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, Merge me!, easy to review
