Repository data-team-uhn/cards, pull requests merged in 2022-11, with the labels that each got.

#1196 CARDS-1936: TSV export
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/QuestionnaireCSVServlet.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
Labels: tested, Merge me!, easy to review

#1203 CARDS-1944: Heracles Questionnaire Updates
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
Labels: tested, Merge me!

#1195 CARDS-1935: Add support for the --demo and --demo_banner flags to the generate_compose_yaml.py script
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
Labels: tested, Merge me!, easy to review

#1200 CARDS-1947: Add support for an --adminer flag to generate_compose_yaml.py
  compose-cluster/generate_compose_yaml.py
Labels: tested, Merge me!, easy to review, low risk

#1206 CARDS-1949: As an admin using the questionnaire designer, I can access contextual help / detailed descriptions of the questionnaire items' fields
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/BooleanInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ConditionalValueInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditorInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownTextField.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NumberInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ObjectInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ReferenceInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/TextInput.jsx
Labels: tested, Merge me!

#1207 CARDS-1953: Loading a patient chart should display a loading indicator while the forms are being fetched
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, easy to review

#1211 CARDS-1965: Disable WebDAV
  distribution/src/main/features/base.json
  distribution/src/main/features/oak/oak_base.json
Labels: tested, urgent, Merge me!, easy to review

#1210 CARDS-1960: Update the prems logo
  prems-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/media/prems/logo.png
  prems-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/media/prems/logo_light_bg.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
Labels: tested, easy to review

#1214 [misc] Minor update to the PREMs welcome message
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
Labels: Test me!, easy to review

#1209 CARDS-1955: PageStart extensions are loaded too many times
  modules/page-start-header/src/main/frontend/src/PageStart.jsx
Labels: tested, Merge me!, easy to review, low risk

#1201 CARDS-1884: Implement a mapping between local questionnaire / question IDs and the corresponsing IDs within EPIC
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ExternalLink.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested, urgent, Merge me!

#1212 CARDS-1961: Update the prems terms of use
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
Labels: tested, Merge me!

#1213 CARDS-1966: Display the link to Terms of Use on the patient portal error page
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
Labels: tested, easy to review

#1215 [misc] Include hidden answers in the CSV export
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
Labels: tested, urgent, Merge me!, easy to review

#1217 [code-cleanup] Removed unused import
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
Labels: easy to review, low risk
