Repository data-team-uhn/cards, pull requests merged in 2022-04, with the labels that each got.

#986 [misc] Improve the correctness and performance of PROMs dashboard queries
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
Labels: tested, urgent, Merge me!, easy to review

#984 CARDS-1637: Make certain answers easily accessible in the subject json
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AbstractAnswerCopyProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AnswerCopyProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/FormAnswerCopyProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/SubjectAnswerCopyProcessor.java
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/AUDITC.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/EQ5D.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/GAD7.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/PHQ9.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/SC.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/Visit information.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/SubjectTypes/Patient/Visit.json
Labels: tested, urgent, Merge me!

#988 CARDS-1706: Improve the look of filters for very long questions or answers
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/NumericFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/TextFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent, Merge me!, easy to review

#990 CARDS-1711: Add date to WHODAS, CHS, RAS
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Changes in Health Survey.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Recent Activities Survey.xml
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/WHODAS.xml
Labels: tested, Merge me!, easy to review

#994 CARDS-1640: Proms mode: start_cards.sh should do all necessary initialization without requiring any additional manual settings
  start_cards.sh
Labels: easy to review

#992 CARDS-1717: Proms mode 'GO TO MY SURVEYS' button outdated '/Cardio' link
  proms-resources/feature/src/main/features/feature.json
Labels: tested, Merge me!, easy to review

#993 CARDS-1623: Add basic support for DICOM image storage
  clindig-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Dicom.xml
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/DicomQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/dicomDataDictionary.js
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/DicomLabelProcessor.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: tested

#991 [misc] Minor improvements in handling answerMetadata
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
Labels: tested, Merge me!, easy to review

#1001 Redact the values for all DICOM tags listed in dicomRedactedTags.js upon creation of the DICOM metadata Notes field
  modules/data-entry/src/main/frontend/src/questionnaire/DicomQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/dicomRedactedTags.js
Labels: tested

#1002 CARDS-1698: Set up the clindig project for CARDS -- Include PROMs functionality
  start_cards.sh
Labels: easy to review

#995 CARDS-1722: .data JSON processor uses slow and lightly wrong query when filtering by status
  cardiac-rehab-resources/backend/src/main/java/io/uhndata/cards/cardiacrehab/internal/export/ExportTask.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/DataSubjectProcessor.java
  modules/vocabularies/src/main/frontend/src/vocabularyAction.jsx
Labels: tested, Merge me!

#996 CARDS-1722: .data JSON processor uses slow and lightly wrong query when filtering by status
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportTask.java
  modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/dataentry/internal/serialize/DataProcessor.java
Labels: Merge me!

#989 CARDS-1633: The score interpretation displayed to the patient after they submit their responses should be configurable by clinic
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Mood.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PHQ9.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
Labels: tested, urgent, Merge me!

#1000 CARDS-1715: As a user landing on the PROMs login page, I can choose whether I wish to authenticate as a Patient or a Healthcare Provider
  proms-resources/frontend/pom.xml
  proms-resources/frontend/src/main/frontend/src/proms/PromsLandingPage.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/LoginPageStart/PromsLandingPage.json
Labels: tested, urgent, Merge me!, easy to review

#983 CARDS-1612: Automatically generate side bar entries, dashboard extensions, and user groups for onboarded clinics
  modules/commons/pom.xml
  modules/commons/src/main/resources/SLING-INF/content/libs/cards/ResourceHomepage/ROOT.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  modules/statistics/src/main/resources/SLING-INF/nodetypes/statistics.cnd
  proms-resources/backend/pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ClinicsServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/Clinics.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Views/Clinics.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/ClinicMapping.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
  proms-resources/frontend/src/main/frontend/src/proms/ClinicStyle.jsx
  proms-resources/frontend/src/main/frontend/src/proms/Clinics.json
  proms-resources/frontend/src/main/frontend/src/proms/Clinics.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/PMCC-ACHD.json
Labels: urgent, Test me!

#1006 CARDS-1731: Refactor the PROMs dashboard to display appointments and surveys by default
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ClinicsServlet.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/ClinicMapping.xml
  proms-resources/frontend/src/main/frontend/src/proms/PromsDashboard.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/AUDITCView.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/EQ5DView.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/GAD7View.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/PHQ9View.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/SCView.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/DashboardViews/VisitView.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/PMCC-ACHD.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/DashboardViews853703519.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/DashboardViewsPMCC-ACHD.json
Labels: tested, urgent, Merge me!

#1009 [misc] Fix wording on the proms landing page
  proms-resources/frontend/src/main/frontend/src/proms/PromsLandingPage.jsx
Labels: easy to review

#1013 CARDS-1740: Appointments with the status 'entered-in-error' should not appear on the PROMs dashboard
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
Labels: Test me!, easy to review

#1012 CARDS-1732: Appointment utils is doing the incorrect check for invalid appointments
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
Labels: easy to review

#1011 CARDS-1735: Patient authentication cookies should expire when the token expires
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/CardsTokenImpl.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/sling/TokenAuthenticationHandler.java
Labels: easy to review

#1008 CARDS-1716: As a patient user, I can authenticate without a token
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/labels/AnswerOptionsLabelProcessor.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/QuestionnaireRestrictionFactory.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/QuestionnaireRestrictionPattern.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Mood.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
  proms-resources/feature/src/main/features/feature.json
  proms-resources/frontend/src/main/frontend/src/proms/Header.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUDialog.jsx
  proms-resources/frontend/src/main/frontend/src/proms/index.jsx
Labels: urgent, Test me!

#1017 [misc] Bulletproofing the token-less authentication code
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
Labels: easy to review

#1014 Misc: Add documentation on how to obtain JWTs from Vault and use them to query Torch for upcoming appointments
  proms-resources/DHP_Torch_Integration.md
Labels: easy to review
