Repository data-team-uhn/cards, pull requests merged in 2022-07, with the labels that each got.

#1099 [misc] Heracles mode broken due to double dependency versions
  heracles-resources/feature/src/main/features/feature.json
  modules/webhook-backup/src/main/features/feature.json
Labels: tested, Merge me!

#1102 [misc] Upgrade eslint from a no longer available version to 7.29.0
  Utilities/Development/ExtensionPointResources/package.json
  lfs-resources/variants/src/main/frontend/package.json
  modules/commons/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/package.json
  modules/demo-banner/src/main/frontend/package.json
  modules/downtime-warning-banner/src/main/frontend/package.json
  modules/homepage/src/main/frontend/package.json
  modules/login/src/main/frontend/package.json
  modules/page-start-header/src/main/frontend/package.json
  modules/pedigree/src/main/frontend/package.json
  modules/permissions-trusted/src/main/frontend/package.json
  modules/principals/src/main/frontend/package.json
  modules/statistics/src/main/frontend/package.json
  modules/token-authentication/src/main/frontend/package.json
  modules/ui-extension/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/package.json
  proms-resources/frontend/src/main/frontend/package.json
Labels: tested, Merge me!

#1097 CARDS-1839: Update the labels in Visit information to something more generic
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
Labels: tested, Merge me!, easy to review

#1094 CARDS-1773: Add configuration for whether patients need to accept ToU before proceeding
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/TermsOfUse.xml
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUDialog.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/ToUConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/ToUConfiguration.json
Labels: tested, Merge me!

#1104 CARDS-1848: The patient identification should not send "undefined" for unfilled inputs
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
Labels: tested, easy to review

#1103 CARDS-1844: As an administrator, I can update the Terms of Use from the admin UI
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/TermsOfUse.xml
  proms-resources/frontend/src/main/frontend/src/proms/ToUConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUDialog.jsx
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/ToUConfiguration.json
Labels: Test me!

#1111 [misc] Disable docker build by default
  README.md
  distribution/pom.xml
Labels: tested, Merge me!

#1109 CARDS-1852: Bold fonts in Firefox are not bold enough
  modules/commons/src/main/resources/SLING-INF/content/libs/cards/Resource/header.html
  modules/data-entry/src/main/frontend/src/questionnaireEditor/LabeledField.jsx
Labels: tested, Merge me!

#1105 [misc] Update some sling dependencies
  distribution/src/main/features/base.json
  distribution/src/main/features/boot.json
  modules/data-entry/src/main/features/feature.json
  modules/email-notifications/src/main/features/feature.json
  modules/metrics/src/main/features/feature.json
  modules/statistics/src/main/features/feature.json
  modules/ui-extension/src/main/features/feature.json
  modules/vocabularies/src/main/features/feature.json
  pom.xml
Labels: tested, Merge me!, easy to review

#1120 CARDS-1858: Update 6MWT xml to match prod
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: tested, Merge me!

#1110 CARDS-1851: Add Cancel button to all single-configuration admin screens
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminScreen.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/WelcomeMessageConfiguration.jsx
Labels: tested, Merge me!

#1100 CARDS-1847: Incorrect identification of upcoming visits with tokenless authentication when declining the Terms of Use
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/ToUDialog.jsx
Labels: tested, easy to review

#1124 CARDS-1649: SAML login: Disable NEXT button when username is blank
  modules/login/src/main/frontend/src/login/loginForm.js
Labels: tested, Merge me!, easy to review

#1117 CARDS-1856: Fix java build warnings
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/ExportEndpoint.java
  modules/data-entry/src/main/java/io/uhndata/cards/DataImportServlet.java
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/serialize/SubjectTypeInstanceCountProcessor.java
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTestEndpoint.java
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/VocabularyBioPortalApiKeyServlet.java
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/internal/BioOntologyIndexer.java
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/internal/NCITFlatIndexer.java
  modules/vocabularies/src/test/java/io/uhndata/cards/vocabularies/VocabularyIndexerServletTest.java
  modules/webhook-backup/src/main/java/io/uhndata/cards/webhookbackup/WebhookBackupEndpoint.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportEndpoint.java
  test-resources/src/main/java/io/uhndata/cards/test/MockNCREndpoint.java
Labels: tested

#1126 CARDS-1873: Java compiler warnings should fail the build
  pom.xml
Labels: easy to review

#1123 CARDS-1864: Responsive layout on the Admin Dashboard
  modules/homepage/src/main/frontend/src/adminDashboard/AdminDashboard.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminDashboardStyle.jsx
Labels: tested, Merge me!, easy to review

#1128 [misc] Upgrade org.codehaus.woodstox:stax2-api
  modules/saml-support/src/main/features/base.json
Labels: easy to review

#1114 CARDS-1836: As an administrator, I can configure the texts in the Patient Portal Survey UI
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/SurveyInstructions.xml
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/SurveyInstructionsConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/index.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/SurveyInstructionsConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/SurveyInstructionsConfiguration.json
Labels: tested, Merge me!

#1125 CARDS-1872: Sign In button is improperly rendered when using two-step login
  modules/login/src/main/frontend/src/login/loginForm.js
  modules/login/src/main/frontend/src/styling/styles.js
Labels: easy to review

#1132 [misc] Bump com.h2database:h2-mvstore dependency version to 2+
  distribution/src/main/features/oak/persistence/oak_persistence_mongods.json
Labels: dependencies, tested, urgent, Merge me!, easy to review

#1137 CARDS-1835: Update the ui with the new status as the form gets saved
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToTextAdapterFactory.java
Labels: tested, Merge me!, easy to review

#1133 CARDS-1704: Uninformative error message displayed when attempting to create a subject with an identifier that already exists
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, Merge me!, easy to review

#1136 CARDS-1875: Tab navigation is broken on the Admin Dashboard in Firefox
  modules/homepage/src/main/frontend/src/adminDashboard/AdminDashboard.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminDashboardStyle.jsx
Labels: Test me!, easy to review

#1130 CARDS-1868: As an admin, I can configure the clinician dashboard
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/DashboardSettings.xml
  proms-resources/frontend/src/main/frontend/src/proms/DashboardSettingsConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsDashboard.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsView.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsViewInternal.jsx
  proms-resources/frontend/src/main/frontend/src/proms/VisitView.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/DashboardSettingsConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/DashboardSettingsConfiguration.json
Labels: tested, urgent, Merge me!

#1141 CARDS-1878: Broken visit date displayed on the clinic dashboard
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Mood.xml
Labels: Test me!, easy to review

#1134 CARDS-1869: Move the Patient Portal Welcome Message from its own admin section to the beginning of the Patient Portal Survey Instructions section
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/SurveyInstructions.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/WelcomeMessage.xml
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/SurveyInstructionsConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/WelcomeMessageConfiguration.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/WelcomeMessageConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/WelcomeMessageConfiguration.json
Labels: tested, Merge me!

#1140 [Misc] Subject Creation Scripts
  Utilities/Development/create_n_level_deep_subject.py
  Utilities/Development/create_subject_for_type.py
  Utilities/Development/create_subject_type.py
Labels: easy to review

#1138 CARDS-1874: CARDS should support connecting to external Mongo Replica Sets in addition to singular external Mongo instances
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
  distribution/src/main/features/oak/persistence/oak_persistence_mongods.json
Labels: urgent

#1139 CARDS-1876 & CARDS-1699: Recurring section styling improvements
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/EditButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/RecurringSectionTest.xml
Labels: tested

#1115 [misc] Dockerize backup_recorder.js
  Utilities/Administration/Backup-To-JSON/backup_recorder.js
  Utilities/ExpressJS-Docker/Dockerfile
  Utilities/ExpressJS-Docker/README.md
  Utilities/ExpressJS-Docker/docker_entry.sh
  Utilities/ExpressJS-Docker/pom.xml
  Utilities/pom.xml
  compose-cluster/generate_compose_yaml.py
  pom.xml
Labels: easy to review

#1142 CARDS-1221: Prevent creation of parentless child subjects
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/SubjectHierarchyValidator.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/SubjectHierarchyValidatorProvider.java
Labels: tested, Merge me!

#1145 [misc] Reorder PROMs admin sections, improve their hints
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/Clinics.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/DashboardSettingsConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/SurveyInstructionsConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/ToUConfiguration.json
Labels: urgent, Merge me!, easy to review
