Repository data-team-uhn/cards, pull requests merged in 2022-09, with the labels that each got.

#1166 CARDS-1911: All custom cards ACL restrictions are failing to be evaluated
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/FormsRestrictionProvider.java
Labels: tested, urgent

#1167 CARDS-1912: cards:unsubmittedForms restriction is not being evaluated
  proms-resources/feature/src/main/features/feature.json
Labels: tested, urgent, easy to review

#1165 CARDS-1910: Log every form pushed from Heracles/CaRe
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/ExportTask.java
Labels: Test me!

#1157 CARDS-1867: As an admin, I can configure the patient identification process
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/api/PatientAccessConfiguration.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AbstractEmailNotification.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentEmailNotificationsFactory.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/GeneralNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/PatientAccessConfigurationImpl.java
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/PatientIdentification.xml
  proms-resources/frontend/src/main/frontend/src/proms/Header.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentification.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PatientIdentificationConfiguration.jsx
  proms-resources/frontend/src/main/frontend/src/proms/PromsLandingPage.jsx
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/index.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/PatientIdentificationConfiguration.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Views/PatientIdentificationConfiguration.json
Labels: tested, urgent, Merge me!

#1171 CARDS-1917: Patient portal: unresponsive ui when trying to accept the Terms of Use in absence of the Patient information form
  modules/patient-interface/src/main/frontend/src/proms/PatientIdentification.jsx
  modules/patient-interface/src/main/frontend/src/proms/ToUDialog.jsx
Labels: bug, urgent, easy to review

#1176 CARDS-1919: Occasionally after logging out of the patient portal the app crashes
  modules/patient-interface/src/main/frontend/src/proms/index.jsx
Labels: Merge me!

#1175 CARDS-1916: Trying to log in as a patient with a token while the Patient Information form doesn't exist ends with a white screen
  modules/patient-interface/src/main/java/io/uhndata/cards/proms/ValidateCredentialsServlet.java
Labels: Test me!

#1172 CARDS-1914 - Patient portal: improve the configurability of the survey start screen
  modules/patient-interface/src/main/frontend/src/proms/QuestionnaireSet.jsx
  modules/patient-interface/src/main/frontend/src/proms/SurveyInstructionsConfiguration.jsx
  modules/patient-interface/src/main/frontend/src/proms/index.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/SurveyInstructions.xml
Labels: tested, urgent

#1168 CARDS-1910: Log every form pushed from Heracles/CaRe
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportTask.java
Labels: tested, Merge me!

#1154 Misc: Ensure that the response to /fetch_requires_saml_login.html and /goto_saml_login are never cached
  compose-cluster/proxy/http_saml_000-default.conf
  compose-cluster/proxy/https_saml_000-default.conf
Labels: Merge me!, easy to review

#1178 [misc] Center horizontal sliders horizontally in the question box
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, Merge me!, easy to review

#1163 CARDS-1893: Publish the Alpine Linux APK package status files for each CARDS Docker image that is in deployment
  Utilities/SecurityScanning/build_package_listing_docker_image.sh
Labels: easy to review

#1156 CARDS-1902: Add support for using Cloud-IAM.com as a SAML IdP for testing purposes
  Utilities/Administration/SAML/cloud-iam_demo_samlKeystore.p12.sha256sum
  Utilities/Development/keycloak_headermod_http_proxy.js
  compose-cluster/CloudIAMdemoKeystoreSha256Property.py
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
  modules/pom.xml
  modules/saml/cloud-iam-demo-saml/pom.xml
  modules/saml/cloud-iam-demo-saml/src/main/features/feature.json
  modules/saml/cloud-iam-demo-saml/src/main/resources/SLING-INF/content/cloud-iam.demo.json
  modules/saml/pom.xml
  pom.xml
  start_cards.sh
Labels: Merge me!, Test me!

#1184 CARDS-1905: Date range answers with maxAnswers=1 cause the form to be invalid
  modules/form-completion-status/pom.xml
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/AnswerCompletionStatusEditor.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/AnswerCompletionStatusEditorProvider.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/DateRangeMinMaxAnswersValidator.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/MinMaxAnswersValidator.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/MinMaxValueValidator.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/spi/AnswerValidator.java
Labels: Merge me!

#1186 [misc] start_cards.sh - unary operator expected fix
  start_cards.sh
Labels: easy to review

#1185 CARDS-1928: Enable exporting all forms in CSV
  Utilities/Administration/export_csvs.py
Labels: tested, Merge me!, easy to review, low risk

#1182 CARDS-1915: Add support for launching a S3 bucket Docker container to the generate_compose_yaml.py script
  compose-cluster/generate_compose_yaml.py
Labels: tested, easy to review

#1187 CARDS-1526: The start_cards.sh script should have a --debug option to enable and wait on Java Debugger (JDB) attachment
  start_cards.sh
Labels: easy to review

#1174 CARDS-1778: Set up prems-resources
  distribution/docker_entry.sh
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
  pom.xml
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/media/prems/logo.png
  prems-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/media/prems/logo_light_bg.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/TGH-ED.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/TGH-IP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/TW-ED.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/TW-IP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/ExtensionsOverride/Sidebar/UserStatistics.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/DashboardSettings.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/PatientIdentification.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-EMERGENCY/mailTemplates/invitation.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-EMERGENCY/mailTemplates/invitation.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-EMERGENCY/mailTemplates/reminder.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-EMERGENCY/mailTemplates/reminder.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-INPATIENT/mailTemplates/invitation.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-INPATIENT/mailTemplates/invitation.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-INPATIENT/mailTemplates/reminder.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TGH-INPATIENT/mailTemplates/reminder.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-EMERGENCY/mailTemplates/invitation.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-EMERGENCY/mailTemplates/invitation.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-EMERGENCY/mailTemplates/reminder.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-EMERGENCY/mailTemplates/reminder.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-INPATIENT/mailTemplates/invitation.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-INPATIENT/mailTemplates/invitation.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-INPATIENT/mailTemplates/reminder.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/TW-INPATIENT/mailTemplates/reminder.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/OAIP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/OED.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/Patient information.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/Visit information.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/SubjectTypes/Patient/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/SubjectTypes/Patient/Visit.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/AppName.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/Media.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  prems-resources/feature/pom.xml
  prems-resources/feature/src/main/features/feature.json
  prems-resources/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Mood.xml
  start_cards.sh
Labels: urgent

#1177 CARDS-1781: Configure surveys and their frequencies
  .gitignore
  Utilities/FormImport/import.py
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
Labels: urgent, Test me!

#1189 [misc] Fix expiry date of visit token generated for email links
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
Labels: easy to review

#1188 CARDS-1918: .token.html ignores the configured token expiry setting
  modules/token-authentication/src/main/resources/SLING-INF/content/libs/cards/Subject/token.html.esp
Labels: Test me!, easy to review, low risk

#1183 CARDS-1895: Publish the yarn.lock file for each CARDS Docker image that is in deployment
  Utilities/SecurityScanning/get_yarn_lock_file_for_docker_image.sh
  distribution/Dockerfile
Labels: tested, easy to review

#1193 CARDS-1432: The Statistics module should be enabled per project, not by default
  distribution/src/main/features/core/statistics.json
  lfs-resources/feature/src/main/features/feature.json
  modules/statistics/pom.xml
  modules/statistics/src/main/features/feature-repoinit.txt
  modules/statistics/src/main/features/feature.json
  modules/statistics/src/main/resources/SLING-INF/content/Statistics.json
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/ExtensionsOverride/Sidebar/UserStatistics.json
  proms-resources/feature/src/main/features/feature.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/UserStatistics.json
Labels: tested
