Repository data-team-uhn/cards, pull requests merged in 2022-05, with the labels that each got.

#1021 PROMs Patient UI improvements: CARDS-1747, CARDS-1748, CARDS-1749, CARDS-1750, CARDS-1751
  modules/commons/src/main/frontend/src/components/style.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  proms-resources/frontend/src/main/frontend/src/proms/Header.jsx
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
Labels: tested, urgent, Merge me!, easy to review

#1025 CARDS-1755: Proms patient ui: refactoring of the review screen to use markdown serialization for faster loading
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/AbstractFormToStringSerializer.java
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
Labels: tested, easy to review

#1026 Proms mode: Allow for the role queries to be configured
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportConfigDefinition.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportEndpoint.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/NightlyImport.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: urgent

#1015 CARDS-1612: Create a user group for the new clinic
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/ClinicsServlet.java
Labels: tested, urgent, Merge me!, easy to review

#825 CARDS-1400: New Questionnaire entry type: Question matrix
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/CreationMenu.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Fields.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ObjectInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionMatrixEntry.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/data-entry/src/main/java/io/uhndata/cards/internal/QuestionMatrixEditor.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/QuestionMatrixEditorProvider.java
  modules/data-entry/src/main/java/io/uhndata/cards/internal/QuestionnaireQuickSearchEngine.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/QuestionMatrixTest.xml
Labels: tested, urgent, Merge me!, large PR

#1030 CARDS-1592: New Proms questionnaire SF12; CARDS-1594: questionnaire set for Mood Disorders
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Mood.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/SF12.xml
Labels: tested, urgent, easy to review

#1027 Misc: Fix mock_torch.js so that it works with the version of Express.js available in Debian 11
  Utilities/Development/mock_torch.js
Labels: urgent, easy to review

#1037 Misc: Fix mock_slack.js so that it works with the version of Express.js available in Debian 11
  Utilities/Development/mock_slack.js
Labels: urgent, easy to review

#1041 CARDS-1720: Fix sidebar's scrollbar issues
  modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebarStyle.jsx
Labels: tested, Merge me!, easy to review

#1031 CARDS-1725: When there is scheduled maintenance downtime, display a warning banner to inform the users ahead of time
  distribution/src/main/features/core/cards.json
  modules/downtime-warning-banner/pom.xml
  modules/downtime-warning-banner/src/main/frontend/package.json
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/downtime-warning-banner/src/main/frontend/src/downtimeBanner.jsx
  modules/downtime-warning-banner/src/main/frontend/webpack.config.js
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/DowntimeWarningConfiguration.json
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/Extensions/LoginPageStart/DowntimeWarningBanner.json
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/Extensions/PageStart/DowntimeWarningBanner.json
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/Extensions/Views/DowntimeWarningConfiguration.json
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/apps/cards/config/DowntimeWarning.json
  modules/downtime-warning-banner/src/main/resources/SLING-INF/nodetypes/downtimeConfig.cnd
  modules/pom.xml
Labels: tested, urgent, Merge me!

#1005 CARDS-1724: Add support for coloured DICOM images and MONO other than knee and head
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/DicomQuestion.jsx
Labels: help wanted, tested

#969 CARDS-1669: Add support for exporting data as csv
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/QuestionnaireCSVServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/DataProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/QuestionnaireToCsvProcessor.java
  modules/data-entry/src/main/java/io/uhndata/cards/dataentry/internal/serialize/TreeGraph.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/CSVString.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToCSVAdapterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/ResourceCSVProcessor.java
Labels: tested

#1048 Misc: Cards4Proms docker_entry.sh fix - automatically enable the cards-email-notifications module in cards4proms mode
  distribution/docker_entry.sh
Labels: easy to review
