Repository data-team-uhn/cards, pull requests merged in 2022-02, with the labels that each got.

#891 CARDS-1355: Review PROMs questionnaires - AUDIT-C interpretation
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
Labels: tested, urgent, Merge me!, easy to review, current sprint

#892 CARDS-1614: Proms: Simplify the link given to the Patient for filling out their surveys
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
  proms-resources/frontend/src/main/frontend/src/proms/index.jsx
Labels: tested, urgent

#895 CARDS-1609: Better formatting of Upcoming appointment info with multiple providers and/or locations
  proms-resources/frontend/src/main/frontend/src/proms/QuestionnaireSet.jsx
Labels: tested, Merge me!, easy to review, current sprint

#890 CARDS-1539: Trusted permissions mode: Users outside of the Trusted users group should not be seeing any errors in the Dashboard, Forms and Variants
  modules/data-entry/pom.xml
  modules/data-entry/src/main/features/permissions_trusted.json
  modules/data-entry/src/main/resources/SLING-INF/content/Extensions/PendingUsersView/PendingUsersView.json
  modules/ui-extension/src/main/java/io/uhndata/cards/uix/ExtensionsManager.java
  proms-resources/feature/src/main/features/feature.json
  proms-resources/frontend/src/main/frontend/src/proms/PendingView.jsx
  proms-resources/frontend/src/main/frontend/webpack.config.js
Labels: tested, urgent, Merge me!

#896 CARDS-1339: Patient users should only be able to access the PROMs ui
  modules/commons/src/main/features/feature-repoinit.txt
Labels: tested, easy to review

#894 CARDS-1475: PROMs dashboard: one Appointments box + 5 more boxes, one per questionnaire, with the score displayed as one of the columns
  proms-resources/frontend/src/main/frontend/src/proms/PromsDashboard.jsx
Labels: tested, Merge me!, easy to review

#868 CARDS-1424: Send email to patients 72 hours prior to appointment, prompting them to complete the surveys
  modules/email-notifications/pom.xml
  modules/email-notifications/src/main/features/feature.json
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailUtils.java
  pom.xml
  proms-resources/backend/pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/InitialNotificationsTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/NightlyNotifications.java
  proms-resources/backend/src/main/resources/SLING-INF/content/apps/cards/proms/clinics/Cardio/mailTemplates/72h.html
  proms-resources/backend/src/main/resources/SLING-INF/content/apps/cards/proms/clinics/Cardio/mailTemplates/72h.txt
  proms-resources/feature/src/main/features/feature.json
  start_cards.sh
Labels: urgent, current sprint

#898 [misc] Better spacing for the User Dasboard widgets
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, Merge me!, easy to review

#893 CARDS-1611: Proms printing: include the header on every page
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
Labels: tested, urgent, Merge me!, easy to review, current sprint

#827 CARDS-1484 / CARDS-1349: Every night, query Torch to obtain patients who have appointments in the next 72h
  proms-resources/backend/pom.xml
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportConfig.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportConfigDefinition.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportEndpoint.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportTask.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/NightlyImport.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/ClinicMapping.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
  proms-resources/feature/src/main/features/feature.json
  proms-resources/pom.xml
Labels: urgent, current sprint

#902 CARDS-1475: PROMs dashboard - bugfix
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/UnsubmittedFormsRestrictionFactory.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/UnsubmittedFormsRestrictionPattern.java
Labels: tested, urgent, easy to review

#900 CARDS-1617: Ctrl+P bypasses react-to-print and prints what is on the screen
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceHeader.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, urgent, Merge me!, easy to review, current sprint

#903 CARDS-1475: PROMs dashboard
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/UnsubmittedFormsRestrictionFactory.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/UnsubmittedFormsRestrictionPattern.java
  proms-resources/feature/src/main/features/feature.json
Labels: tested

#905 [misc] Bugfix: importing Visit Information forms from CSV may cause errors to be logged
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/VisitChangeListener.java
Labels: tested, Merge me!

#904 [misc] Bugfix: accessing the Users or Groups administration causes stacktraces to be printed in the logs
  modules/principals/src/main/java/io/uhndata/cards/principals/PrincipalsServlet.java
Labels: tested, Merge me!

#909 CARDS-1628: Sometimes visit forms are also shown under patient in the patient's chart
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
Labels: urgent, Test me!, easy to review

#913 CARDS-1628 - Regression fix
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
Labels: urgent, Test me!, easy to review

#911 [misc] Bugfix: importing Visit Information forms may lead to exceptions
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
Labels: tested, Merge me!

#912 [misc] JS console warning/error fixes
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/login/src/main/frontend/src/login/loginForm.js
Labels: tested, Merge me!, easy to review

#910 CARDS-1594 Proms new clinic configuration
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/ClinicMapping.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Homepage/Proms/Mood.xml
Labels: Merge me!, easy to review

#882 CARDS-1423: Certain survey responses should trigger an immediate email to the on-call nurse
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/AppointmentUtils.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/EmailAlertEventListener.java
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/emailnotifications/EmailFormAlerts.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/nodetypes/proms.cnd
Labels: urgent, current sprint

#907 CARDS-1582: Proms mode: Clinicians can delete only forms that they created
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/CreatedByRestrictionFactory.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/CreatedByRestrictionPattern.java
  proms-resources/feature/src/main/features/feature.json
Labels: tested, Merge me!

#916 [misc] Proms mode should use trusted permissions by default
  start_cards.sh
Labels: tested, urgent, Merge me!

#917 [misc] Fix javadoc errors
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/FilterServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
  modules/principals/src/main/java/io/uhndata/cards/principals/PrincipalsServlet.java
  modules/ui-extension/src/main/java/io/uhndata/cards/uix/ExtensionsManager.java
  modules/utils/src/main/java/io/uhndata/cards/scripting/ContentTypeSetter.java
  modules/utils/src/main/java/io/uhndata/cards/scripting/StatusCodeSetter.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToJsonAdapterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/ResourceJsonProcessor.java
Labels: urgent, Merge me!

#924 [misc] Fix slower than usual startup when there are spaces in the username (usually on Windows)
  start_cards.sh
Labels: Merge me!, easy to review

#922 [misc] Fixed wrong logger class
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: Merge me!

#919 [misc] Better name for the PROMS Torch import configuration
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/ImportConfigDefinition.java
Labels: Merge me!

#925 [misc] Move the sling launcher cache directory inside our own data directory .cards-data
  start_cards.sh
Labels: tested, Merge me!, easy to review

#918 CARDS-1549: Periodically delete expired tokens
  modules/token-authentication/pom.xml
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/ExpiredTokensCleanupScheduler.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/ExpiredTokensCleanupTask.java
Labels: tested

#936 CARDS-1656: Print mode header doesn't stretch on the whole width of the page
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
Labels: tested, easy to review

#933 CARDS-1459: Rework form pagination to prevent rendering non-active pages instead of rendering and hiding them
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested

#937 [misc] Fixed filters delete button spacing from the filters inputs
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
Labels: tested, easy to review

#940 CARDS-1653: PROMs: email not imported (bugfix)
  proms-resources/backend/src/main/java/io/uhndata/cards/proms/internal/importer/PatientLocalStorage.java
Labels: easy to review

#941 [misc] Remove unused & deprecated dependency that was pulling in an old log4j jar during the build
  modules/token-authentication/pom.xml
Labels: tested, easy to review

#934 CARDS-1651: The SAMLRequest URL parameter should not be present in the address bar at the /login page
  Utilities/Development/keycloak_headermod_http_proxy.js
  compose-cluster/proxy/http_saml_000-default.conf
  compose-cluster/proxy/https_saml_000-default.conf
  modules/login/src/main/frontend/src/login/loginForm.js
Labels: tested, easy to review
