Repository data-team-uhn/cards, pull requests merged in 2022-12, with the labels that each got.

#1221 [code-cleanup] Removed unused variable and dead code from Clinics componen
  modules/patient-portal/src/main/frontend/src/patient-portal/Clinics.jsx
Labels: tested, Merge me!, easy to review

#1224 CARDS-1969: Users should not be allowed to upload HTML or JavaScript files
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/utils/pom.xml
  modules/utils/src/main/java/io/uhndata/cards/utils/internal/DenyScriptsSlingPostProcessor.java
Labels: urgent, easy to review

#1220 CARDS-1964: Prems surveys updates
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-EDIP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/invitation.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/invitation.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/reminder.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/reminder.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/CPESIC.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/OAIP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/OED.json
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, Merge me!, large PR

#1226 CARDS-1964: Prems clinics and surveys updates, take 3
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: tested, urgent, Merge me!

#1227 [misc] Forbid including CARDS in an iframe
  compose-cluster/proxy/http_000-default.conf
  compose-cluster/proxy/https_000-default.conf
Labels: tested, urgent, easy to review

#1230 CARDS-1949: As an admin using the questionnaire designer, I can access contextual help / detailed descriptions of the questionnaire items' fields
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
Labels: Merge me!, easy to review

#1229 [upgrade] Upgrading Python script to use non-deprecated library for the file management
  aggregated-frontend/src/main/frontend/webpack_script.py
Labels: tested, urgent, Merge me!, easy to review

#1232 CARDS-1971: Misplaced reference question in form's markdown export
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractFormToStringSerializer.java
Labels: tested, Merge me!

#1233 CARDS-1975: Heracles addition of external file uploads to 6MWT form
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
Labels: tested, urgent, easy to review

#1225 CARDS-1970: CopyAnswers doesn't support multivalued sources
  modules/data-model/forms/api/pom.xml
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractAnswerCopyProcessor.java
  modules/utils/pom.xml
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/PropertiesProcessor.java
Labels: tested

#1234 CARDS-1977: On admin screens such as Questionnaires or SubjectTypes, the livetable data fails to load if the url ends in `/`
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
Labels: tested, easy to review

#1235 CARDS-1978: As a patient filling out a paginated survey, I am presented with all the questions I must fill out before reaching the buttons to advance to the next page
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent, Merge me!

#1238 [misc] Replace old-style for loop causing build failure on new CARDS clones
  modules/data-entry/src/main/frontend/src/resourceQuery/QueryMatchingUtils.jsx
Labels: tested, urgent, Merge me!, easy to review

#1219 CARDS-1954: The questionnaire editor fetches the questionnaire JSON too many times
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireContext.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ConditionalValueInput.jsx
Labels: tested, Merge me!

#1240 CARDS-1964: Prems clinics and surveys updates - Bug fix
  prems-resources/clinical-data/pom.xml
Labels: urgent, easy to review

#1241 [misc] Make the surveys narrower in the patient portal
  modules/patient-portal/src/main/frontend/src/patient-portal/Header.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: easy to review

#1242 CARDS-1985 - Patient portal, token auth: the patient identification form is visible for a short while before the survey is loaded
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
Labels: urgent, Test me!

#1243 CARDS-1986: Questionnaire designer: The Add > Conditional menu item is not restored after deleting an existing condition
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: easy to review
