Repository data-team-uhn/cards, pull requests merged in 2023-12, with the labels that each got.

#1661 CARDS-2444: Boolean labels not shown in view mode
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, urgent, easy to review

#1662 CARDS-2424 / CARDS-2427: Configuration of export exclusions
  heracles-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1658 CARDS-2441: Computed questions only have access to the first value of multivalued variables
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/ExpressionUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ExpressionUtilsImpl.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/BackendComputedTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
Labels: urgent, Test me!, testing...

#1660 CARDS-2424 and CARDS-2402: New Phone Call Follow-Up and replacement Event - Clinical Cardiac forms
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Phone Call Follow-Up.xml
Labels: tested, urgent

#1646 [Misc] Fix SPARC questionnaire csv import
  Utilities/FormImport/import.py
  Utilities/JSON-to-XML/json_to_xml.py
Labels: tested, Merge me!

#1665 [misc] We don't really use logback-classic
  pom.xml
Labels: tested, easy to review
