Repository data-team-uhn/cards, pull requests merged in 2023-06, with the labels that each got.

#1520 [misc] Docker Improvements
  Utilities/Packaging/Docker/build_self_contained.sh
  Utilities/SecurityScanning/build_package_listing_docker_image.sh
  distribution/Dockerfile
Labels: easy to review, low risk

#1471 CARDS-2211 - Patient portal, token auth: a welcome message is visible for a time that is too short to read it before loading the assigned surveys are displayed
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, Merge me!, easy to review

#1521 CARDS-2251: Proxy images in the compose-cluster environment should be based on Ubuntu 22.04 LTS
  Utilities/ContainerManagement/upgrade_nginx_ubuntu_proxy.sh
  compose-cluster/proxy/Dockerfile
Labels: dependencies, easy to review

#1522 CARDS-2255: PREMS: Death Date and Mychart Status columns are not imported
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
Labels: easy to review

#1530 CARDS-2261: PREMS: Most emergency patients are being discarded during import
  compose-cluster/mssql/processorImportTestSql.sql
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, easy to review

#1526 [misc] Provide instructions about what to do when the libraries needed by the generate_compose_yaml.py script are missing
  compose-cluster/.gitignore
  compose-cluster/generate_compose_yaml.py
  compose-cluster/requirements.txt
Labels: easy to review, testing...

#1532 CARDS-2233: Optimize the performance of the count and pagination servlets
  compose-cluster/mssql/generate_test_YE_sql.py
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested

#1529 [misc] Throw an error when an invalid condition is present in the configuration of a clarity processor
  modules/clarity-integration/pom.xml
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/AbstractConditionalClarityDataProcessor.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/ConfiguredCohortMapper.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/ConfiguredDiscardFilter.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/ConfiguredGenericMapper.java
Labels: easy to review

#1534 CARDS-2266: Quick search never returns when the total number of results is requested and more than 5 results are found
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
Labels: tested, urgent, easy to review

#1452 CARDS-2176: Switch from material-table to material-react-table
  lfs-resources/variants/src/main/frontend/package.json
  lfs-resources/variants/src/main/frontend/src/variantFilesContainer.jsx
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/principals/src/main/frontend/package.json
  modules/principals/src/main/frontend/src/Userboard/Groups/addusertogroupdialogue.jsx
  modules/principals/src/main/frontend/src/Userboard/Groups/groupsmanager.jsx
  modules/principals/src/main/frontend/src/Userboard/Users/usersmanager.jsx
  modules/principals/src/main/frontend/src/Userboard/userboardStyle.jsx
  modules/statistics/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/src/vocabularyTable.jsx
Labels: dependencies, Test me!, large PR

#1542 CARDS-1461: Can't filter for Subjects containing "-" in their ID
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/SubjectFilter.jsx
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
Labels: tested, easy to review

#1537 [misc] Update guava version
  pom.xml
Labels: easy to review

#1536 CARDS-2265: Loading child subjects on the patient chart is too slow
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
Labels: tested, easy to review

#1545 CARDS-2151: Wrong label displayed for Resource answers without a value
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/labels/ResourceLabelProcessor.java
Labels: tested, easy to review

#1543 CARDS-2197: AUDITC interpretation should already take into account the sex when computing the results
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
Labels: tested, easy to review

#1546 CARDS-2270: Manual token generation fails on very large instances
  modules/token-authentication/src/main/resources/SLING-INF/content/libs/cards/Subject/token.html.esp
Labels: easy to review

#1538 CARDS-2267: Speed up the statistics computation
  modules/statistics/src/main/java/io/uhndata/cards/statistics/StatisticQueryServlet.java
Labels: tested

#1541 CARDS-2252: Refactor the ThemeColor config for better extensibility
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
  modules/commons/src/main/resources/SLING-INF/content/libs/cards/Resource/header.html
  modules/commons/src/main/resources/SLING-INF/content/libs/sling/servlet/errorhandler/404.html
  modules/token-authentication/src/main/resources/SLING-INF/content/libs/cards/TokenExpired/html.html
  modules/utils/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
Labels: tested, easy to review

#1544 CARDS-1981: Field filtering on cards4care
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/Questionnaire/updateAllForms.html.esp
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/Questionnaire/updateDateRangeForms.html.esp
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/libs/lfs/Questionnaire/updateSelectedForms.html.esp
Labels: easy to review

#1539 CARDS-2268: Loading table pages far from the first takes longer and longer
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested, easy to review

#1504 CARDS-1220: Odd looking selection dialog appears after canceling creation of subject's parent
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#1535 CARDS-2264: Speed up the quick search
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
  modules/data-entry/src/main/java/io/uhndata/cards/spi/QuickSearchEngine.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormsQuickSearchEngine.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/QuestionnaireQuickSearchEngine.java
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectQuickSearchEngine.java
Labels: tested

#1550 CARDS-2275: Filtering the subject selection dialog by `-` does not return results
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, easy to review

#1549 CARDS-2273: JS error logged when editing certain Heracles questionnaires
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
Labels: tested, easy to review

#1547 CARDS-2271: Heracles change CPET External File form to allow multiple entries per participant
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
Labels: tested, easy to review

#1552 CARDS-2250: Questionnaire designer: adding a question without text leads to a bad state
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested, easy to review

#1553 CARDS-2269: Wrong subject used when creating new forms
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, easy to review
