Repository data-team-uhn/cards, pull requests merged in 2023-01, with the labels that each got.

#1246 [misc] Use a shaded outline istead of a shaded border for focused entries in forms and questionnaires
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, easy to review

#1245 CARDS-1987 - Previously deleted section items are re-shown in the questionnaire editor
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
Labels: tested, easy to review

#1237 CARDS-1973: Heracles Pause/Resume form
  heracles-resources/backend/pom.xml
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/PauseResumeFormEditor.java
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/PauseResumeFormEditorProvider.java
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Pause-Resume Status.xml
  heracles-resources/feature/src/main/features/feature.json
Labels: urgent, Test me!

#1236 CARDS-1982: Add `autocreated` (read only) entry mode
  modules/data-entry/src/main/frontend/src/questionnaire/AutocreatedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ReferenceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: urgent, Test me!

#1250 CARDS-1973: Heracles Pause/Resume form - Typo fix
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Pause-Resume Status.xml
Labels: tested, easy to review

#1244 CARDS-1988 - Re-adding a conditional does not show all the available questions
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: tested, Merge me!, easy to review

#1251 [misc] Upgrade commons-text to 1.10.0
  modules/email-notifications/src/main/features/feature.json
  pom.xml
Labels: tested

#1252 [misc] Fix the class referenced by the logger
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersEditor.java
Labels: easy to review

#1253 CARDS-1990: Patient survey header is too narrow when the survey title is short
  modules/patient-portal/src/main/frontend/src/patient-portal/Header.jsx
Labels: tested, urgent, easy to review

#1256 [misc] Make the "Your Experience" app name title case instead of uppercase
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/AppName.json
Labels: tested, urgent, Merge me!, easy to review

#1255 [misc] Terms of Use: typo fix
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
Labels: tested, urgent, Merge me!, easy to review

#1254 CARDS-1991: Upgrade luxon to avoid vulnerability
  Utilities/Development/ExtensionPointResources/package.json
  lfs-resources/variants/src/main/frontend/package.json
  modules/commons/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/package.json
  modules/patient-portal/src/main/frontend/package.json
  modules/statistics/src/main/frontend/package.json
Labels: dependencies, tested, Merge me!

#1258 CARDS-2003 - Make the PREMs survey titles shorter
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: tested, urgent, easy to review

#1218 CARDS-1938: Implement the /Forms.count API endpoint
  modules/data-entry/src/main/features/feature.json
  modules/data-entry/src/main/java/io/uhndata/cards/CountServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
Labels: Test me!

#1261 CARDS-2006 - As an admin designing a paginated questionnaire, I can specify the pagination style
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
Labels: tested, easy to review, low priotity

#1194 CARDS-1933: PREMs Email notification Scheduling
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitChangeListener.java
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
Labels: tested, urgent, Merge me!

#1247 [Cleanup] JS console errors when rendering some dialogs
  modules/commons/src/main/frontend/src/components/ErrorDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/login/src/main/frontend/src/login/signUpForm.js
  modules/login/src/main/frontend/src/styling/styles.js
  modules/principals/src/main/frontend/src/Userboard/Users/createuserdialogue.jsx
  modules/principals/src/main/frontend/src/Userboard/deleteprincipaldialogue.jsx
  modules/vocabularies/src/main/frontend/src/bioportalApiKey.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyAction.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyActions.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDetails.jsx
Labels: tested, Merge me!, large PR

#1161 CARDS-1881: Periodical export task that serializes new forms as CSVs
  distribution/docker_entry.sh
  modules/pom.xml
  modules/scheduled-csv-export/pom.xml
  modules/scheduled-csv-export/src/main/features/feature.json
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportConfig.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportConfigDefinition.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportEndpoint.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportTask.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ScheduledExport.java
  start_cards.sh
Labels: tested, urgent, Merge me!

#1260 CARDS-2002 - PREMs: display a landing page to the patient before they start filling out their surveys & CARDS-2001 - PREMs: the first question in each survey sounds awkward
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/SurveyInstructionsConfiguration.jsx
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, large PR

#1268 CARDS-2013 - The wrong number of steps is displayed in paginated forms when the pagination variant is `dots` or `text`
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
Labels: tested, easy to review

#1273 CARDS-2007: The patient name appears on the landing page of the PREMs patient portal
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, Test me!

#1274 CARDS-2005: PROMS: Review surveys page does not load
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractFormToStringSerializer.java
Labels: tested

#1264 [code-cleanup] Removed unused methods, updated `ui-extension` java dependencies
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
  modules/statistics/src/main/java/io/uhndata/cards/statistics/StatisticQueryServlet.java
  modules/ui-extension/pom.xml
Labels: Test me!, easy to review

#1267 CARDS-2010 - PREMs: updated surveys for ED and IP short form
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: tested, urgent

#1270 CARDS-2014 - Patient portal: the labels of the buttons that transition to the next survey are too long
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Mood.xml
Labels: tested, easy to review

#1265 CARDS-2011 - Patient portal: add a configuration allowing to skip the review screen when patients fill in surveys
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/SurveyInstructionsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
Labels: tested

#1271 CARDS-2015 - Patient portal: if there's only one questionnaire in the survey, don't display the step indicator (1/1)
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: Test me!, easy to review

#1278 CARDS-2010 - PREMs: updated surveys for IP short form (amendment)
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
Labels: tested, easy to review

#1277 CARDS-2017 / CARDS-2018 - Rename the PatientIdentification configuration to PatientAccess
  modules/patient-portal/src/main/frontend/src/patient-portal/LandingPage.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
  modules/patient-portal/src/main/frontend/webpack.config.js
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/PatientAccessConfigurationImpl.java
  modules/patient-portal/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/PatientAccessConfiguration.json
  modules/patient-portal/src/main/resources/SLING-INF/content/Extensions/AdminDashboard/PatientIdentificationConfiguration.json
  modules/patient-portal/src/main/resources/SLING-INF/content/Extensions/Views/PatientAccessConfiguration.json
  modules/patient-portal/src/main/resources/SLING-INF/content/Extensions/Views/PatientIdentificationConfiguration.json
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/PatientAccess.xml
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/PatientAccess.xml
Labels: urgent, Test me!

#1269 CARDS-2012: Add an option to move only forward through paginated surveys
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
Labels: tested, urgent

#1280 Misc patient portal React warnings
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ToUDialog.jsx
Labels: tested, easy to review

#1281 [misc] Reassigned option values for question oed_1 in ED Survey
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: tested, Merge me!, easy to review

#1285 [misc] Fix typo in the info box on the first page of the CPESIC survey
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
Labels: tested, urgent, Merge me!, easy to review

#1283 CARDS-2025 - As an admin, I can specify if a user answering a vocabulary question can add free-text answers and has access the vocabulary browser
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/resourceQuery/ResourceQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyQuery.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ConceptRecognitionTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ResourceTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/VocabularyMultipleChoiceTest.xml
Labels: tested, urgent, Merge me!

#1284 CARDS-2024 - Update question 48 in Canadian Patient Experiences Survey (long form) to include ontology feature
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
Labels: tested, urgent, Merge me!, easy to review

#1286 CARDS-2023 - PREMs: Rehab survey configuration
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-Rehab.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1291 [misc] Fix for a NumberFormatCustom missing ref Warning
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested

#1204 CARDS-1780: Configure/Implement data import from Clarity
  compose-cluster/generate_compose_yaml.py
  compose-cluster/mssql/.gitignore
  compose-cluster/mssql/generate_test_sql.py
  compose-cluster/mssql/importTestSql.sql
  distribution/docker_entry.sh
  environment.md
  modules/clarity-integration/pom.xml
  modules/clarity-integration/src/main/features/feature.json
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportConfigDefinition.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportEndpoint.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/NightlyClarityImport.java
  modules/clarity-integration/src/main/resources/SLING-INF/nodetypes/clarity-mapping.cnd
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/formSubjectQuestionnaire.json
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjectIdentifier.json
  modules/pom.xml
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
  start_cards.sh
Labels: urgent, Test me!, large PR

#1294 CARDS-2036: Unsubmitted forms for past visits are always deleted
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupScheduler.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupTask.java
Labels: urgent

#1289 CARDS-2030: Add support for configuring the main theme colors (primary, secondary) in each app
  modules/commons/src/main/frontend/src/themePalette.jsx
  modules/commons/src/main/resources/SLING-INF/content/libs/cards/Resource/header.html
  modules/commons/src/main/resources/SLING-INF/content/libs/sling/servlet/errorhandler/404.html
  modules/token-authentication/src/main/resources/SLING-INF/content/libs/cards/TokenExpired/html.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/ThemeColor.json
Labels: tested, Merge me!, easy to review

#1288 CARDS-1962: Prems discharge events import exclusions, CARDS-1963: Prems long-form/short-form survey scheduling [PoC]
  prems-resources/backend/pom.xml
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/FilterEmailConsent.java
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/SendCPESForDepartmentFrequency.java
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
  prems-resources/feature/src/main/features/feature.json
  prems-resources/pom.xml
Labels: tested

#1293 CARDS-2035 - PREMs: All CPESIC questions except the free-entry ones (48_other and 49) should be mandatory
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
Labels: tested, urgent, easy to review

#1295 CARDS-2037: Show some visual indication that the deletion is happening after clicking the Delete button
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
Labels: tested, easy to review

#1292 [misc] PREMs surveys: typo fix in CPESIC title, made paginationVariant `dots` for CPESIC, IP, ED
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: tested, urgent, easy to review
