Repository data-team-uhn/cards, pull requests merged in 2023-02, with the labels that each got.

#1282 CARDS-1375: Add an option to block advancing in a form unless all required fields have been filled out
  modules/commons/src/main/frontend/src/components/MainActionButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
Labels: tested, urgent, Merge me!, large PR

#1303 CARDS-2052 + CARDS-2053: UI fixes for reference resource questions
  modules/data-entry/src/main/frontend/src/questionnaire/AutocreatedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ReferenceTestCopied.xml
Labels: tested, urgent, easy to review

#1275 CARDS-2016: Fix broken email alerts for worrisome submitted answers
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/EmailAlertEventListener.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/EmailFormAlerts.java
Labels: tested, Merge me!

#1307 CARDS-2043 - Create the Survey events questionnaire for recording the information (amendment)
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
Labels: tested, urgent, easy to review

#1306 CARDS-2041: The generate_compose_yaml.py script should support using a singular MongoDB Docker container for data persistence
  compose-cluster/ServerMemorySplitConfig.py
  compose-cluster/generate_compose_yaml.py
Labels: tested

#1179 CARDS-1892 / CARDS-1894 / CARDS-1896 / CARDS-1897 / CARDS-1898 / CARDS-1899: Send notifications to Slack whenever important security updates are available for a CARDS deployment
  Utilities/SecurityScanning/GitHubRepoHandler.py
  Utilities/SecurityScanning/README.md
  Utilities/SecurityScanning/build_maven_package_list.py
  Utilities/SecurityScanning/generate_slack_vulnerability_report_for_host.py
  Utilities/SecurityScanning/github_download_deployment_packages_config.py
  Utilities/SecurityScanning/github_download_docker_related_resource.py
  Utilities/SecurityScanning/github_get_docker_image_digest.py
  Utilities/SecurityScanning/github_publish_os_package_list.py
  Utilities/SecurityScanning/github_publish_scan_report.py
  Utilities/SecurityScanning/list_maven_packages_in_docker_image.sh
  Utilities/SecurityScanning/os_file_management.py
  Utilities/SecurityScanning/post_message_blocks_to_slack.py
  Utilities/SecurityScanning/screenshots/install_os_pkg_app.png
  Utilities/SecurityScanning/slack_vulnerability_report_job.sh
  Utilities/SecurityScanning/trivy-utils/build_docker_image.sh
  Utilities/SecurityScanning/trivy-utils/get_vulnerabilities_for_mvn_pkg.py
  Utilities/SecurityScanning/trivy-utils/scan_maven_package_list.py
  Utilities/SecurityScanning/trivy-utils/scan_remote_maven_list.sh
  Utilities/SecurityScanning/trivy-utils/scan_remote_npm_list.sh
  Utilities/SecurityScanning/trivy-utils/scan_remote_package_list.sh
  Utilities/SecurityScanning/trivy-utils/trivy_to_slack.py
  Utilities/SecurityScanning/trivy-utils/update_trivy_cache.sh
Labels: large PR, low risk

#1315 CARDS-2062 - Prems: Update Terms of Use
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
Labels: tested

#1309 CARDS-2060: Weak SSL ciphers should be disabled in the proxy container whenever the proxy container is operating as an SSL-terminating reverse proxy
  Utilities/Development/scan_nmap_ssl_xml_for_weak_ciphers.py
  compose-cluster/proxy/apache_common_conf/apache_ssl.conf
Labels: tested, urgent, Merge me!

#1310 CARDS-1877: Reset to initial settings in administration pages is broken
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownText.jsx
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/DashboardSettingsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/SurveyInstructionsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ToUConfiguration.jsx
Labels: tested

#1279 CARDS-2017 / CARDS-2019 - Add a `draftLifetime` field to the `Patient Access` configuration
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/api/PatientAccessConfiguration.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/PatientAccessConfigurationImpl.java
Labels: tested, easy to review

#1319 CARDS-2068 - Patient portal: on the start screen, the numbers in front of the surveys look like they should be clicked, but don't react to clicks
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, easy to review

#1322 CARDS-2070 - Patient portal: the "Close" button on the last page is confusing
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, easy to review

#1314 CARDS-2042: Patient portal: add support for recording communication events related to patient surveys
  modules/patient-portal/pom.xml
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentEmailNotificationsFactory.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/GeneralNotificationsTask.java
  modules/permissions/src/main/java/io/uhndata/cards/permissions/internal/QuestionnaireRestrictionPattern.java
  prems-resources/backend/pom.xml
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/surveytracker/SurveyTracker.java
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1321 CARDS-2058 - PREMs: Survey instructions improvements
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
Labels: tested, urgent, easy to review

#1320 CARDS-2069 - Patient portal: add support for an "Affiliation" logo
  modules/patient-portal/src/main/frontend/src/patient-portal/Header.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  prems-resources/clinical-data/src/main/media/SLING-INF/content/libs/cards/resources/media/prems/logo2.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/Media.json
Labels: tested, urgent, easy to review

#1317 CARDS-2065: Add a questionnaire setting to hide answer instructions, CARDS-2066: Reword "This question is mandatory"
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested, urgent, easy to review

#1318 CARDS-2067: Clicking on the grey highlighting of a multiple choice option should have the same effect as clicking on the option text or radio/checkbox
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, urgent, easy to review

#1328 CARDS-2072: Checking "Patients can answer surveys without a personalized link" in Administration > Patient access is not sufficient to enable the identification form
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
Labels: tested, easy to review

#1327 CARDS-1995: Sign out is not working for patients
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/sling/TokenAuthenticationHandler.java
Labels: tested, urgent

#1316 CARDS-2064 - Add support for formatting in the question text
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
Labels: tested, urgent, easy to review

#1329 CARDS-2071 - Patient portal: some error messages displayed to the user are too technical
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: easy to review

#1335 CARDS-2080: Add the option to export a raw CSV header with variable names instead of questions' text
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
Labels: tested

#1334 CARDS-1999: Add the ability to include/exclude fields when exporting as CSV
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/FormAnswerFilterProcessor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireFilterProcessor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/TreeGraph.java
Labels: tested

#1338 CARDS-2057 - PREMs: UX polishing
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, easy to review

#1339 CARDS-2082: Mark all visit forms as submitted when the patient submits the survey
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/SubmissionListener.java
Labels: tested

#1333 CARDS-2075: The PrintHeader UIX and JSX code are fetched every time the form menu is opened or closed
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
Labels: tested

#1342 [misc] In patient portal, find the clinic answer in the Visit information form json by node name, not by question text
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: easy to review

#1323 CARDS-2056: PREMs Survey updates
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/ReminderNotification/bodyTemplate.txt
Labels: tested, urgent

#1298 CARDS-2020: Implement a scheduled task that clears the patient's answer values from unsubmitted drafts that the patient hasn't updated for longer than `PatientAccess.draftLifetime` days
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupScheduler.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupTask.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/PatientAccessConfigurationImpl.java
  modules/versioning/pom.xml
  modules/versioning/src/main/java/io/uhndata/cards/versioning/LastModifiedEditor.java
  modules/versioning/src/main/java/io/uhndata/cards/versioning/LastModifiedEditorProvider.java
Labels: tested

#1343 [misc] Remove maxAnswers=1 from *_department reference questions in prems surveys
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
Labels: Test me!

#1336 CARDS-1842: Configure the periodic task to export survey data as csv
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportConfigDefinition.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportEndpoint.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ExportTask.java
  modules/scheduled-csv-export/src/main/java/io/uhndata/cards/scheduledcsvexport/ScheduledExport.java
  prems-resources/feature/src/main/features/feature.json
Labels: tested

#1345 CARDS-2083: Update importTestSql.sql and generate_test_sql.py so that they can be used with the updated Clarity column names
  compose-cluster/mssql/generate_test_sql.py
  compose-cluster/mssql/importTestSql.sql
Labels: tested, urgent, Merge me!, low risk

#1346 CARDS-2087 - Patient portal: the "Next survey" and "Review" buttons look uncomfortable on narrow screens in paginated surveys with paginationVariant = progress
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent, easy to review

#1340 CARDS-2038: The Clarity Importer should increment /Metrics/ImportedAppointments by the total number of created visits
  modules/clarity-integration/pom.xml
  modules/clarity-integration/src/main/features/feature.json
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
  modules/clarity-integration/src/main/resources/SLING-INF/nodetypes/clarity-mapping.cnd
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
Labels: urgent

#1349 CARDS-2088 - Patient portal: the "Submit my answers" button can be easily missed on the review screen
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, easy to review

#1348 CARDS-1855: Upgrade checkstyle
  modules/data-entry/src/main/java/io/uhndata/cards/DataImportServlet.java
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentEmailNotificationsFactory.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/EmailFormAlerts.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/submissioncounter/SubmissionCounter.java
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/VocabularyIndexerServlet.java
  pom.xml
Labels: dependencies, tested

#1347 [misc] Re-enable the dependency check plugin
  heracles-resources/backend/pom.xml
  modules/data-entry/pom.xml
  modules/data-model/forms/impl/pom.xml
  modules/email-notifications/pom.xml
  modules/form-completion-status/pom.xml
  modules/metrics/pom.xml
  modules/patient-portal/pom.xml
  modules/utils/pom.xml
  modules/webhook-backup/pom.xml
  pom.xml
  proms-resources/backend/pom.xml
Labels: dependencies, tested

#1344 CARDS-2020: Implement a scheduled task that clears the patient's answer values from unsubmitted drafts that the patient hasn't updated for longer than `PatientAccess.draftLifetime` days
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupTask.java
Labels: Test me!

#1352 CARDS-2092: Make the schema and table name used by Clarity Import configurable
  compose-cluster/generate_compose_yaml.py
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
Labels: urgent, easy to review

#1353 CARDS-2081: Regression: `Surveys completed` does not get set upon completion of the surveys by patient
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitChangeListener.java
Labels: tested, urgent, Merge me!

#1360 CARDS-2098: PREMS: Add support for importing only one visit per event
  compose-cluster/mssql/generate_test_sql.py
  compose-cluster/mssql/processorImportTestSql.sql
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/spi/ClarityDataProcessor.java
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/DiscardDuplicatesFilter.java
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested

#1364 [misc] Fixed format errors in ClarityQuestionMapping.toString
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
Labels: urgent

#1355 CARDS-1962: Prems discharge events import exclusions - redefine "short stay"
  prems-resources/feature/src/main/features/feature.json
Labels: urgent

#1363 CARDS-2100: Use the encounter identifier as the visit subject identifier
  compose-cluster/mssql/processorImportTestSql.sql
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
Labels: tested, urgent

#1370 [misc] The default survey page looks unbalanced on narrow screens due to logo size
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
Labels: urgent, easy to review

#1372 [misc] Terms of Use dialog: long links cause horizontal scrollbar on narrow screens
  modules/patient-portal/src/main/frontend/src/patient-portal/ToUDialog.jsx
Labels: urgent, easy to review

#1379 CARDS-2108: "Hide answer instructions" setting not working in releases
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: urgent, Test me!, easy to review

#1380 CARDS-2109 - Patient portal: the "Submit my answers" button should show some indication that submission is in progress once pressed
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: urgent, Test me!, easy to review

#1388 CARDS-2123: Bad data in one form can prevent all further changes from being imported
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
Labels: tested, urgent
