Repository data-team-uhn/cards, pull requests merged in 2023-04, with the labels that each got.

#1446 CARDS-2173: Upgrade the version of Alpine Linux used by CARDS Docker container images
  compose-cluster/cleanup.sh
  compose-cluster/percona_encryption_at_rest.md
  distribution/Dockerfile
  distribution/make_filled_m2.sh
Labels: dependencies

#1433 CARDS-2170: Inconsistency in the Form delete dialog; CARDS-2169: Inconsistent wording in the subject delete dialog
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested, easy to review

#1451 CARDS-2177: In the Heracles S3 exporter, the "Failed to perform the nightly export" message should be logged for all types of failures that occur during the data export task
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/export/ExportTask.java
Labels: tested, easy to review

#1449 CARDS-2179: HERACLES: Pause/Resume forms randomly show up without autocreated answers
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/AnswerFormEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/CreateMissingAnswersEditor.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/AnswerCompletionStatusEditor.java
Labels: tested, urgent

#1457 CARDS-2183: In the Cards4CaRe S3 exporter, the "Failed to perform the nightly export" message should be logged for all types of failures that occur during the data export task
  cardiac-rehab-resources/backend/src/main/java/ca/sickkids/ccm/lfs/cardiacrehab/internal/export/ExportTask.java
Labels: easy to review

#1448 CARDS-2178: Survey Events CSV export has paths instead of labels for the assigned survey
  prems-resources/feature/src/main/features/feature.json
Labels: tested

#1456 CARDS-2185: "Unclosed ResourceResolver" warnings logged when re-deploying patient-portal
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/submissioncounter/SubmissionCounter.java
Labels: easy to review

#1442 Upgrade libthrift from 0.13.0 to 0.14.1
  modules/data-entry/src/main/features/feature.json
  modules/vocabularies/src/main/features/feature.json
Labels: dependencies

#1405 CARDS-1768: Refactoring/UX improvement: replace long 'Select's with Autocomplete
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/SubjectFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/VariableAutocomplete.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/tableStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireAutocomplete.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ConditionalValueInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ReferenceInput.jsx
Labels: urgent, large PR

#1445 Upgrade woodstox-core from 5.3.0 to 5.4.0
  modules/saml-support/src/main/features/base.json
Labels: dependencies

#1447 Reduce webpack file sizes
  Utilities/Development/ExtensionPointResources/package.json
  aggregated-frontend/src/main/frontend/webpack.config-template.js
  aggregated-frontend/src/main/frontend/webpack_script.py
  lfs-resources/variants/pom.xml
  lfs-resources/variants/src/main/frontend/package.json
  lfs-resources/variants/src/main/frontend/webpack.config.js
  lfs-resources/variants/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/commons/src/main/frontend/package.json
  modules/commons/src/main/frontend/src/assetManager.jsx
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
  modules/data-entry/pom.xml
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectIdentifier.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/frontend/webpack.config.js
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/demo-banner/src/main/frontend/package.json
  modules/downtime-warning-banner/pom.xml
  modules/downtime-warning-banner/src/main/frontend/package.json
  modules/downtime-warning-banner/src/main/frontend/webpack.config.js
  modules/downtime-warning-banner/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/homepage/pom.xml
  modules/homepage/src/main/frontend/package.json
  modules/homepage/src/main/frontend/src/themePage/EntityIdentifier.jsx
  modules/homepage/src/main/frontend/webpack.config.js
  modules/homepage/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/login/src/main/frontend/package.json
  modules/page-start-header/src/main/frontend/package.json
  modules/page-start-header/src/main/frontend/webpack.config.js
  modules/patient-portal/pom.xml
  modules/patient-portal/src/main/frontend/package.json
  modules/patient-portal/src/main/frontend/webpack.config.js
  modules/patient-portal/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/pedigree/src/main/frontend/package.json
  modules/permissions-trusted/src/main/frontend/package.json
  modules/principals/src/main/frontend/package.json
  modules/statistics/pom.xml
  modules/statistics/src/main/frontend/package.json
  modules/statistics/src/main/frontend/webpack.config.js
  modules/statistics/src/main/resources/SLING-INF/content/Statistics/Statistics.json
  modules/statistics/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/token-authentication/src/main/frontend/package.json
  modules/ui-extension/src/main/frontend/package.json
  modules/vocabularies/pom.xml
  modules/vocabularies/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/webpack.config.js
  modules/vocabularies/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
Labels: Merge me!

#1458 CARDS-2188 - Statistics: better chart colors
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
Labels: tested, Merge me!

#1463 CARDS-1882 - PROMs: The audit_sex question in the AUDITC questionnaire should have entryMode: reference
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/AUDITC.xml
Labels: urgent, Test me!, easy to review

#1462 CARDS-2105 - Patient identification page: "Where can I find my MRN?" dialog layout is slightly broken on narrow screens
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
Labels: urgent, Test me!, easy to review

#1466 CARDS-2193: Require completion & hide answer instructions for all PROMs questionnaires
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/GAD7.xml
Labels: urgent, regression

#1467 CARDS-2198: PROMS: Remove the restriction on audit_sex for tokenless access
  proms-resources/feature/src/main/features/feature.json
Labels: urgent, Test me!

#1464 CARDS-2195: Dropdown date selector usability improvements
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
Labels: urgent, Merge me!, Test me!, easy to review

#1459 CARDS-2194: Add support for more advanced formatting for information cards in questionnaires
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Information.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Information-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Information.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: urgent, Test me!, easy to review

#1468 CARDS-1768: Refactoring/UX improvement: replace long Selects with Autocomplete - FIXES
  modules/data-entry/src/main/frontend/src/dataHomepage/VariableAutocomplete.jsx
Labels: Merge me!, Test me!, easy to review

#1474 Maven packages security updates
  .github/actions/install-ci-dependencies/action.yml
  distribution/src/main/features/base.json
  distribution/src/main/features/core/base-configuration.json
  distribution/src/main/features/oak/oak_base.json
  heracles-resources/feature/src/main/features/feature.json
  modules/data-entry/src/main/features/feature.json
  modules/email-notifications/src/main/features/feature.json
  modules/metrics/src/main/features/feature.json
  modules/ui-extension/src/main/features/feature.json
  modules/vocabularies/src/main/features/feature.json
  modules/webhook-backup/src/main/features/feature.json
  pom.xml
Labels: dependencies

#1477 CARDS-2213: Docker Compose environments generated by generate_compose_yaml.py should assign the unless-stopped restart policy to services
  compose-cluster/generate_compose_yaml.py
Labels: easy to review

#1470 CARDS-2210: If patient authentication with dob and mrn/hc is required all attempts to use a token link will result in redirection to `Expired.html`
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
Labels: tested, urgent, easy to review
