Repository data-team-uhn/cards, pull requests merged in 2023-10, with the labels that each got.

#1610 CARDS-2363 - PREMs: "Left triage" discharge disposition should disqualify patients from receiving the ED or CPES survey
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review

#1612 CARDS-2364: All service user rights are broken
  distribution/src/main/features/oak/oak_base.json
  heracles-resources/feature/src/main/features/feature.json
  modules/error-tracking/src/main/features/feature-repoinit.txt
  modules/metrics/src/main/features/feature-repoinit.txt
Labels: urgent, Test me!

#1613 CARDS-2368: Email invitations to complete surveys containing the IC questionnaire should come from the IC email address
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/ROOT.json
Labels: easy to review

#1611 CARDS-2344: Incorrect answer alignment in the matrix sections when in view mode
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Test me!, easy to review

#1616 [misc] cards:Conditional is marked as orderable twice
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: easy to review

#1617 CARDS-2372: Add support for data migrators
  distribution/src/main/features/core/migrators.json
  heracles-resources/backend/pom.xml
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/migrators/Cards2336BikeMigration.java
  modules/data-model/migrators/pom.xml
  modules/data-model/migrators/src/main/features/feature.json
  modules/data-model/migrators/src/main/java/io/uhndata/cards/migrators/internal/DataMigratorManager.java
  modules/data-model/migrators/src/main/java/io/uhndata/cards/migrators/internal/DataMigratorUtils.java
  modules/data-model/migrators/src/main/java/io/uhndata/cards/migrators/internal/UpdatePreviousVersionMigrator.java
  modules/data-model/migrators/src/main/java/io/uhndata/cards/migrators/spi/DataMigrator.java
  modules/data-model/pom.xml
  pom.xml
Labels: tested

#1618 CARDS-2389: /opt/cards/.cards-data in the cardsinitial Docker container is (incorrectly) no longer being bound to the local ./SLING directory
  compose-cluster/generate_compose_yaml.py
Labels: easy to review

#1614 CARDS-2369: The validation regexp specified in the questionnaire designer for text questions is not taken into account
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TextQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/RegExpValueValidator.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/RegExpTest.xml
Labels: tested, urgent

#1620 CARDS-2392: Switch YE clarity import to pull data from new table PatientActivity_data_for_PtExpSurveyApp
  compose-cluster/generate_compose_yaml.py
  compose-cluster/mssql/cards-2134-test.sql
  compose-cluster/mssql/generate_test_YE_sql.py
  compose-cluster/mssql/importTestSql.sql
  compose-cluster/mssql/processorImportTestSql.sql
  compose-cluster/mssql/visitFilterImportTestSql1.sql
  compose-cluster/mssql/visitFilterImportTestSql2.sql
  environment.md
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/MychartEmailConsentMapper.java
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1608 CARDS-2362: New Integrated Care Survey questions
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/IC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/IPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/IC.json
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1622 CARDS-2401: RecentVisitDiscardFilter should allow reimporting the same visit
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/RecentVisitDiscardFilter.java
Labels: easy to review

#1624 CARDS-2403: The yarn.lock file for aggregated-frontend should be checked into git
  .gitignore
  aggregated-frontend/src/main/frontend/yarn.lock
Labels: question, dependencies, urgent, easy to review
