Repository data-team-uhn/cards, pull requests merged in 2023-07, with the labels that each got.

#1557 CARDS-2280: Add tooltip for Admin's questionnaire export button
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
Labels: tested, easy to review

#1555 CARDS-2272: SlackNotificationsTask and NightlySlackNotifications should be moved into their own CARDS module
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
  modules/patient-portal/pom.xml
  modules/patient-portal/src/main/features/feature.json
  modules/pom.xml
  modules/slack-notifications/pom.xml
  modules/slack-notifications/src/main/features/feature.json
  modules/slack-notifications/src/main/java/io/uhndata/cards/slacknotifications/ScheduledSlackNotifications.java
  modules/slack-notifications/src/main/java/io/uhndata/cards/slacknotifications/SlackNotificationsTask.java
  start_cards.sh
Labels: easy to review

#1554 CARDS-2277: Unable to create a new tumor region subject in some cases; CARDS-2284: Subject creation takes a wrong path when trying to create an already existing parent subject
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, easy to review

#1564 CARDS-2293: Pagination is broken on patient selector dialog
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Test me!, easy to review

#1558 CARDS-2104: Resource question dropdown menu keeps moving when selecting options
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, easy to review

#1568 [misc] Update io.netty version
  heracles-resources/feature/src/main/features/feature.json
  modules/webhook-backup/src/main/features/feature.json
Labels: easy to review

#1432 CARDS-2159: Principals pagination servlet should support also listing service users
  modules/principals/src/main/java/io/uhndata/cards/principals/PrincipalsServlet.java
Labels: tested, easy to review, java

#1570 CARDS-2299: Non-admin users cannot add user filters for any users other than themselves
  distribution/src/main/features/base-repoinit.txt
Labels: tested

#1571 [code-cleanup] Removed unused imports
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/VocabularyFilter.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireAutocomplete.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectIdentifier.jsx
Labels: easy to review
