Repository data-team-uhn/cards, pull requests merged in 2023-05, with the labels that each got.

#1454 CARDS-2137: Query servlet is too slow; CARDS-2182: Query servlet sometimes outputs the same node multiple times
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
  modules/data-entry/src/main/java/io/uhndata/cards/spi/SearchUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormsQuickSearchEngine.java
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectQuickSearchEngine.java
Labels: tested, Merge me!

#1480 CARDS-2216: HERACLES: Remove maxPerSubject=6 restrictions
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6MWT.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
Labels: tested, easy to review

#1481 CARDS-2217: Display the clinic label in the Visit Information form
  modules/patient-portal/src/main/resources/SLING-INF/content/Questionnaires/Visit information.xml
Labels: tested, easy to review

#1479 CARDS-2205: Improve the maximum number of forms per subject handling in the form creation dialog
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/MaxPerSubjectTest.xml
Labels: tested, Merge me!, easy to review

#1478 CARDS-2214: PROMs Smoking Cessation survey: clarify that the CAMH program is self-referral
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/SC.xml
Labels: tested, Merge me!, easy to review

#1486 [misc] Removed duplicate dataType property
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/VocabularyMultipleChoiceTest.xml
Labels: easy to review, low risk, low priority

#1487 [misc] Trivy security scanning hostname lookup failure fix
  Utilities/SecurityScanning/trivy-utils/update_trivy_cache.sh
Labels: easy to review, low risk

#1491 [misc] Trivy security scanning hostname lookup failure fix
  Utilities/SecurityScanning/slack_vulnerability_report_job.sh
Labels: easy to review, low risk

#1494 CARDS-2231: Add support for the --behind_ssl_termination flag to generate_compose_yaml.py
  compose-cluster/generate_compose_yaml.py
  compose-cluster/proxy/terminated-ssl_000-default.conf
  compose-cluster/proxy/terminated-ssl_saml_000-default.conf
Labels: urgent, easy to review

#1490 CARDS-2228: Update wording and links on PROMs summary page
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Cardio.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
Labels: tested, urgent

#1498 [misc] Updated the department name in the title of the Cardio survey screen
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Cardio.xml
Labels: tested, easy to review

#1496 CARDS-2232: Heracles change Cardiac Rehab Indication question to multi-select
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Baseline Health Information.xml
Labels: tested, Merge me!, easy to review

#1502 [misc] Disable email address validation in PROMS
  proms-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review

#1497 CARDS-2212 - Your Experience: logos are not displayed properly on iPhone mobile view
  modules/commons/src/main/frontend/src/components/Logo.jsx
Labels: Test me!, easy to review

#1500 CARDS-2235: Add a custom generic error handler
  modules/commons/pom.xml
  modules/commons/src/main/frontend/src/components/GenericErrorPage.js
  modules/commons/src/main/frontend/webpack.config.js
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
Labels: tested

#1499 CARDS-2234: Disable the default Sling HTML and Text output for nodes without a custom render
  distribution/src/main/features/core/base-configuration.json
Labels: tested

#1505 [misc] Remove Mood clinic reference from pom.xml
  proms-resources/clinical-data/pom.xml
Labels: tested, easy to review

#1508 CARDS-2241: Unable to upgrade to 9.11 due to referenced question
  proms-resources/clinical-data/pom.xml
Labels: tested, urgent, easy to review

#1509 CARDS-2236: Bare JSON should have a simpler representation of a form's related subjects
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/BareFormProcessor.java
Labels: tested, easy to review

#1507 CARDS-2239: Create a Python script for exporting questionnaire schemas
  Utilities/Administration/export_schemas.py
Labels: tested, easy to review, low risk

#1514 CARDS-2241: Unable to upgrade to 9.11 due to referenced question
  proms-resources/clinical-data/pom.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/SurveyNoOverwrite/Cardio.xml
Labels: tested, urgent, easy to review

#1512 [misc] CopyAnswers logs excessively in proms mode
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractAnswerCopyProcessor.java
Labels: Test me!, easy to review

#1511 [misc] Fixed an error in the error handler when an error code is not set
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
Labels: easy to review

#1515 CARDS-2243: Improve the performance of the clinic dashboard tables
  modules/patient-portal/src/main/frontend/src/patient-portal/ClinicForms.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ClinicVisits.jsx
Labels: tested, urgent, easy to review

#1510 CARDS-2242: Optimize the unsubmitted forms restriction for faster execution
  proms-resources/permissions/pom.xml
  proms-resources/permissions/src/main/java/io/uhndata/cards/proms/permissions/UnsubmittedFormsRestrictionFactory.java
  proms-resources/permissions/src/main/java/io/uhndata/cards/proms/permissions/UnsubmittedFormsRestrictionPattern.java
Labels: urgent, Test me!

#1516 CARDS-2244: Use TG-PMCC CARDIAC CLINICS as the clinic to import
  compose-cluster/mssql/generate_test_proms_sql.py
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/ConfiguredGenericMapper.java
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  proms-resources/feature/src/main/features/feature.json
  proms-resources/frontend/src/main/resources/SLING-INF/content/Extensions/Sidebar/PMCC-ACHD.json
Labels: tested, urgent

#1513 CARDS-2240: Clear the cards_auth_token cookie when landing on the Survey Patient Portal page
  Utilities/Development/test_proxy_configuration.py
  compose-cluster/proxy/apache_common_conf/apache_common.conf
Labels: help wanted, urgent, Test me!, easy to review, testing...

#1518 [misc] Reduce the dicom dictionary filesize under 500k to remove webpack warning
  modules/data-entry/src/main/frontend/src/dicom/dicomDataDictionary.js
Labels: easy to review

#1493 CARDS-2222: Create a script which scans the current state of the local CARDS repository for Maven and NPM/Yarn vulnerabilities
  Utilities/SecurityScanning/scan_this_repository.sh
Labels: easy to review, low risk

#1517 CARDS-2204: Patient portal access tokens are slow to use on large instances
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/TokenManagerImpl.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/oak/CardsTokenProvider.java
Labels: tested, urgent

#1519 CARDS-2247: Custom error page fails to render in projects other than prems - QUICK FIX
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
Labels: tested, urgent, Merge me!, easy to review

#1476 Maven packages security updates (stable-0.8.x)
  cardiac-rehab-resources/backend/pom.xml
  cardiac-rehab-resources/backend/src/main/provisioning/model.txt
  compose-cluster/load_apple_cert.sh
  distribution/Dockerfile
  distribution/src/main/provisioning/10-sling-base.txt
  distribution/src/main/provisioning/20-sling-models-jacksonexporter.txt
  distribution/src/main/provisioning/50-sling-webconsole.txt
  modules/utils/pom.xml
  modules/vocabularies/pom.xml
  modules/vocabularies/src/main/provisioning/model.txt
Labels: dependencies, tested
