Repository data-team-uhn/cards, pull requests merged in 2023-08, with the labels that each got.

#1572 CARDS-2302: As a patient, I cannot edit surveys I have already submitted
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, easy to review

#1548 CARDS-1744: Filter operator '<>' does not pick up blank values; CARDS-1756: Proms mode's Visit Information/Time filters are not working
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested, Merge me!, easy to review

#1577 CARDS-2291: Inconsistent letter case in the edit and delete table action tooltips
  modules/data-entry/src/main/frontend/src/dataHomepage/EditButton.jsx
Labels: tested

#1575 CARDS-2305: Add configuration for `reply-to` in patient notification emails
  Utilities/Postfix-Docker/README.md
  environment.md
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTemplate.java
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailUtils.java
Labels: tested, urgent, Merge me!

#1578 CARDS-2315: Exporting and re-importing Smoking Cessation form fails
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
Labels: tested, easy to review

#1533 CARDS-2262: Publish the currently running kernel version for the VM so that vulnerabilities in non-running kernels can be safely ignored
  Utilities/SecurityScanning/GitHubRepoHandler.py
  Utilities/SecurityScanning/README.md
  Utilities/SecurityScanning/github_get_os_kernel_version.py
  Utilities/SecurityScanning/github_publish_os_kernel_version.py
  Utilities/SecurityScanning/screenshots/install_os_pkg_app.png
  Utilities/SecurityScanning/trivy-utils/scan_remote_package_list.sh
  Utilities/SecurityScanning/trivy-utils/trivy_to_slack.py
Labels: low risk

#1444 CARDS-2171: Refactor FilterServlet to provide all the information needed by Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/FilterServlet.java
Labels: tested, Merge me!

#1579 CARDS-2298: Last modified by patient field never gets updated for completed/submitted surveys
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/SubmissionListener.java
  modules/versioning/src/main/java/io/uhndata/cards/versioning/LastModifiedEditor.java
Labels: Test me!

#1576 CARDS-2307: Listener that observes when the clinic field of the Visit information form changes and automatically adds any missing surveys to the visit subject
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitChangeListener.java
Labels: tested

#1506 CARDS-1190: As a user, I can filter forms by "Created by", "Last modified by", "Last modification date" in the dashboard and on the Forms page
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/UserFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/FilterServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/downtime-warning-banner/src/main/frontend/package.json
Labels: tested

#1485 CARDS-2186: Statistics: add a configuration to bundle null and false together for boolean variables
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
  modules/statistics/src/main/frontend/src/Statistics/Statistics.json
  modules/statistics/src/main/frontend/src/Statistics/statisticsStyle.jsx
Labels: tested

#1580 CARDS-2323: Embedded view of subject charts and forms, without navigation elements
  distribution/src/main/features/core/cards.json
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
  modules/embedded-view/pom.xml
  modules/embedded-view/src/main/frontend/package.json
  modules/embedded-view/src/main/frontend/src/embeddedView/index.jsx
  modules/embedded-view/src/main/frontend/webpack.config.js
  modules/embedded-view/src/main/resources/SLING-INF/content/embedded.json
  modules/embedded-view/src/main/resources/SLING-INF/content/libs/cards/EmbeddedHomepage/html.GET.html
  modules/embedded-view/src/main/resources/SLING-INF/nodetypes/embedded-homepage.cnd
  modules/pom.xml
Labels: urgent, Test me!

#1562 CARDS-2286: Allow to configure token life time for each survey
  modules/patient-portal/src/main/frontend/src/patient-portal/Clinics-hints.json
  modules/patient-portal/src/main/frontend/src/patient-portal/Clinics.json
  modules/patient-portal/src/main/frontend/src/patient-portal/Clinics.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ClinicsServlet.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/api/PatientAccessConfiguration.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/EmailAlertEventListener.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/PatientAccessConfigurationImpl.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupTask.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/surveytracker/SurveyTracker.java
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
  modules/token-authentication/src/main/resources/SLING-INF/content/libs/cards/Subject/token.html.esp
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/PatientAccess.xml
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/PatientAccess.xml
Labels: tested, urgent, testing...
