Repository data-team-uhn/cards, pull requests merged in 2023-03, with the labels that each got.

#1394 CARDS-2129: Patient portal: the process of emailing survey links to patients is too slow
  compose-cluster/mssql/generate_test_sql.py
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/AnswerFormEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/AnswerFormEditorProvider.java
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
  modules/patient-portal/src/main/frontend/src/patient-portal/ClinicForms.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ClinicVisits.jsx
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupTask.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupTask.java
Labels: tested, urgent, Merge me!

#1389 CARDS-2127: Reusable Logo component; CARDS-2125: Affiliation logo on the login page; CARDS-2126: Affiliation logo on error pages
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
  modules/commons/src/main/frontend/src/components/Logo.jsx
  modules/login/src/main/frontend/src/login/loginMainComponent.js
  modules/login/src/main/frontend/src/styling/styles.js
  modules/patient-portal/src/main/frontend/src/patient-portal/Header.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/LandingPage.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/unsubscribe.jsx
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/conf/Media.json
Labels: tested, urgent, testing...

#1393 CARDS-2132 - PREMs: line about about supported browsers in the email keeps getting missed by recepients
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/mailTemplates/bodyTemplate.header.html
Labels: tested, urgent, easy to review

#1367 CARDS-2091: Discard PREMs visits with recent survey events
  compose-cluster/mssql/visitFilterImportTestSql1.sql
  compose-cluster/mssql/visitFilterImportTestSql2.sql
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/RecentVisitDiscardFilter.java
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1398 CARDS-2136: When importing lots of data, some Survey Events forms are not created
  distribution/src/main/features/base.json
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/surveytracker/SurveyTracker.java
Labels: urgent, easy to review

#1402 CARDS-2134: Fix performance metrics generated by Cards4PREMs
  compose-cluster/mssql/cards-2134-test.sql
  modules/patient-portal/src/main/features/feature.json
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/slacknotifications/SlackNotificationsTask.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/submissioncounter/SubmissionCounter.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/submissioncounter/SubmissionEventListener.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent

#1386 CARDS-1709: Enable administrators to export all patient data stored in specific questionnaire in csv format
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: Test me!, testing...

#1362 CARDS-2099: Console warning when deleting form
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
Labels: tested, easy to review

#1361 CARDS-2034: Console warning when editing prems Visit Information's Provider question
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, easy to review

#1406 CARDS-2144: PREMS: Import data from 7 days ago to have more stable events
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportConfigDefinition.java
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/NightlyClarityImport.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent

#1408 CARDS-2141: The "Token Expired" page should display the affiliation logo when enabled
  modules/token-authentication/src/main/frontend/src/tokenAuthentication/TokenExpired.jsx
Labels: Test me!, easy to review

#1262 [improvement] Dependencies update
  lfs-resources/variants/src/main/frontend/package.json
  modules/commons/src/main/frontend/package.json
  modules/commons/src/main/frontend/src/components/404.js
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
  modules/commons/src/main/frontend/src/components/dragAndDrop.jsx
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/demo-banner/src/main/frontend/package.json
  modules/downtime-warning-banner/src/main/frontend/package.json
  modules/homepage/src/main/frontend/package.json
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/login/src/main/frontend/package.json
  modules/login/src/main/frontend/src/login/loginMain.js
  modules/page-start-header/src/main/frontend/package.json
  modules/patient-portal/src/main/frontend/package.json
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/unsubscribe.jsx
  modules/pedigree/src/main/frontend/package.json
  modules/permissions-trusted/src/main/frontend/package.json
  modules/principals/src/main/frontend/package.json
  modules/statistics/src/main/frontend/package.json
  modules/token-authentication/src/main/frontend/package.json
  modules/token-authentication/src/main/frontend/src/tokenAuthentication/TokenExpired.jsx
  modules/ui-extension/src/main/frontend/package.json
  modules/vocabularies/src/main/frontend/package.json
Labels: dependencies, tested, urgent

#1401 [misc] Use the system timezone in docker-compose
  compose-cluster/generate_compose_yaml.py
Labels: tested

#1410 CARDS-2145: On large instances, statistics are too slow or fail to load
  modules/statistics/pom.xml
  modules/statistics/src/main/java/io/uhndata/cards/statistics/StatisticQueryServlet.java
Labels: easy to review

#1404 CARDS-2142: CSV export: Selecting only questions inside sections as the including filter doesn't output any questions at all
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireFilterProcessor.java
Labels: tested, Merge me!

#1375 CARDS-2106: Question matrix sub-questions should support text formatting
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionMatrixEntry.json
Labels: tested, Merge me!, easy to review

#1414 CARDS-1908: Updates to Heracles questionnaires
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
Labels: tested, easy to review

#1419 CARDS-2152: Add support for a modified by filter for the .data processor
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/DataProcessor.java
Labels: tested, Merge me!, low risk

#1420 CARDS-2110: When opening Select a questionnaire dialog, move focus to the search
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
Labels: tested, easy to review

#1422 CARDS-2160: When opening Select a subject dialog, move focus to the search bar
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: Test me!, easy to review

#1423 CARDS-1275: Clicking on the description of checkbox and radio should select the option
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, easy to review

#1425 CARDS-2161: Accessing the patient portal with a valid token for a deleted subject gets the UI stuck loading
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
Labels: tested, easy to review

#1390 [misc] Enable stats in prems
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/CPES-Overall.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/ED-Overall.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/IP-Overall.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/Rehab-Overall.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/Surveys.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/Unsubscribed.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested, easy to review

#1428 CARDS-2165: Statistics tables display question marks instead of non-ASCII characters
  modules/statistics/src/main/java/io/uhndata/cards/statistics/StatisticQueryServlet.java
Labels: Merge me!

#1426 [misc] Remove hardcoded admin credentials in Administration/Groups table loading code
  modules/principals/src/main/frontend/src/Userboard/principalsContainer.jsx
Labels: Merge me!

#1431 CARDS-2073: Doubled words in subject delete dialogs
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: Test me!, easy to review

#1435 CARDS-1846: Proms related Visit infromation filters are not working properly
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/BooleanFilter.jsx
Labels: Test me!, easy to review

#1438 Upgrade jackson.version from 2.13.2 to 2.13.5
  pom.xml
Labels: dependencies

#1440 Upgrade commons-fileupload from 1.4 to 1.5
  distribution/src/main/features/base.json
Labels: dependencies

#1441 YourExperience config updates
  prems-resources/feature/src/main/features/feature.json
Labels: urgent

#1443 CARDS-2174: NullPointerException in UnsubscribedFilter prevents importing Clarity data
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/UnsubscribedFilter.java
Labels: urgent

#1439 CARDS-1578: Usability improvements to the dropdown date component
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
Labels: Merge me!, Test me!
