Repository data-team-uhn/cards, pull requests merged in 2023-09, with the labels that each got.

#1584 CARDS-2303 / CARDS-2309 : When importing data from Clarity, if the fields Status [FLO 44189] and Patient Eligibility [FLO 44190] are "New Patient" and "Enrolled", then the `status` answer in the Visit information should be set to `in-progress` instead of `discharged`
  compose-cluster/mssql/generate_test_YE_sql.py
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityMapping.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, Merge me!

#1589 CARDS-2338: Put back the breadcrumb on the Patient chart to enable navigation to the previous hierarchy level - Patients page
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectIdentifier.jsx
Labels: tested, Merge me!, easy to review

#1587 [misc] Optimize a query by using the correct node type
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupTask.java
Labels: Merge me!, easy to review

#1582 CARDS-2328: Heracles - update Participant Status question with new answer options
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: tested, Merge me!, easy to review

#1583 CARDS-2329 / CARDS-2330 - Heracles add a new question to the CPET Interpretation Form & update cpet_prot field answer options
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET Interpretation.xml
Labels: tested, Merge me!, easy to review

#1591 [misc] DraftsAnswersCleanupTask.java checkstyle fix
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/DraftsAnswersCleanupTask.java
Labels: easy to review

#1595 CARDS-2350: Heracles - add new file upload field to CPET: External File form
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPET - External File.xml
Labels: Test me!, easy to review

#1593 [misc] Update the SHA256 hash of the samlKeystore.p12 file used for the Cloud-IAM SAML demo
  Utilities/Administration/SAML/cloud-iam_demo_samlKeystore.p12.sha256sum
  compose-cluster/CloudIAMdemoKeystoreSha256Property.py
Labels: easy to review

#1586 CARDS-2332: Add automatic saving and checkin of forms after a period of inactivity
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SessionExpiryWarningModal.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/index.jsx
Labels: tested, Merge me!

#1585 CARDS-2311: Add new Integrated Care clinics setup (including surveys and email templates)
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTemplate.java
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-EDIC.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-EDIPIC.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-IC.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/UHN-IPIC.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/IC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/IPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/IC-Logo.png
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/IC.json
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, Test me!

#1597 CARDS-2310: Add a backgroud job that updates Visit information form to Integrated Care "clinic" where applicable
  prems-resources/backend/pom.xml
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/integratedcare/IntegratedCareSwitchingScheduler.java
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/integratedcare/IntegratedCareSwitchingTask.java
  prems-resources/feature/src/main/features/feature.json
Labels: tested

#1181 CARDS-1904: Reference questions: add a listener that captures the changes to the source answer and updates the copied answer
  modules/data-entry/src/main/features/feature.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/referenceQuestion.json
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersChangedListener.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersEditor.java
Labels: tested, urgent

#1391 CARDS-2078: Extract a CardsToken interface to publicly expose some details of the token implementation
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/CardsToken.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/TokenManager.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/CardsTokenImpl.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/ExpiredTokensCleanupTask.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/TokenManagerImpl.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/oak/CardsTokenProvider.java
  modules/token-authentication/src/main/java/io/uhndata/cards/auth/token/impl/sling/TokenAuthenticationHandler.java
Labels: tested, low risk

#1600 CARDS-2354: Javascript console errors on pages displaying forms with questions that have no 'text'
  modules/data-entry/src/main/frontend/src/questionnaire/AutocreatedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/BooleanQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ChromosomeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DicomQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ResourceQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TextQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
  modules/data-entry/src/main/frontend/src/resourceQuery/ResourceQuery.jsx
Labels: tested, easy to review

#1581 CARDS-2333: Automatically check in forms that haven't been modified in more than 30 minutes
  distribution/src/main/features/core/cards.json
  distribution/src/main/features/core/versioning.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/surveytracker/SurveyTracker.java
  modules/versioning/pom.xml
  modules/versioning/src/main/features/feature.json
  modules/versioning/src/main/java/io/uhndata/cards/versioning/LastModifiedEditor.java
  modules/versioning/src/main/java/io/uhndata/cards/versioning/StaleFormsCheckinScheduler.java
  modules/versioning/src/main/java/io/uhndata/cards/versioning/StaleFormsCheckinTask.java
Labels: tested

#1604 CARDS-2359: Cannot navigate back to the first page of a livetable
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
Labels: tested, urgent, easy to review

#1596 CARDS-2346: New question type: telephone number
  Utilities/Administration/Backup-To-JSON/restore_json_backup.py
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PhoneQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/java/io/uhndata/cards/DataImportServlet.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/PhoneNumberTest.xml
Labels: tested, Merge me!

#1609 CARDS-2361: All PREMs reminder emails should be sent 7 days apart
  prems-resources/feature/src/main/features/feature.json
Labels: easy to review
