Repository data-team-uhn/cards, pull requests merged in 2023-11, with the labels that each got.

#1627 CARDS-2406: Add Survey Events questions for tracking IC notification emails
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested

#1634 [misc] Bad merge: some new modules are still using the old version format
  modules/data-model/links/api/pom.xml
  modules/data-model/links/impl/pom.xml
  modules/data-model/links/pom.xml
Labels: tested

#1633 CARDS-2406: Add questions for tracking the IC notification emails in the Survey Events forms
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
Labels: tested, urgent, easy to review

#1632 CARDS-2411: Back button is wrongly enabled, leading to WSORD
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
Labels: tested, urgent, easy to review

#1623 CARDS-2382: Correct child node definitions to only list one required child type
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested, easy to review

#1631 CARDS-2404: YourExperience: No patients are assigned to Integrated Care
  compose-cluster/mssql/generate_test_YE_sql.py
Labels: easy to review

#1635 [misc] Make the clarity processor sorting more stable
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/spi/ClarityDataProcessor.java
Labels: easy to review

#1637 [misc] Update the Form's error display to match the current backend response format
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: easy to review

#1639 CARDS-2415 - Statistics dashboard: clicking on a bar in any widget leads to WSORD and javascript console error
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
Labels: tested, easy to review

#1636 CARDS-2413: Prevent overriding forms with stale data
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/utils/src/main/java/io/uhndata/cards/utils/internal/PreventVersionOverrideServletFilter.java
Labels: tested

#1638 CARDS-2414: Editing forms with missing answers creates phantom answer nodes
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: urgent, Merge me!

#1629 CARDS-2409: Filtering the forms table is too slow
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: tested

#1640 [misc] Fix checkstyle issue
  modules/utils/src/main/java/io/uhndata/cards/utils/internal/PreventVersionOverrideServletFilter.java
Labels: urgent

#1643 CARDS-2418: Form data is not saved when leaving the edit screen by clicking away
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, urgent

#1645 [misc] Better wording for displaying the last successful save time in the "Failed to save" error dialog
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: tested, easy to review

#1644 CARDS-2419: Survey intepretation occasionally fails to load
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested

#1650 CARDS-2429: Add support for survey-specific exit screen message
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
Labels: tested, easy to review

#1649 CARDS-2383: Create importable spreadsheet for the new YVM questionnaire
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/YVM.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/YVM.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/YVM.json
Labels: tested, Merge me!
