Repository data-team-uhn/cards, pull requests merged in 2024-03, with the labels that each got.

#1710 Update the IC survey to match the changes from CARDS-2471
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
Labels: tested, urgent, Merge me!, easy to review

#1709 CARDS-2384 - Updates to the YVM survey and clinic configuration
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/YVM.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/ReminderNotification/bodyTemplate.txt
Labels: tested, urgent, Merge me!, easy to review

#1711 CARDS-2490: Narrow down the list of clinics/departments for which we send YVM surveys
  compose-cluster/mssql/generate_test_YVM_sql.py
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, Test me!, testing...

#1712 CARDS-2491: Update Terms of Use for YVM survey
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/TermsOfUse.xml
Labels: tested, urgent, easy to review

#1718 CARDS-2494: Non-matrix sections should not have dataType and min/maxAnswers properties
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested

#1720 CARDS-2442: Include LICENSE and NOTICE files in the generated jars
  pom.xml
Labels: tested

#1719 CARDS-2485: Remove queries on subject.ancestors
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested

#1685 CARDS-2474: Clinic dashboards are too slow on large datasets
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/formSubjectQuestionnaire.json
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjectTypes.json
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
Labels: tested

#1725 CARDS-2497: Filtering forms by date equality doesn't work reliably
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
Labels: tested

#1721 CARDS-2495: Speed up queries involving forms for a specific subject
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/oak%3Aindex/subjects.json
Labels: tested

#1716 CARDS-2054: Auto-created nodes are out of order
  modules/data-entry/src/main/features/feature.json
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/SortChildrenEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/SortChildrenEditorProvider.java
Labels: tested

#1724 CARDS-2496: Update YVM filters and column mapping
  compose-cluster/mssql/generate_test_YVM_sql.py
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityImport/PMH-YVM.xml
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent

#1738 [misc] Prems YVM: update the survey time estimate in the email to match the landing page estimate
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/ReminderNotification/bodyTemplate.txt
Labels: urgent, Test me!, easy to review

#1737 [misc] Prems YVM: small wording update in question 16
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/YVM.xml
Labels: urgent, Test me!, easy to review

#1735 [misc] YVM intro update
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/YVM.xml
Labels: tested, urgent, easy to review

#1734 [misc] Prems emails: make the text in the yellow box easier to read
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/mailTemplates/bodyTemplate.header.html
Labels: urgent, Test me!, easy to review

#1740 [misc] Don't abbreviate the survey expiry month name in the invitation emails
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
Labels: tested, urgent, easy to review, needs rebase

#1728 CARDS-2475: Decimal range field is always marked as invalid
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/MinMaxAnswersValidator.java
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/RangeMinMaxAnswersValidator.java
Labels: tested

#1743 HERACLES-5 / HERACLES-7: Update to existing Physical Assessments form
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Physical Assessments.xml
Labels: tested

#1744 [MISC] Fix importer repeated section condition
  Utilities/FormImport/import.py
Labels: tested

#1746 HERACLES-3 and HERACLES-4: Updated Event Clinical Cardiac and Phone Call Follow-up forms
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Phone Call Follow-Up.xml
Labels: tested, urgent

#1713 SPARC-12: SPARC Form Graphics: Fix black background on Formatted Text Images
  modules/commons/src/main/frontend/src/components/FormattedText.jsx
Labels: easy to review
