Repository data-team-uhn/cards, pull requests merged in 2024-01, with the labels that each got.

#1667 CARDS-2453: Increase the long form survey (CPESIC) percentage to 14% to meet quarterly target
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, easy to review

#1675 CARDS-2467: The s3-export Sling service user should have jcr:read and jcr:write permissions for /Metrics
  modules/s3-export/src/main/features/feature.json
Labels: easy to review

#1672 CARDS-2466: Order of matrix items is not preserved in view mode
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
Labels: tested, urgent, Merge me!, easy to review

#1676 CARDS-2436: QuestionMatrix: the row of option labels should be sticky to the top
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, urgent, Merge me!, easy to review

#1673 CARDS-2445: Wrong flag when missing information on required questions within recurring sections
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormUtilities.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
Labels: tested, urgent, Merge me!

#1681 CARDS-2453: Temporarily increase the long form survey (CPESIC) percentage to 25% until April 1st, to meet quarterly target
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review

#1683 [misc] Upgrade Apache Felix Health Check Webconsole Plugin
  distribution/src/main/features/webconsole.json
Labels: easy to review

#1684 [misc] Upgrade Apache XML Security for Java
  Utilities/Administration/SAML/cloud-iam_demo_samlKeystore.p12.sha256sum
  Utilities/Development/test_proxy_configuration.py
  compose-cluster/CloudIAMdemoKeystoreSha256Property.py
  compose-cluster/generate_compose_yaml.py
  environment.md
  modules/saml-support/src/main/features/base.json
  modules/saml/cloud-iam-demo-saml-ssl/src/main/features/feature.json
  modules/saml/cloud-iam-demo-saml-ssl/src/main/resources/SLING-INF/content/cloud-iam.demo.json
  modules/saml/cloud-iam-demo-saml/src/main/features/feature.json
  modules/saml/cloud-iam-demo-saml/src/main/resources/SLING-INF/content/cloud-iam.demo.json
  start_cards.sh
Labels: easy to review

#1680 CARDS-2449: Update the RecentVisitDiscardFilter to discard visits depending on the clinic/survey
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/internal/RecentVisitDiscardFilter.java
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent
