Repository data-team-uhn/cards, pull requests merged in 2024-09, with the labels that each got.

#1806 CARDS-2576: Reference questions should allow one time copy of answers
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersChangedListener.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ReferenceTestCopied.xml
Labels: tested

#1805 CARDS-2575: Submitted IP/ED forms will be deleted if the clinic switches to Integrated Care
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupScheduler.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupTask.java
Labels: tested, urgent

#1799 CARDS-2549: Support a mix of patient and clinician forms in a survey
  modules/data-model/qsets/api/src/main/java/io/uhndata/cards/qsets/api/QuestionnaireRef.java
  modules/data-model/qsets/api/src/main/java/io/uhndata/cards/qsets/api/QuestionnaireSetUtils.java
  modules/data-model/qsets/api/src/main/resources/SLING-INF/nodetypes/qsets.cnd
  modules/data-model/qsets/impl/src/main/java/io/uhndata/cards/qsets/internal/QuestionnaireSetUtilsImpl.java
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/SubmissionListener.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitChangeListener.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitInformationAdapterImpl.java
  modules/permissions-unsubmitted/src/main/java/io/uhndata/cards/permissions/internal/unsubmitted/UnsubmittedFormsRestrictionPattern.java
Labels: tested

#1808 CARDS-2578: Support more than one Survey Events form per visit
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/surveytracker/SurveyTracker.java
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
Labels: tested, urgent

#1811 [misc] Delete unimplemented AC+IP email schedules
  prems-resources/feature/src/main/features/feature.json
Labels: easy to review

#1815 CARDS-2582: Integrated Care form is marked as invalid if there is more than one provider in the Visit Information form
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
Labels: tested, easy to review

#1813 [misc] Upgrade the version of the nexus-staging-maven-plugin
  pom.xml
Labels: tested, easy to review

#1812 CARDS-2581: Integrated Care Survey Events are always incomplete
  modules/patient-portal/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
  prems-resources/feature/src/main/features/feature.json
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Survey events.xml
Labels: tested

#1809 [misc] Empty event date column configuration breaks clarity import
  modules/clarity-integration/src/main/java/io/uhndata/cards/clarity/importer/ClarityImportTask.java
Labels: tested, easy to review
