Repository data-team-uhn/cards, pull requests merged in 2024-10, with the labels that each got.

#1819 CARDS-2583: A visit subject without a Visit Information form causes subsequent visits to not have data forms autocreated
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitInformationAdapterImpl.java
Labels: tested, urgent

#1810 CARDS-2580 - Number question: allow min/max value to be specified but not enforced
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/internal/MinMaxValueValidator.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/NumberMinMaxTest.xml
Labels: tested, urgent

#1820 HERACLES-37: Update Participant Status Form - conditional date withdrawn field
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Participant Status.xml
Labels: Test me!

#1807 HERACLES-33: Historical & Lab Results range/unit revisions
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Historical Lab Results.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Laboratory Results.xml
Labels: urgent, Test me!

#1823 [misc] Do not require completion on Holter forms
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Holter.xml
Labels: tested, urgent, easy to review

#1829 [misc] Fix potential stacktrace when a request to validate patient credentials is sent without either MRN or HC
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
Labels: easy to review
