Repository data-team-uhn/cards, pull requests merged in 2024-12, with the labels that each got.

#1854 CARDS-2574: Some surveys have different alignment on the Patient Portal review screen
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, urgent, easy to review

#1862 CARDS-2614: Numbers from the unit of measurement field of numeric answers are appended to the answer value in the input after each re-edit
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: tested, urgent, easy to review

#1861 CARDS-2613: Units of measurement for numeric answers should support superscript
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, urgent, easy to review

#1830 CARDS-2590: A section that contains only an information entry will never be shown in view mode
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/SectionsWithInfoNodesTest.xml
Labels: urgent, Merge me!, Test me!, easy to review

#1846 CARDS-2606: Improve delete dialog with long names
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
Labels: Merge me!

#1859 CARDS-2586: YE new system quality and infection control questions to be added to existing PREMs surveys
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
Labels: tested, urgent, Merge me!
