Repository data-team-uhn/cards, pull requests merged in 2024-07, with the labels that each got.

#1788 CARDS-2540: Add ability to submit questionnaire responses starting with a certain day relative to the appointment, regardless of completion status
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, Merge me!, easy to review

#1789 CARDS-2544: Multivalued answers should be supported in email templates
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailTemplate.java
Labels: tested, urgent, Merge me!

#1664 CARDS-2450: Promote unsubmitted permissions to a core platform module
  distribution/sling-features.json
  modules/data-entry/src/main/features/permissions_unsubmitted.json
  modules/permissions-unsubmitted/pom.xml
  modules/permissions-unsubmitted/src/main/java/io/uhndata/cards/permissions/internal/unsubmitted/UnsubmittedFormsRestrictionFactory.java
  modules/permissions-unsubmitted/src/main/java/io/uhndata/cards/permissions/internal/unsubmitted/UnsubmittedFormsRestrictionPattern.java
  modules/pom.xml
  proms-resources/feature/src/main/features/feature.json
  proms-resources/pom.xml
Labels: tested, urgent

#1786 CARDS-2539 - Patient portal: better visibility of the Submit button on review page
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, urgent

#1794 CARDS-2556: Allow "Information" form entries to be displayed in view mode
  Utilities/FormImport/import.py
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Information-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Information.json
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/QuestionnaireUtils.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractFormToStringSerializer.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/FormToMarkdownProcessor.java
Labels: tested, Merge me!, easy to review

#1797 [misc] Adjustments to the IC survey
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
Labels: tested, urgent, easy to review

#1796 [misc] Minor refactoring in NewSubjectDialog and NewFormDialog
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/UserDashboard.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, easy to review
