Repository data-team-uhn/cards, pull requests merged in 2024-11, with the labels that each got.

#1832 [misc] Fix cyclomatic complexity checkstyle violation
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/ValidateCredentialsServlet.java
Labels: tested, easy to review

#1831 [misc] Update computed question expressions in Phone Call Follow-Up that fail on the backend because of unsupported js syntax
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Phone Call Follow-Up.xml
Labels: tested, easy to review

#1837 CARDS-2596: Wrong schedule configured for the YourExperience weekly exports
  heracles-resources/feature/src/main/features/feature.json
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review

#1836 CARDS-2597: Different file name used for the Survey Events YE export
  modules/export/src/main/java/io/uhndata/cards/export/ExportTask.java
Labels: urgent, easy to review

#1841 [MISC] Fix deleting questionnaire entries
  modules/data-entry/src/main/java/io/uhndata/cards/DeleteServlet.java
Labels: easy to review

#1838 [misc] Add json processor for exporting questionnaires to importable XMLs
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/ImportableProcessor.java
Labels: Test me!, low risk

#1834 CARDS-2593: Exporting very big files to S3 may fail
  heracles-resources/feature/src/main/features/feature.json
  modules/export/src/main/java/io/uhndata/cards/export/ExportTask.java
  modules/export/src/main/java/io/uhndata/cards/export/internal/formatters/CSVDataFormatter.java
  modules/export/src/main/java/io/uhndata/cards/export/internal/formatters/JSONDataFormatter.java
  modules/export/src/main/java/io/uhndata/cards/export/internal/formatters/RawFileDataFormatter.java
  modules/export/src/main/java/io/uhndata/cards/export/internal/formatters/TSVDataFormatter.java
  modules/export/src/main/java/io/uhndata/cards/export/internal/stores/FilesystemDataStore.java
  modules/export/src/main/java/io/uhndata/cards/export/spi/DataPipelineStep.java
  modules/export/src/main/java/io/uhndata/cards/export/spi/DataStore.java
  modules/s3-export/pom.xml
  modules/s3-export/src/main/java/io/uhndata/cards/s3export/S3DataStore.java
Labels: tested, urgent

#1835 CARDS-2594, CARDS-2595 and CARDS-2600: Unsubmitted cleanup fixes
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupScheduler.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/UnsubmittedFormsCleanupTask.java
  modules/utils/src/main/java/io/uhndata/cards/utils/DateUtils.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent
