Repository data-team-uhn/cards, pull requests merged in 2024-05, with the labels that each got.

#1766 CARDS-2519: The frontend evaluation of conditional sections fails to retrieve ZERO/FALSE values from the form context
  modules/data-entry/src/main/frontend/src/questionnaire/ConditionalSingle.jsx
Labels: tested, urgent, Merge me!, easy to review

#1764 CARDS-2518: Conditional sections show up when they shouldn't upon deselecting and reselecting their preconditions
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
Labels: tested, urgent, Merge me!

#1758 HERACLES-3 and HERACLES-4: Variable renaming and cleanup of ECC and PFU
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Phone Call Follow-Up.xml
Labels: tested, urgent, Merge me!

#1760 [MISC] Fix questions in repeated sections having the section name prefixed
  Utilities/FormImport/import.py
Labels: testing...

#1759 [misc] Allow automatically fetching project dependencies in the start script
  start_cards.sh
Labels: urgent

#1751 CARDS-2505: Allow filtering data forms by the status of the visit submission status
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/VisitSubmittedDataFilterFactory.java
Labels: tested

#1767 HERACLES-3: Made one question conditional
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Event - Clinical Cardiac.xml
Labels: tested, urgent, easy to review

#1769 CARDS-2524: The cards-slack-notifications module should be included in CARDS production container images
  Utilities/Packaging/Docker/cards_feature_list.txt
Labels: urgent, easy to review
