Repository data-team-uhn/cards, pull requests merged in 2024-06, with the labels that each got.

#1776 [misc] YE/YVM: added two new units to the survey list
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review

#1777 CARDS-2530: Question Option Descriptions not displayed
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: urgent, Test me!

#1770 HERACLES-12 and HERACLES-13, migrator bugfixes
  heracles-resources/backend/src/main/java/io/uhndata/cards/heracles/internal/migrators/Heracles8PAMigration.java
Labels: Merge me!

#1778 CARDS-2531: Backend computation of unary conditionals fails
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/ConditionalSectionUtils.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/UnaryConditionals.xml
Labels: Test me!, easy to review

#1771 HERACLES-14 / HERACLES-16: Triggered Assessment - Physician Interpretation (new form)
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Triggered Assessments.xml
Labels: tested, urgent, Merge me!

#1779 HERACLES-20 - Triggered Assessments: Add "None of the above" option t…o `triggered_subreason` question
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Triggered Assessments.xml
Labels: tested, urgent, easy to review

#1773 CARDS-2526: New form pagination variant: navigable
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPageNavigation.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
Labels: urgent, Test me!, testing...

#1781 CARDS-2532 - Patient portal: The survey counter looks awkward when there are 10 or more surveys to fill out
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: urgent, Test me!, easy to review

#1752 CARDS-2510: Fix computed questions always recalculating on checkin
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/ExpressionUtils.java
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/AnswersEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ComputedAnswersEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ExpressionUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ReferenceAnswersEditor.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/BackendComputedTest.xml
Labels: urgent

#1774 CARDS-2528: New comparators for Conditionals: "include any", "exclude any"
  modules/data-entry/src/main/frontend/src/questionnaire/ConditionalSingle.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Conditional.json
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/ConditionalSectionUtils.java
Labels: Test me!, easy to review, testing...

#1782 [misc] TimeQuestion fields are too wide
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
Labels: tested, urgent, easy to review

#1783 [MISC] Implement support for array of values for operands
  Utilities/FormImport/import.py
Labels: tested, easy to review

#1691 CARDS-2288: New question type: Selectable Areas
  modules/data-entry/pom.xml
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SelectableAreaQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Questionnaire.json
  modules/data-entry/src/main/media/SLING-INF/content/libs/cards/resources/media/dataEntry/fullBody.svg
  modules/data-entry/src/main/media/SLING-INF/content/libs/cards/resources/media/dataEntry/fullBodyMap.json
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/dataEntry/SelectableArea/Face.json
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/dataEntry/SelectableArea/FullBody.json
  modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  pom.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/SelectableAreasTest.xml
Labels: urgent, Merge me!

#1775 CARDS-2529: Conditional sections show up when they shouldn't upon deselecting and reselecting their preconditions (again)
  modules/data-entry/src/main/frontend/src/questionnaire/ConditionalSingle.jsx
Labels: tested, easy to review

#1784 CARDS-2537: Question matrix sticky header is covered by page header in patient portal
  modules/patient-portal/src/main/frontend/src/patient-portal/Header.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, urgent, easy to review

#1785 CARDS-2538: Support compact layout for sections in Patient Portal
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/portalTheme.jsx
Labels: tested, urgent, easy to review

#1780 HERACLES-17 / HERACLES-19: Holter form
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Holter.xml
Labels: tested

#1787 HERACLES-30: Triggered Assessments - new triggered_cohort question
  heracles-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Triggered Assessments.xml
Labels: tested, easy to review
