Repository data-team-uhn/cards, pull requests merged in 2024-02, with the labels that each got.

#1687 CARDS-2476 / CARDS-2477: The CARDS build process should fail if conflicting NPM/Yarn dependencies are specified
  aggregated-frontend/src/main/frontend/webpack_script.py
  modules/patient-portal/src/main/frontend/package.json
  modules/permissions-trusted/src/main/frontend/package.json
  modules/statistics/src/main/frontend/package.json
Labels: easy to review

#1688 CARDS-2481: Update the yarn.lock file for the aggregated-frontend
  aggregated-frontend/src/main/frontend/yarn.lock
Labels: easy to review

#1671 CARDS-2465: The cards-s3-export module should not be enabled by default
  Utilities/Packaging/Docker/cards_feature_list.txt
  distribution/Dockerfile
  distribution/docker_entry.sh
  distribution/get_project_dependency_features.py
  distribution/sling-features.json
  distribution/src/main/features/core/s3-export.json
  start_cards.sh
Labels: urgent, Test me!

#1686 CARDS-2281: Only count the total number of subjects for a type in the administration
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectTypes.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/serialize/SubjectTypeInstanceCountProcessor.java
Labels: tested

#1693 CARDS-2451: Publish releases on Maven Cental Repository
  pom.xml
Labels: tested

#1696 [misc] Exclude project-specific text files from license check
  pom.xml
Labels: easy to review

#1668 CARDS-2460: Compact layout for sections
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Section.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/CompactSectionsTest.xml
Labels: tested, on hold

#1690 MISC: Update importer for repeated section from fixed list
  Utilities/FormImport/import.py
Labels: tested

#1679 CARDS-2471: Conditional improvements
  Utilities/FormImport/import.py
  heracles-resources/clinical-data/util/import.py
  kids-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/6-21NDVariables.xml
  kids-resources/clinical-data/util/heartCentreData.py
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ConditionalSingle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireAutocomplete.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Conditional.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/form-completion-status/src/main/java/io/uhndata/cards/formcompletionstatus/ConditionalSectionUtils.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DecimalConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DoubleConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/LongConditionalTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/StringConditionalTest.xml
Labels: tested

#1697 CARDS-2468 - Cards4Care: new Exercise Diaries form
  cardiac-rehab-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Exercise Diaries.xml
Labels: tested

#1706 [LFS] Added ability to upload a pedigree file, fixed typo
  lfs-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Patient information.xml
  lfs-resources/tissue-metrix/src/main/resources/SLING-INF/content/Questionnaires/TissueMetrix.xml
Labels: tested, urgent, easy to review

#1704 [misc] Questionnaire import utility: added support for `requireCompletion` and `hideAnswerInstructions` questionnaire properties
  Utilities/FormImport/import.py
Labels: easy to review

#1703 [misc] Questionnaire import utility: added support for the new conditional operators "includes", "excludes" that were introduced by CARDS-2471
  Utilities/FormImport/import.py
Labels: Test me!, easy to review

#1705 [misc] Questionnaire import utility: autogenerated conditional sections' ids should have "section_" as prefix instead of "section" as suffix
  Utilities/FormImport/import.py
Labels: easy to review

#1699 CARDS-2430: Make data filters extensible and reusable
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/DataProcessor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/CreatedAfter.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/CreatedBefore.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/Creator.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/LastAuthor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/ModifiedAfter.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/ModifiedBefore.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/filters/StatusFlags.java
  modules/patient-portal/pom.xml
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/ClinicDataFilterFactory.java
  modules/utils/pom.xml
  modules/utils/src/main/java/io/uhndata/cards/serialize/DataFilters.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/DataFiltersParser.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/DefaultDataFilters.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/DefaultDataFiltersParser.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/BaseFilterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/DataFilter.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/DataFilterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/utils/DateUtils.java
Labels: urgent, Merge me!

#1702 CARDS-2383: YVM survey updates
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/YVM.xml
Labels: tested, urgent, Merge me!
