Repository data-team-uhn/cards, pull requests merged in 2025-09, with the labels that each got.

#2053 [misc] YE: Updated the spacing / letter casing of the "Don't know / Not sure" answer options to be consistent across active surveys
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/IC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
Labels: urgent, Merge me!, easy to review

#2060 CARDS-2750: Clinician dashboard views expand links are incorrect
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
Labels: tested, Merge me!, easy to review, low risk

#2058 [misc] Large sample SQLs should be split into batches
  compose-cluster/mssql/generate_test_YE_sql.py
Labels: Merge me!, easy to review, low risk

#2067 CARDS-2764: Outlined textboxes displayed for text answers should be as wide as the question card
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: tested, easy to review

#1929 CARDS-1761: Adapt React Date / Time pickers
  modules/commons/src/main/frontend/src/components/DateTimeUtilities.jsx
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionYear.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/variants/src/main/frontend/src/VariantFilesContainer.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/SurveyNoOverwrite/Cardio.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateFormatsTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ServersideComputedTest.xml
Labels: Test me!

#1980 CARDS-2585: More consistent treatment of out-of-range numerical answers and non-regexp-matching text answers
  modules/commons/src/main/frontend/src/components/DateTimeUtilities.jsx
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/DateFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/AnswerInstructions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/ComputedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionMonth.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionYear.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTimeline.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/TimeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/variants/src/main/frontend/src/VariantFilesContainer.jsx
  proms-resources/clinical-data/src/main/resources/SLING-INF/content/SurveyNoOverwrite/Cardio.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ComputedTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DateFormatsTest.xml
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/ServersideComputedTest.xml
Labels: Test me!, easy to review, low priority

#2079 CARDS-1761: Adapt React Date / Time pickers
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
Labels: easy to review
