Repository data-team-uhn/cards, pull requests merged in 2025-05, with the labels that each got.

#1963 [misc] Fix invalid questionnaire description type
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/UnaryConditionals.xml
Labels: easy to review

#1964 [misc] material-react-table is not a build dependency
  aggregated-frontend/src/main/frontend/package.json
Labels: easy to review

#1969 [misc] Fix condition operator in Pagination Test questionnaire
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/PaginationTest.xml
Labels: easy to review

#1970 CARDS-2684: Print functionality is broken
  aggregated-frontend/src/main/frontend/package.json
  aggregated-frontend/src/main/frontend/yarn.lock
  modules/data-entry/src/main/frontend/src/questionnaire/PrintPreview.jsx
Labels: tested, urgent, easy to review

#1968 CARDS-2682: Introduce a new property for numeric questions: disableNegativeInput
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question-hints.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: urgent, easy to review

#1961 Refactored the Downtime Banner and Demo Warning Banner components to reduce custom styling
  modules/demo-banner/src/main/frontend/src/demoBanner.jsx
  modules/downtime-warning-banner/src/main/frontend/src/downtimeBanner.jsx
Labels: tested, Merge me!, easy to review

#1974 [bugfix] Broken production builds due to missing asset dependency declarations
  modules/commons/src/main/frontend/src/assetManager.jsx
  modules/data-entry/src/main/frontend/assets.config
  modules/data-entry/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
Labels: tested, urgent, regression

#1922 CARDS-2514: New locking module
  Utilities/Packaging/Docker/cards_feature_list.txt
  compose-cluster/generate_compose_yaml.py
  distribution/docker_entry.sh
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectActions.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/actionsManager.jsx
  modules/data-model/subjects/api/pom.xml
  modules/data-model/subjects/api/src/main/resources/SLING-INF/content/apps/cards/ExtensionPoints/SubjectActions.json
  modules/locking/pom.xml
  modules/locking/src/main/features/feature.json
  modules/locking/src/main/frontend/assets.config
  modules/locking/src/main/frontend/src/locking/SubjectLockAction.jsx
  modules/locking/src/main/java/io/uhndata/cards/locking/LockServlet.java
  modules/locking/src/main/java/io/uhndata/cards/locking/LockedRestrictionFactory.java
  modules/locking/src/main/java/io/uhndata/cards/locking/LockedRestrictionPattern.java
  modules/locking/src/main/java/io/uhndata/cards/locking/LockedStatusFlagEditor.java
  modules/locking/src/main/java/io/uhndata/cards/locking/LockedStatusFlagEditorProvider.java
  modules/locking/src/main/java/io/uhndata/cards/locking/api/LockError.java
  modules/locking/src/main/java/io/uhndata/cards/locking/api/LockException.java
  modules/locking/src/main/java/io/uhndata/cards/locking/api/LockManager.java
  modules/locking/src/main/java/io/uhndata/cards/locking/api/LockWarning.java
  modules/locking/src/main/java/io/uhndata/cards/locking/internal/IncompleteFormsPrecondition.java
  modules/locking/src/main/java/io/uhndata/cards/locking/internal/LockManagerImpl.java
  modules/locking/src/main/java/io/uhndata/cards/locking/internal/LockRepositoryInitializer.java
  modules/locking/src/main/java/io/uhndata/cards/locking/spi/LockPrecondition.java
  modules/locking/src/main/resources/SLING-INF/content/Extensions/SubjectActions/SubjectLockAction.json
  modules/locking/src/main/resources/SLING-INF/content/libs/cards/resources/assetDependencies.json
  modules/locking/src/main/resources/SLING-INF/nodetypes/locking.cnd
  modules/pom.xml
  start_cards.sh
  test-resources/src/main/features/feature.json
Labels: urgent, Test me!, large PR

#1976 CARDS-2677: Quick search results page: the title is a button, should be a heading
  modules/commons/src/main/frontend/src/headerStyle.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchResults.jsx
Labels: easy to review, low risk, low priority

#1978 [bugfix] Questionnaire editor displays stale date after saving and previewing
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: tested, Merge me!, easy to review

#1977 [misc] Code optimisation
  modules/commons/src/main/frontend/src/SearchBar.jsx
  modules/commons/src/main/frontend/src/components/DropdownsDatePicker.jsx
  modules/commons/src/main/frontend/src/components/MainActionButton.jsx
  modules/commons/src/main/frontend/src/components/NewItemButton.jsx
  modules/commons/src/main/frontend/src/components/UserInputAssistant.jsx
  modules/commons/src/main/frontend/src/components/dragAndDrop.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/ExportButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PermissionsButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPageNavigation.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPagination.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NCRNote.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionMatrix.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectIdentifier.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/CreationMenu.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/EditDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownText.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/MarkdownTextField.jsx
  modules/data-entry/src/main/frontend/src/resourceQuery/ResourceQuery.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBranch.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyBrowser.jsx
  modules/data-entry/src/main/frontend/src/vocabQuery/VocabularyTree.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminResourceListing.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/AdminNavbarLinks.jsx
  modules/login/src/main/frontend/src/login/loginForm.js
  modules/login/src/main/frontend/src/login/signUpForm.js
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ToUDialog.jsx
  modules/statistics/src/main/frontend/src/Statistics/AdminStatistics.jsx
  modules/variants/src/main/frontend/src/variantFilesContainer.jsx
  modules/vocabularies/src/main/frontend/src/vocabulariesAdminPage.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyDirectory.jsx
Labels: easy to review, low priority

#1985 CARDS-2696: [YE] Add description to open-ended questions in ED, Inpatient, Rehab surveys
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OAIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/OED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/Rehab.xml
Labels: urgent, easy to review
