Repository data-team-uhn/cards, pull requests merged in 2025-10, with the labels that each got.

#2084 CARDS-2776: 0 and false values are lost when editing and saving forms without any other changes
  modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
Labels: tested, urgent, Merge me!

#2074 CARDS-2768: On the patient portal, the survey questions should be vertically aligned to the top
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: tested, urgent, Merge me!, easy to review

#2088 [misc] Fix wrongly committed docker tag
  compose-cluster/CardsDockerTagProperty.py
Labels: urgent

#2087 CARDS-2773: Save request do not have enough time to finish before we check if the form is complete
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
Labels: easy to review
