Repository data-team-uhn/cards, pull requests merged in 2025-08, with the labels that each got.

#2039 CARDS-2734: Allow specifying more than one node property filter in the pagination servlet
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectView.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
  modules/data-entry/src/main/java/io/uhndata/cards/CountServlet.java
  modules/data-entry/src/main/java/io/uhndata/cards/PaginationServlet.java
Labels: WIP

#2018 CARDS-2664: Add support for Notes on Autocreated answers
  modules/data-entry/src/main/frontend/src/questionnaire/AutocreatedQuestion.jsx
Labels: easy to review

#2040 CARDS-2736: Change the default to not count all results in the query endpoint
  modules/data-entry/src/main/java/io/uhndata/cards/QueryBuilder.java
Labels: urgent, easy to review

#2051 [misc] Remove unused variants icon from the homepage module
  modules/homepage/src/main/frontend/assets.config
Labels: easy to review

#2054 [misc] Optimize the handling on null/empty strings when parsing dates
  modules/utils/src/main/java/io/uhndata/cards/utils/DateUtils.java
Labels: urgent, easy to review

#2048 CARDS-2737: Improve the UI for the patient portal page layout
  modules/commons/src/main/frontend/src/components/ErrorPage.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientIdentification.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/SurveyInstructionsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/Unsubscribe.jsx
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/CPES.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/OO.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/OOIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/SurveyInstructions.xml
Labels: urgent, Test me!

#2056 CARDS-2737: Improve the UI for the patient portal page layout
  modules/patient-portal/src/main/frontend/src/patient-portal/QuestionnaireSet.jsx
Labels: easy to review, low risk

#2055 YE: The CPESIC survey should no longer be sent out for visit dates from Oct 1st onward
  prems-resources/backend/src/main/java/io/uhndata/cards/prems/internal/importer/SendCPESForDepartmentFrequency.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent, easy to review
