Repository data-team-uhn/cards, pull requests merged in 2025-07, with the labels that each got.

#2006 CARDS-2696: [YE] Add description to open-ended question in CPESIC
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/CPESIC.xml
Labels: urgent, Test me!, easy to review

#2008 [misc] Use the new way to publish artifacts to maven central
  pom.xml
Labels: urgent, easy to review

#2009 [misc] Fix bad javadoc
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/ExcludeDefaultPropertiesProcessor.java
Labels: easy to review

#2007 CARDS-2717: Add belongsToSurvey script for updating old forms
  modules/data-model/links/api/src/main/java/io/uhndata/cards/links/api/LinkUtils.java
  modules/data-model/links/impl/src/main/java/io/uhndata/cards/links/internal/LinkUtilsImpl.java
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/libs/cards/Questionnaire/addBelongsToSurveyLinks.html.esp
Labels: urgent

#2024 CARDS-2720: Untrusted users warning no longer shows up
  modules/permissions-trusted/src/main/resources/SLING-INF/content/Extensions/PendingUsersView/PendingUsersView.json
Labels: easy to review

#2022 [misc] Fixed lock button size to be consistent with others
  modules/locking/src/main/frontend/src/locking/SubjectLockAction.jsx
Labels: easy to review, low priority

#2026 CARDS-2621: Computed answers depending on Reference answers fail to be computed on the backend
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/ComputedAnswersEditor.java
Labels: easy to review, java

#2028 CARDS-2728: [YE] Add a statement at the top of the YVM survey to clarify that everyone visiting the Centre receives it regardless of their diagnosis
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/YVM.xml
Labels: easy to review

#2030 [misc] Improvement of the form pagination progress bar look
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
Labels: Test me!, easy to review

#2032 [misc] Removed leftover mention of "DATA-PRO" from generic CARDS module
  modules/patient-portal/src/main/resources/SLING-INF/nodetypes/patient-portal.cnd
Labels: easy to review, low risk
