Repository data-team-uhn/cards, pull requests merged in 2025-01, with the labels that each got.

#1844 [misc] Update json importability processor with requiredSubjectTypes support
  modules/utils/src/main/java/io/uhndata/cards/serialize/ResourceToJsonAdapterFactory.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/ImportableProcessor.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/spi/ResourceJsonProcessor.java
Labels: Test me!

#1845 CARDS-2605: Remove patient names from email to: fields
  modules/email-notifications/src/main/java/io/uhndata/cards/emailnotifications/EmailUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentEmailNotificationsFactory.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/GeneralNotificationsTask.java
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/CPES/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-AC-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-AC-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-AC/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-AC/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PMH-YVM/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/ReminderNotification/ROOT.json
Labels: tested

#1863 CARDS-2611: Support for enforcing specific subject identifier formats
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTypeDialog.jsx
  modules/data-model/subjects/api/src/main/resources/SLING-INF/nodetypes/subjects.cnd
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectIdPatternValidator.java
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectIdPatternValidatorProvider.java
Labels: tested, urgent

#1855 [dependency-upgrade] Vulnerability fixes
  modules/http-requests/pom.xml
  modules/s3-export/pom.xml
  modules/s3-export/src/main/features/feature.json
  modules/vocabularies/pom.xml
Labels: dependencies, low priority

#1870 CARDS-2623: YE: Update the number of questions in email templates and the survey completion time estimates on the welcome screen to account for the newly added questions
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/AIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ED.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/EDIPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/IPIC.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/Rehab.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-ED/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-EDIP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-ED/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-EDIP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IC-IP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-IP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/UHN-Rehab/mailTemplates/InitialInvitation/bodyTemplate.txt
Labels: urgent, Test me!

#1873 CARDS-2628: Information nodes crash print preview
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/AbstractFormToStringSerializer.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/InformationNodesTest.xml
Labels: tested, easy to review

#1825 CARDS-2587: Malfunction in forms with mandatory file questions and requireCompletion = true
  modules/data-entry/src/main/frontend/src/questionnaire/FileQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnairePreview.jsx
Labels: tested

#1885 [misc] Removed unused withRouter from components
  modules/data-entry/src/main/frontend/src/dataHomepage/EditButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PermissionsButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/PrintButton.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/QuestionnaireItemCard.jsx
  modules/homepage/src/main/frontend/src/themePage/Navbars/HeaderSearchBar.jsx
  modules/principals/src/main/frontend/src/Userboard/Users/usersmanager.jsx
Labels: Test me!, easy to review

#1884 [misc] Removed dead code from DeleteButton component
  modules/data-entry/src/main/frontend/src/dataHomepage/DeleteButton.jsx
Labels: Test me!, easy to review

#1886 CARDS-2624: Rename PM Acute Care survey to PM Outpatient Oncology
  compose-cluster/generate_compose_yaml.py
  prems-resources/clinical-data/pom.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/PM-OO-IP.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Extensions/Sidebar/PM-OO.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Questionnaires/PMOO.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Statistics/OO-Overall.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/ClinicMapping.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/OO.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/Survey/OOIP.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityImport/PMH-OO.xml
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO-IP/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/InitialInvitation/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/InitialInvitation/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/InitialInvitation/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/InitialInvitation/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/ReminderNotification/ROOT.json
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/ReminderNotification/bodyTemplate.footer.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/ReminderNotification/bodyTemplate.html
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clinics/PM-OO/mailTemplates/ReminderNotification/bodyTemplate.txt
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/config/CopyAnswers/Questionnaires/PMOO.json
  prems-resources/feature/src/main/features/feature.json
Labels: tested, urgent, large PR

#1882 [misc] Removed defaultProps from Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: Test me!, easy to review, testing...

#1880 [misc] Add a warning for subject type pattern input field if any subject of this type already exists
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTypeDialog.jsx
Labels: question, tested

#1879 CARDS-2629: Display full datetime when hovering user-friendly dates like "yesterday"
  modules/data-entry/src/main/frontend/src/questionnaire/DateQuestionFull.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: tested

#1857 [code-cleanup] Removed unused imports and leftover code from refactoring
  Utilities/Development/list_extension_points.py
  Utilities/FormImport/import.py
  Utilities/SecurityScanning/github_get_docker_image_digest.py
  aggregated-frontend/src/main/frontend/webpack.config-template.js
  aggregated-frontend/src/main/frontend/webpack_script.py
  compose-cluster/generate_compose_yaml.py
  modules/commons/src/main/frontend/src/assetManager.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/ListFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/NumericFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/QuestionnaireFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/FilterComponents/ResourceFilter.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/NewFormDialog.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Subjects.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/AutocreatedQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/FormPageNavigation.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Note.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SelectableAreaQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ConditionalValueInput.jsx
  modules/data-entry/src/main/frontend/src/resourceQuery/ResourceQuery.jsx
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormsQuickSearchEngine.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/QuestionnaireQuickSearchEngine.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/SubjectHierarchyValidator.java
  modules/downtime-warning-banner/src/main/frontend/src/DowntimeWarningConfiguration.jsx
  modules/google-apis/src/main/frontend/src/googleApiKeyAdminPage.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminConfigScreen.jsx
  modules/homepage/src/main/frontend/src/themePage/QuickSearchConfiguration.jsx
  modules/homepage/src/main/frontend/src/themePage/index.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/DashboardSettingsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PatientAccessConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/PrintHeader.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/SurveyInstructionsConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/ToUConfiguration.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/UnsubscribeLink.jsx
  modules/statistics/src/main/frontend/src/Statistics/Statistic.jsx
  modules/vocabularies/src/main/frontend/src/vocabularyActions.jsx
  modules/vocabularies/src/main/java/io/uhndata/cards/vocabularies/internal/OboParser.java
Labels: low priority

#1890 CARDS-2633: Adding a new child subject under a subject with an invalid indentifier fails
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectIdPatternValidator.java
  modules/data-model/subjects/impl/src/main/java/io/uhndata/cards/subjects/internal/SubjectIdPatternValidatorProvider.java
Labels: tested

#1888 CARDS-2619: In the New subject dialog with a single subject type, that type is not always selected automatically
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectSelector.jsx
Labels: tested, easy to review, low risk, low priority

#1878 CARDS-2625: Replace deprecated react-beautiful-dnd with pragmatic-drag-and-drop
  aggregated-frontend/src/main/frontend/yarn.lock
  modules/data-entry/src/main/frontend/package.json
  modules/data-entry/src/main/frontend/src/questionnaireEditor/AnswerOptions.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/DroppableAnswerOption.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/DroppableAnswerOptionList.jsx
Labels: tested

#1868 CARDS-2618: Replace Livetable with MaterialReactTable in administration screens
  modules/data-entry/src/main/frontend/src/dataHomepage/EditButton.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/SubjectTypes.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/SubjectTypeDialog.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NewQuestionnaireDialog.jsx
  modules/homepage/src/main/frontend/src/adminDashboard/AdminResourceListing.jsx
  modules/patient-portal/src/main/frontend/src/patient-portal/Clinics.jsx
  modules/statistics/src/main/frontend/src/Statistics/AdminStatistics.jsx
Labels: tested
