Repository data-team-uhn/cards, pull requests merged in 2025-04, with the labels that each got.

#1939 CARDS-2665: Add support for configuring the precision of decimal/double answers
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/NumberInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: tested, urgent, Merge me!, easy to review

#1821 CARDS-2577: New answer type: identifier
  Utilities/FormImport/import.py
  modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/IdentifierQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/data-model/forms/api/src/main/resources/SLING-INF/content/oak%3Aindex/forms.json
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/IdentifierAnswerEditor.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/IdentifierAnswerEditorProvider.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/IdentifierTest.xml
Labels: tested, urgent, Merge me!

#1937 CARDS-2662: Update the Outpatient Oncology schema name and columns
  compose-cluster/generate_compose_yaml.py
  prems-resources/clinical-data/src/main/resources/SLING-INF/content/apps/cards/clarityImport/PMH-OO.xml
Labels: urgent

#1941 [misc] Removed deprecated or unused dependencies
  aggregated-frontend/src/main/frontend/package.json
  aggregated-frontend/src/main/frontend/yarn.lock
Labels: dependencies, high priority

#1942 [dependency] Bumped dev dependencies
  aggregated-frontend/src/main/frontend/package.json
  aggregated-frontend/src/main/frontend/webpack.config-template.js
  aggregated-frontend/src/main/frontend/yarn.lock
  pom.xml
Labels: dependencies, high priority

#1943 [dependency] Minor UI dependencies version updates
  aggregated-frontend/src/main/frontend/package.json
  aggregated-frontend/src/main/frontend/yarn.lock
Labels: dependencies, high priority

#1932 [misc] Make variant required for the SelectableArea questions
  modules/data-entry/src/main/frontend/src/questionnaire/SelectableAreaQuestion.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/ListInput.jsx
  modules/data-entry/src/main/frontend/src/questionnaireEditor/Question.json
Labels: Merge me!, easy to review

#1955 CARDS-2676: Default error page is broken again
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
Labels: easy to review

#1956 [misc] <sly> markup present in the HTML of generic error pages
  modules/commons/src/main/resources/SLING-INF/content/apps/sling/servlet/errorhandler/default.esp
Labels: easy to review

#1957 CARDS-2674: Questionnaire export no longer shows questions/sections to include/exclude
  modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
Labels: tested, easy to review

#1958 CARDS-2671: After changing the password, a confirmation alert is displayed in the wrong place
  modules/homepage/src/main/frontend/src/themePage/Navbars/AdminNavbarLinks.jsx
  modules/principals/src/main/frontend/src/Userboard/Users/changeuserpassworddialogue.jsx
Labels: tested, easy to review
