Repository data-team-uhn/cards, pull requests merged in 2025-06, with the labels that each got.

#1983 CARDS-2694: Make 1 instead of 0 the default value for the maxAnswers property of cards:Section nodes
  modules/data-model/forms/api/src/main/resources/SLING-INF/nodetypes/forms.cnd
Labels: easy to review, low risk

#1909 CARDS-2626: Patient portal: Flexible scheduling of survey invitation emails
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/api/PatientAccessConfiguration.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AbstractEmailNotification.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/AppointmentUtils.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/emailnotifications/GeneralNotificationsTask.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/PatientAccessConfigurationImpl.java
Labels: urgent, java

#1995 [misc] Update gitignore for Your Experience backup exports
  .gitignore
Labels: easy to review

#1984 CARDS-2672: Json processor that excludes properties if their value is the default value
  modules/data-model/forms/api/src/main/java/io/uhndata/cards/forms/api/FormUtils.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/FormUtilsImpl.java
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/ExcludeFilesProcessor.java
  modules/utils/src/main/java/io/uhndata/cards/serialize/internal/ExcludeDefaultPropertiesProcessor.java
  test-resources/src/main/resources/SLING-INF/content/Questionnaires/DefaultValsExportTest.xml
Labels: Merge me!, Test me!, low risk, java

#1990 CARDS-2700: QuestionnaireAutocomplete showing sections in conditional value reference select after questionnaire add/remove entry
  modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
Labels: Merge me!

#1994 CARDS-2706: Improve the visibility of the button that adds another recurring section instance
  modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
Labels: tested, Merge me!

#1991 CARDS-2702: Add link between Survey Events form and related forms
  modules/data-model/links/api/src/main/java/io/uhndata/cards/links/api/LinkUtils.java
  modules/data-model/links/impl/src/main/java/io/uhndata/cards/links/internal/LinkUtilsImpl.java
  modules/patient-portal/pom.xml
  modules/patient-portal/src/main/features/feature.json
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/SurveyEventsFormListener.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/surveytracker/SurveyTracker.java
  modules/patient-portal/src/main/resources/SLING-INF/content/apps/cards/LinkDefinitions/belongsToSurvey.xml
  modules/patient-portal/src/main/resources/SLING-INF/content/apps/cards/LinkDefinitions/includesSurveyForm.xml
Labels: urgent

#1998 CARDS-2703: Add selector to include Survey Event form link
  modules/data-model/forms/impl/src/main/java/io/uhndata/cards/forms/internal/serialize/QuestionnaireToCsvProcessor.java
  modules/data-model/links/api/src/main/java/io/uhndata/cards/links/api/LinkUtils.java
  modules/data-model/links/impl/src/main/java/io/uhndata/cards/links/internal/LinkUtilsImpl.java
  modules/patient-portal/src/main/java/io/uhndata/cards/patients/internal/serialize/FormToSurveyLinkProcessor.java
  prems-resources/feature/src/main/features/feature.json
Labels: urgent

#1996 [misc] Fix Tooltip positioning for LiveTable Edit action
  modules/data-entry/src/main/frontend/src/dataHomepage/FormView.jsx
  modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
Labels: Test me!, easy to review, low risk, low priority

#2000 CARDS-2712: Visit forms are sometimes displayed on the patient chart
  modules/data-entry/src/main/frontend/src/questionnaire/Subject.jsx
Labels: easy to review

#2005 [misc] Minor polishing of multiple choice
  modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
Labels: urgent, Test me!, easy to review
